### ISSUE TITLE
signaling channel crash

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#147] opened 2020-01-15 04:44 UTC
Websocket is not properly established.  singaling channel code tried again, and then segfault.
Backtracce is as the following:

```
2020-01-15 00:06:46 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000001, Next state: 0x0000000000000002
2020-01-15 00:06:46 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000004
2020-01-15 00:06:47 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000010
2020-01-15 00:06:47 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
2020-01-15 00:06:48 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000040
2020-01-15 00:06:48 INFO    signalingClientConnectSync(): Signaling Client Connect Sync
2020-01-15 00:06:48 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000080
2020-01-15 00:06:53 ERROR   connectSignalingChannelLws(): operation returned status code: 0x0000000f
2020-01-15 00:06:53 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000080, Next state: 0x0000000000000004
2020-01-15 00:06:53 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000010
2020-01-15 00:06:54 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
2020-01-15 00:06:55 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000040
2020-01-15 00:06:55 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000080
2020-01-15 00:06:55 WARN    lwsWssCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-01-15 00:06:56 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000080, Next state: 0x0000000000000004
2020-01-15 00:06:57 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000010
2020-01-15 00:06:57 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
2020-01-15 00:06:58 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000040
2020-01-15 00:06:58 INFO    stepStateMachine(): State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000080
```
```
./webrtc(_Z15segsegv_handleri+0x4a)[0x5649f3a456da]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f7eb88cef20]
./libkvsWebrtcSignalingClient.so(lwsWssCallbackRoutine+0xe2)[0x7f7eb9bf4c7d]
/home/weizhang/git/kvs-x86/open-source/local/lib/libwebsockets.so.15(+0x111a8)[0x7f7eb7ad71a8]
/home/weizhang/git/kvs-x86/open-source/local/lib/libwebsockets.so.15(+0x1581f)[0x7f7eb7adb81f]
/home/weizhang/git/kvs-x86/open-source/local/lib/libwebsockets.so.15(+0x2b6e3)[0x7f7eb7af16e3]
/home/weizhang/git/kvs-x86/open-source/local/lib/libwebsockets.so.15(lws_service+0x45)[0x7f7eb7adb675]
./libkvsWebrtcSignalingClient.so(lwsCompleteSync+0x4c3)[0x7f7eb9bf5a4c]
./libkvsWebrtcSignalingClient.so(lwsListenerHandler+0xdc)[0x7f7eb9bf8b0d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f7eb97cf6db]
```

**Comment by Sean-Der** [comment] 2020-01-21 21:21
@zwei333 This *should* be fixed now that #100 is merged.

I am closing for now, if this is continuing to happen though please re-open! Since we don't have an easy reproduce this is still a speculative fix.

thanks

**Closed by Sean-Der** 2020-01-21 21:21 UTC
