### ISSUE TITLE
[BUG]2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:

### ISSUE THREAD

**Issue by pppaulpeter** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1511] opened 2022-07-06 11:21 UTC
**Hi ,
i have successfully cross-compailed the library and sample, when i try to run the sample on the arm device, it seems i have an issue when using openssl library on embeded  device, the log as following:**
_/kvsWebrtcClientMaster mychannel
[KVS Master] Using trickleICE by default
[KVS Master] Created signaling channel mychannel
[KVS Master] Finished setting audio and video handlers
[KVS Master] Checked sample video frame availability....available
[KVS Master] Checked sample audio frame availability....available
2022-07-06 11:59:41 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:41 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
[KVS Master] KVS WebRTC initialization completed successfully
[2022/07/06 11:59:41:2277] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:41:2278] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:41:2280] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:41:2282] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:41:2284] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:41:2292] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:41:2293] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:41:2293] N:  -- [vh|1|default||-1] (1) 973Î¼s
[2022/07/06 11:59:41:2294] E: Failed to create default vhost
[2022/07/06 11:59:41:2294] N:  -- [wsi|0|pipe] (0) 1.405ms
[2022/07/06 11:59:41:2299] N:  -- [vh|0|netlink] (0) 1.719ms
2022-07-06 11:59:41 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:41 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  7

2022-07-06 11:59:42 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:42 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
[2022/07/06 11:59:43:1937] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:43:1937] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:43:1938] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:43:1939] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:43:1940] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:43:1943] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:43:1944] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:43:1944] N:  -- [vh|1|default||-1] (1) 430Î¼s
[2022/07/06 11:59:43:1944] E: Failed to create default vhost
[2022/07/06 11:59:43:1945] N:  -- [wsi|0|pipe] (0) 646Î¼s
[2022/07/06 11:59:43:1945] N:  -- [vh|0|netlink] (0) 642Î¼s
2022-07-06 11:59:43 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:43 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  6

2022-07-06 11:59:43 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:43 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
2022-07-06 11:59:44 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:44 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
2022-07-06 11:59:45 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:45 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
2022-07-06 11:59:46 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:46 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
[2022/07/06 11:59:46:3525] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:46:3527] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:46:3530] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:46:3532] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:46:3533] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:46:3538] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:46:3538] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:46:3538] N:  -- [vh|1|default||-1] (1) 541Î¼s
[2022/07/06 11:59:46:3539] E: Failed to create default vhost
[2022/07/06 11:59:46:3540] N:  -- [wsi|0|pipe] (0) 1.014ms
[2022/07/06 11:59:46:3541] N:  -- [vh|0|netlink] (0) 918Î¼s
2022-07-06 11:59:46 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:46 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  5

2022-07-06 11:59:47 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:47 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
^C[2022/07/06 11:59:47:5637] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:47:5638] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:47:5639] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:47:5640] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:47:5641] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:47:5648] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:47:5649] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:47:5649] N:  -- [vh|1|default||-1] (1) 826Î¼s
[2022/07/06 11:59:47:5650] E: Failed to create default vhost
[2022/07/06 11:59:47:5651] N:  -- [wsi|0|pipe] (0) 1.170ms
[2022/07/06 11:59:47:5653] N:  -- [vh|0|netlink] (0) 1.271ms
2022-07-06 11:59:47 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:47 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  4

2022-07-06 11:59:48 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:48 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
^C[2022/07/06 11:59:49:0792] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:49:0792] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:49:0793] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:49:0794] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:49:0794] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:49:0798] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:49:0798] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:49:0799] N:  -- [vh|1|default||-1] (1) 429Î¼s
[2022/07/06 11:59:49:0799] E: Failed to create default vhost
[2022/07/06 11:59:49:0800] N:  -- [wsi|0|pipe] (0) 659Î¼s
[2022/07/06 11:59:49:0800] N:  -- [vh|0|netlink] (0) 652Î¼s
2022-07-06 11:59:49 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:49 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  3

2022-07-06 11:59:49 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:49 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
^C[2022/07/06 11:59:49:2490] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:49:2490] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:49:2491] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:49:2492] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:49:2493] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:49:2496] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:49:2496] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:49:2497] N:  -- [vh|1|default||-1] (1) 403Î¼s
[2022/07/06 11:59:49:2497] E: Failed to create default vhost
[2022/07/06 11:59:49:2497] N:  -- [wsi|0|pipe] (0) 618Î¼s
[2022/07/06 11:59:49:2501] N:  -- [vh|0|netlink] (0) 958Î¼s
2022-07-06 11:59:49 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:49 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  2

2022-07-06 11:59:50 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:50 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
2022-07-06 11:59:51 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:51 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
2022-07-06 11:59:52 ERROR   createRtcCertificate(): operation returned status code: 0x59000001
2022-07-06 11:59:52 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
^C[2022/07/06 11:59:52:5566] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:52:5566] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:52:5567] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:52:5568] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:52:5569] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:52:5572] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:52:5576] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:52:5576] N:  -- [vh|1|default||-1] (1) 750Î¼s
[2022/07/06 11:59:52:5576] E: Failed to create default vhost
[2022/07/06 11:59:52:5577] N:  -- [wsi|0|pipe] (0) 968Î¼s
[2022/07/06 11:59:52:5577] N:  -- [vh|0|netlink] (0) 962Î¼s
2022-07-06 11:59:52 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:52 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  1

^C[2022/07/06 11:59:52:7767] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/06 11:59:52:7767] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/06 11:59:52:7769] N:  ++ [wsi|0|pipe] (1)
[2022/07/06 11:59:52:7769] N:  ++ [vh|0|netlink] (1)
[2022/07/06 11:59:52:7771] N:  ++ [vh|1|default||-1] (2)
[2022/07/06 11:59:52:7775] E: problem creating ssl context 604422254: error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
[2022/07/06 11:59:52:7776] E: lws_create_vhost: lws_context_init_client_ssl failed
[2022/07/06 11:59:52:7776] N:  -- [vh|1|default||-1] (1) 534Î¼s
[2022/07/06 11:59:52:7776] E: Failed to create default vhost
[2022/07/06 11:59:52:7777] N:  -- [wsi|0|pipe] (0) 832Î¼s
[2022/07/06 11:59:52:7778] N:  -- [vh|0|netlink] (0) 822Î¼s
2022-07-06 11:59:52 ERROR   createSignalingSync(): operation returned status code: 0x5d000014
2022-07-06 11:59:52 ERROR   createSignalingClientSync(): Create Signaling Sync API returned [0x5d000014]  0

2022-07-06 11:59:52 ERROR   createSignalingClientSync(): Create signaling client API failed with return code [0x5d000014]
[KVS Master] createSignalingClientSync(): operation returned status code: 0x5d000014 
[KVS Master] Terminated with status code 0x5d000014
[KVS Master] Cleaning up....
[KVS Master] signalingClientGetMetrics() operation returned status code: 0x00000001
2022-07-06 11:59:52 ERROR   timerQueueExecutor(): operation returned status code: 0x59000001
[KVS Master] Cleanup done_

**this is the log when i run openssl rand -hex 10:**
_3069628432:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
3069628432:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
3069628432:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
3069628432:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
3069628432:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
3069628432:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:
3069628432:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:crypto/rand/drbg_lib.c:342:
3069628432:error:2406B072:random number generator:RAND_DRBG_generate:in error state:crypto/rand/drbg_lib.c:589:_
**this openssl version is 1.1.1 as following:**
OpenSSL> version
OpenSSL 1.1.1g  21 Apr 2020
OpenSSL>_ 

any thoughts? thanks!

**Comment by hassanctech** [comment] 2022-07-18 16:16
It seems like the issue is related to the `openssl` on your platform, I see you asked the question here as well:  https://github.com/openssl/openssl/issues/5787#issuecomment-1176106233

I'm closing this issue as it isn't related to our SDK.  Please follow up on the `openssl` repo to see what's going on.  

Our CI actually runs an arm cross compile here in case you need an example for this:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.github/workflows/ci.yml#L327-L344

**Closed by hassanctech** 2022-07-18 16:16 UTC
Labels: bug, needs-triage
