### ISSUE TITLE
lws connect() error errno=113

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1413] opened 2022-02-23 05:58 UTC
Occasionally, a connect() error occurs in lws.
Is this related to the KVS server? Or is it a temporary network problem?
Can I try again on state machine?

** Logging ** 
7:38.646 Libwebsockets version: 4.0.22 v4.0.20-4-gb9cfc0c5
7:38.664 Initial logging level 4095
7:38.670 IPV6 not compiled in
7:38.673  LWS_DEF_HEADER_LEN    : 4096
7:38.674  LWS_MAX_SMP           : 1
7:38.680  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
7:38.682  HTTP2 support         : not configured
7:38.683 [KVS] Using trickleICE by default, useTurn = TRUE
7:38.685 [KVS] set log level to 1
7:38.685 [KVS] Created signaling channel 328000373
7:38.725 [KVS] KVS WebRTC initialization completed successfully
7:38.731 KVS_INF createSignalingClientSync: Creating Signaling Client Sync
7:38.747 [lws lws_plat_init:137] mem: platform fd map:   256 bytes
7:38.749 [lws lws_plat_init:138] mem: max_fds 64
7:38.754 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 21
7:38.756 KVS_VER signalingClientStateChanged: Signaling client state changed to 1 - 'New'
7:38.759 KVS_DBG stepStateMachine: State Machine - Current state: 0x0000000000000001, Next state: 0x0000000000000002
7:38.782 KVS_VER signalingClientStateChanged: Signaling client state changed to 2 - 'Get Security Credentials'
7:38.786 KVS_DBG stepStateMachine: State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000004
7:38.790 KVS_VER signalingClientStateChanged: Signaling client state changed to 3 - 'Describe Channel'
7:38.815 KVS_VER lwsCompleteSync: Perform secure synchronous call for URL: https://kinesisvideo.ap-northeast-2.amazonaws.com/describeSignalingChannel
7:38.820 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 27
7:38.826 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 85
7:38.956 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 29
7:39.147 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 24
7:39.160 KVS_DBG lwsHttpCallbackRoutine: Client append handshake header
7:39.163 KVS_VER lwsHttpCallbackRoutine: Appending header - Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20220223/ap-northeast-2/kinesisvideo/aws4_request, SignedHeaders=host;user-agent;x-amz-date, Signature=644b2b474c75d015ee0e4c28c9896db693fbab06041682b01b099f8cce594f12
7:39.184 KVS_VER lwsHttpCallbackRoutine: Appending header - content-length: 31
7:39.187 KVS_VER lwsHttpCallbackRoutine: Appending header - content-type: application/json
7:39.190 KVS_VER lwsHttpCallbackRoutine: Appending header - user-agent: AWS-SDK-KVS/3.0.0 arm-gcc iCatOS V37
7:39.257 KVS_VER lwsHttpCallbackRoutine: Appending header - X-Amz-Date: 20220223T054339Z
7:39.260 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 19
7:39.278 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 31
7:39.282 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 57
7:39.285 KVS_DBG lwsHttpCallbackRoutine: Sending the body {
7:39.287    "ChannelName": "328000373"
7:39.288 }, size 31
7:39.314 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 2
7:39.349 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 44
7:39.352 KVS_DBG lwsHttpCallbackRoutine: Connected with server response: 200
7:39.354 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 46
7:39.356 KVS_DBG lwsHttpCallbackRoutine: Received client http
7:39.359 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 48
7:39.361 KVS_DBG lwsHttpCallbackRoutine: Received client http read: 341 bytes
7:39.392 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 47
7:39.397 KVS_DBG lwsHttpCallbackRoutine: Http client completed
7:39.400 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 45
7:39.403 KVS_DBG lwsHttpCallbackRoutine: Client http closed
7:39.405 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 30
7:39.618 KVS_DBG stepStateMachine: State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000010
7:39.624 KVS_VER signalingClientStateChanged: Signaling client state changed to 5 - 'Get Channel Endpoint'
7:39.649 KVS_VER lwsCompleteSync: Perform secure synchronous call for URL: https://kinesisvideo.ap-northeast-2.amazonaws.com/getSignalingChannelEndpoint
7:39.663 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 85
7:55.304 lws_client_connect_3_connect: connect says errno: 113
7:55.321 lws_client_connect_3_connect: Connect failed: 13.209.140.207 port 443
7:55.325 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 30
7:55.331 KVS_DBG getChannelEndpoint: getChannelEndpointLws() 5d000015
7:55.346 KVS_DBG executeGetEndpointSignalingState: getChannelEndpoint() 0x5d000015
7:55.349 KVS_ERR createSignalingSync(179): operation returned status code: 0x0000000f
7:55.352 KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 28
7:55.355 [KVS] createSignalingClientSync(): operation returned status code: 0x0000000f
7:55.358 [KVS] Terminated with status code 0x0000000f
7:55.359 [KVS] Cleaning up....
7:55.360 KVS_VER signalingClientGetMetrics: Signaling Client Get Metrics
7:55.371 [KVS] signalingClientGetMetrics() operation returned status code: 0x00000001KVS_INF freeSignalingClient: Freeing Signaling Client

7:55.701 [KVS] Cleanup done

** Any design considerations/constraints **

Thanks.

**Comment by disa6302** [comment] 2022-03-03 00:31
It could be an occasional network issue. I do see a timeout occuring. There should be a retry happening. Unless, you have made any changes to the sample to not do any retries.
Which version of the SDK are you using?

**Comment by disa6302** [comment] 2022-03-09 07:32
Closing due to inactivity

**Comment by roxlu** [comment] 2022-03-09 13:24
@disa6302 I'm experiencing a similar issue that is easily reproduced with the v1.7.1 tag on Arch Linux. 

Start the sample:

```bash
./kvsWebrtcClientMasterGstSample roxlu video-only testsrc
```

When the sample is running I disable my interface using:

```bash
sudo ip link set enp5s0 down
```

Then after a couple of seconds I bring up my network again:

```bash
udo ip link set enp5s0 up
```

And you keep receiving the messages shown below and you can't open a new connection with the channel anymore. :

```bash

[KVS GStreamer Master] Using trickleICE by default
[KVS GStreamer Master] Created signaling channel roxlu
[KVS Gstreamer Master] Finished initializing GStreamer
[KVS Gstreamer Master] Streaming video only
[KVS GStreamer Master] streaming type video-only[KVS GStreamer Master] KVS WebRTC initialization completed successfully
[2022/03/09 14:13:31:8310] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/03/09 14:13:31:8310] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/03/09 14:13:31:8350] N:  ++ [wsi|0|pipe] (1)
[2022/03/09 14:13:31:8374] N:  ++ [vh|0|netlink] (1)
[2022/03/09 14:13:31:8375] N:  ++ [vh|1|default||-1] (2)
[KVS GStreamer Master] Signaling client created successfully
[2022/03/09 14:13:31:8378] N:  ++ [wsicli|0|POST/h1/kinesisvideo.eu-west-2.amazonaws.com] (1)
[2022/03/09 14:13:31:9968] N:  -- [wsicli|0|POST/h1/kinesisvideo.eu-west-2.amazonaws.com] (0) 159.033ms
[2022/03/09 14:13:31:9969] N:  ++ [wsicli|1|POST/h1/kinesisvideo.eu-west-2.amazonaws.com] (1)
[2022/03/09 14:13:32:1495] N:  -- [wsicli|1|POST/h1/kinesisvideo.eu-west-2.amazonaws.com] (0) 152.658ms
[2022/03/09 14:13:32:1497] N:  ++ [wsicli|2|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:13:32:4164] N:  -- [wsicli|2|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 266.716ms
[2022/03/09 14:13:32:4165] N:  ++ [wsicli|3|WS/h1/m-978ce4ad.kinesisvideo.eu-west-2.amazonaws.co] (1)
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel roxlu
2022-03-09 13:14:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2022-03-09 13:14:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2022-03-09 13:14:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2022-03-09 13:14:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2022-03-09 13:14:59 WARN    handleStunPacket(): Cannot find candidate pair with local candidate 2001:1c00:2404:3100:a1b4:c33a:11c5:a0a7 and remote candidate 2001:1c00:2404:3100:a1b4:c33a:11c5:a0a7. Dropping STUN binding success response
[2022/03/09 14:15:03:7371] N: rops_handle_POLLIN_netlink: DELADDR
[2022/03/09 14:15:03:7371] N: _lws_route_check_wsi: [wsicli|3|WS/h1/m-978ce4ad.kinesisvideo.eu-west-2.amazonaws.co]: dest route gone
[2022/03/09 14:15:03:7372] N:  -- [wsicli|3|WS/h1/m-978ce4ad.kinesisvideo.eu-west-2.amazonaws.co] (0) 1.522min
[2022/03/09 14:15:03:9173] N:  ++ [wsicli|4|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:03:9180] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:04:9197] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:05:9213] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:06:9215] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:07:9227] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:08:9230] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:09:9234] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:10:9244] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:11:9250] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:12:9262] N: lws_client_connect_3_connect: dns lookup failed -3
2022-03-09 13:15:13 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: Closed before conn
[2022/03/09 14:15:13:9180] N:  -- [wsicli|4|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 10.000s
2022-03-09 13:15:17 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000034
[2022/03/09 14:15:17:9183] N:  ++ [wsicli|5|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:17:9184] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:18:9192] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:19:9204] N: lws_client_connect_3_connect: dns lookup failed -3
[2022/03/09 14:15:20:9463] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:20:9463] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:20:9463] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:20:9463] N: lws_sort_dns_dump: empty
2022-03-09 13:15:20 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
[2022/03/09 14:15:20:9464] N:  -- [wsicli|5|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 3.028s
[2022/03/09 14:15:20:9464] N: lws_client_dns_retry_timeout: DNS lookup failed
2022-03-09 13:15:24 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000034
2022-03-09 13:15:24 WARN    signalingClientError(): Signaling client generated an error 0x5d000030 - 'Failed to reconnect with status code 0x0000000f.'
[2022/03/09 14:15:24:1661] N:  ++ [wsicli|6|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:24:2050] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:24:2050] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:24:2050] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:24:2050] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:24:2050] N:  -- [wsicli|6|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 38.927ms
2022-03-09 13:15:24 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:15:24:2050] N:  ++ [wsicli|7|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:24:2306] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:15:24:2306] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:15:24:2306] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:15:24:2306] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:24:2306] N:  -- [wsicli|7|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 25.591ms
2022-03-09 13:15:24 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:15:24 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:15:24 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  7

[2022/03/09 14:15:25:8996] N:  ++ [wsicli|8|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:25:9210] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:25:9210] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:25:9210] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:25:9210] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:25:9211] N:  -- [wsicli|8|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 21.420ms
2022-03-09 13:15:25 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:15:25:9211] N:  ++ [wsicli|9|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:25:9460] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:25:9460] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:25:9460] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:25:9461] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:25:9461] N:  -- [wsicli|9|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 24.969ms
2022-03-09 13:15:25 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:15:25 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:15:25 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  6

[2022/03/09 14:15:28:2717] N:  ++ [wsicli|a|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:28:2929] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:15:28:2929] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:15:28:2929] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:15:28:2929] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:28:2929] N:  -- [wsicli|a|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 21.271ms
2022-03-09 13:15:28 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:15:28:2930] N:  ++ [wsicli|b|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:28:3105] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:15:28:3105] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:15:28:3105] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:15:28:3105] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:28:3106] N:  -- [wsicli|b|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 17.574ms
2022-03-09 13:15:28 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:15:28 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:15:28 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  5

[2022/03/09 14:15:32:4778] N:  ++ [wsicli|c|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:32:5034] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:15:32:5034] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:15:32:5034] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:15:32:5034] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:32:5034] N:  -- [wsicli|c|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 25.654ms
2022-03-09 13:15:32 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:15:32:5035] N:  ++ [wsicli|d|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:32:5425] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:32:5425] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:32:5425] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:32:5425] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:32:5425] N:  -- [wsicli|d|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 39.078ms
2022-03-09 13:15:32 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:15:32 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:15:32 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  4

[2022/03/09 14:15:40:8698] N:  ++ [wsicli|e|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:40:8959] N: lws_sort_dns: 18.135.212.14 has no route out
[2022/03/09 14:15:40:8959] N: lws_sort_dns: 3.11.40.34 has no route out
[2022/03/09 14:15:40:8959] N: lws_sort_dns: 18.132.158.30 has no route out
[2022/03/09 14:15:40:8959] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:40:8959] N:  -- [wsicli|e|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 26.169ms
2022-03-09 13:15:40 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:15:40:8960] N:  ++ [wsicli|f|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (1)
[2022/03/09 14:15:40:9195] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:15:40:9195] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:15:40:9195] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:15:40:9195] N: lws_sort_dns_dump: empty
[2022/03/09 14:15:40:9195] N:  -- [wsicli|f|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws.] (0) 23.505ms
2022-03-09 13:15:40 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:15:40 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:15:40 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  3

[2022/03/09 14:16:01:3200] N:  ++ [wsicli|10|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (1)
[2022/03/09 14:16:01:3389] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:16:01:3389] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:16:01:3390] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:16:01:3390] N: lws_sort_dns_dump: empty
[2022/03/09 14:16:01:3390] N:  -- [wsicli|10|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (0) 18.972ms
2022-03-09 13:16:01 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:16:01:3390] N:  ++ [wsicli|11|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (1)
[2022/03/09 14:16:01:3632] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:16:01:3632] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:16:01:3632] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:16:01:3632] N: lws_sort_dns_dump: empty
[2022/03/09 14:16:01:3632] N:  -- [wsicli|11|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (0) 24.180ms
2022-03-09 13:16:01 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:16:01 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:16:01 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  2

[2022/03/09 14:16:22:1501] N:  ++ [wsicli|12|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (1)
[2022/03/09 14:16:22:1735] N: lws_sort_dns: 3.9.32.85 has no route out
[2022/03/09 14:16:22:1735] N: lws_sort_dns: 18.133.18.180 has no route out
[2022/03/09 14:16:22:1735] N: lws_sort_dns: 35.179.98.11 has no route out
[2022/03/09 14:16:22:1735] N: lws_sort_dns_dump: empty
[2022/03/09 14:16:22:1735] N:  -- [wsicli|12|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (0) 23.426ms
2022-03-09 13:16:22 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
[2022/03/09 14:16:22:1736] N:  ++ [wsicli|13|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (1)
[2022/03/09 14:16:22:2098] N: lws_sort_dns: 35.179.7.193 has no route out
[2022/03/09 14:16:22:2098] N: lws_sort_dns: 18.171.0.4 has no route out
[2022/03/09 14:16:22:2098] N: lws_sort_dns: 18.135.169.155 has no route out
[2022/03/09 14:16:22:2098] N: lws_sort_dns_dump: empty
[2022/03/09 14:16:22:2099] N:  -- [wsicli|13|POST/h1/r-d29a6cb3.kinesisvideo.eu-west-2.amazonaws] (0) 36.270ms
2022-03-09 13:16:22 ERROR   getIceConfigLws(): Call Failed with Status:  0x5d000015
2022-03-09 13:16:22 ERROR   signalingFetchSync(): operation returned status code: 0x5d000006
2022-03-09 13:16:22 ERROR   signalingClientFetchSync(): Create Signaling Sync API returned [0x5d000006]  1
```

**Comment by worldwideward** [comment] 2022-03-10 15:54
Can someone reopen this issue, it does not seem to be solved yet?

**Comment by jdelapla** [comment] 2022-05-18 19:34
Resolved with linked PR

**Closed by jdelapla** 2022-05-18 19:34 UTC
Labels: pending-response
