### ISSUE TITLE
[BUG] Possible memory leak when viewer has no videos

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#914] opened 2020-11-02 03:43 UTC
**Logging**
[11-02-11-1080P-COM4.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5472601/11-02-11-1080P-COM4.log)

**Describe the bug**
In my chrome brower, I have to close and reopen the page every time I start the viewer. If I don't close the page and start viewer, there is no videos, ss shown in Figure 1. And when the program exits it will print a memory leak. The memory can be 12060, 24120, 36180, integer multiples of 12060, like a size of a structure.

**Screenshots**
Figure 1
![image](https://user-images.githubusercontent.com/20633988/97826772-79c21c00-1cfd-11eb-9680-5877f6db32c4.png)

**Comment by hassanctech** [comment] 2020-11-02 15:13
This is the same issue as:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/904

We are investigating this, in the mean time if you use the JS sample page:  https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

You should be able to play/stop as many times as you want without issue.

**Comment by MushMal** [comment] 2020-11-02 20:43
I am not sure I understand the scenario. Here is what I am trying.

* Using the latest master sample.
* Using Google Chrome in the browser hosting https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
* Start the master app (under the debugger or without)
* Start the viewer (works fine)
* Stop the viewer by clicking stop button and start it again clicking start (works fine)
* Refresh the page and click start (works fine)

How can I reproduce this issue?

The logs you've attached have an odd STATUS_NULL_ARG in the signaling message callback. This shouldn't be the case with the stock master sample.

**Comment by hassanctech** [comment] 2020-11-02 20:56
Right there's no issue in the JS page, it's in the KVS console, if you go to the signaling channel and try to play it'll work the first time, if you pause and try to play again you'll see this behavior, specially I see it with the gstreamer master sample, not with the non-gstreamer.

**Comment by Nomidia** [comment] 2020-11-03 02:39
Correct, I am using kvsWebRTCClientMaster and view from kvs.

![image](https://user-images.githubusercontent.com/20633988/97944864-cc184100-1dc0-11eb-9854-680d8ad46278.png)

**Comment by Nomidia** [comment] 2020-11-03 02:52
Reproduce steps
- Using kvsWebRTCClientMaster 
- Using aws kvs Signaling channels
- Playback viewer
- Stop viewer
- Reconnect viewer
- Refresh the kvs page
- Quit the program

**Comment by MushMal** [comment] 2020-11-03 02:55
Easy enough. Will be looking at it shortly

**Comment by MushMal** [comment] 2020-11-03 04:49
Can't reproduce this with #916 @Nomidia could you PLEASE give the change a try and let me know whether I am doing something wrong.

I do what you've described with multiple different types of permutations. On the KVS master sample side I simply hit Ctrl+C to exit the app. If there is a mem leak I would have hit that. 

Please try the fix and see if this is the root cause (which it is likely to be).

**Comment by Nomidia** [comment] 2020-11-03 06:17
After merging your pr, this problem still exists. In my chrome brower, after stopping and restarting viewer, there is no videos unless I close the page. I think this phenomenon must exist to reproduce this problem.

**Comment by MushMal** [comment] 2020-11-03 06:19
Are we talking about the leak or no video - this issue should be focused only on the leak/race. Can you confirm what you are seeing? In my latest chrome on mac I can't reproduce the blank screen.

Regardless, can we try to get to the bottom of the leaks/etc? I would like to see verbose logs or something as I am unable to reproduce this issue.

**Comment by Nomidia** [comment] 2020-11-03 06:34
Sorry, I thought memory leaks will only appear after there were no videos. In fact, memory leak occurs after several connections.
They should be two separate issues. Here is verbose log.

[11-03-14-1080P-COM4.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5479563/11-03-14-1080P-COM4.log)

**Comment by MushMal** [comment] 2020-11-03 06:46
This is really odd, I am just unable to reproduce the memory leak issue at all. With or without VPN, etc.. Can you check if you are going through TURN or P2P? Which region are you using? I am unable to repro the mem leak nor the blank screen. Just works fine even if I refresh or stop multiple times.

**Comment by MushMal** [comment] 2020-11-03 06:50
Just saw the attached lot. It seems you are in ap-south-1 and you are using turn. I am still unsure how to reproduce this and without the repro or any leads I am having a hard time understanding what's going on. Let me know if there is anything that comes to your mind to help reproducing it.

**Comment by Nomidia** [comment] 2020-11-03 06:57
Ok, I will continue to pay attention to this issue.

**Comment by MushMal** [comment] 2020-11-03 07:12
Thanks. I just added TURN enforcement and I still can't reproduce this. I even make the packets drop with with nacks but still no luck reproducing it. I highly recommend cleaning up your workspace, compiling the changes I pushed and see if you can reproduce it. Please include the info on region, scenario, etc... anything that will help us reproduce it. The difficulty is that if we can't reproduce a memory leak we won't be able to remotely instrument your build - you might need to do it on your own.

**Comment by Nomidia** [comment] 2020-11-03 07:27
My location is China, the signaling channel is Mumbai. My device is armv7 and 4-byte aligned.
I am not using wertc's CMakelists.txt, it is an old cmake file from kvswebrtc, and I also add Kinesis video stream producer and aws s3 together.
Since my device crashed something, I try to update to the lasted version. There was no such problem before the update, because I have used it for several months.

**Comment by MushMal** [comment] 2020-11-04 19:43
Any update? As of today, after spending considerable amount of time, we are unable to reproduce. I will be trying the GStreamer sample instead of the stock master but that would be a different issue than what's reported. If we won't hear back soon we will be closing this issue.

**Comment by MushMal** [comment] 2020-11-04 19:50
Also confirming that I can not reproduce this with the GStreamer sample. Awaiting for repro as otherwise we see no actionable items

**Comment by Nomidia** [comment] 2020-11-05 06:11
I am working on other things recently, I will come back to this issue again when I have time.

**Comment by MushMal** [comment] 2020-11-05 06:15
Thanks. Resolving for now. Please cut a separate issue with detailed information and verbose logs.

**Closed by MushMal** 2020-11-05 06:15 UTC
Labels: bug
