### ISSUE TITLE
[BUG] 71e1deb7ffcff6d1839a7698b15b68bad9153a8a does not support firefox v80.0+

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#811] opened 2020-09-20 05:26 UTC
**Describe the bug**
We are trying to figure out why firefox stopped decoding, we tried to go as far back as early as possible when we recalled that firefox can decode, so far no luck.
So far we think it's not because of SDK changes, but most likely due to firefox's side of changes. 

**SDK version number**
71e1deb7ffcff6d1839a7698b15b68bad9153a8a

**To Reproduce**
- Build 71e1deb7ffcff6d1839a7698b15b68bad9153a8a on Mac.
- Run Gst Example or Master Example.
- Can render on Mac/Windows Chrome
- Can NOT render video on Firefox Version 80.0.1 (64-bit) Windows, can play sound
- Can NOT render video on Firrefox Version 80.0 Mac, can play sound 

**Expected behavior**
Firefox can decode things coming out of SDK

**Comment by hassanctech** [comment] 2020-09-22 17:33
I'm looking in the release notes for the Mac Firefox 80.0 release it looks like a bug was introduced in 80.0 but fixed in 81.0, can you please try the latest (81.0) ?

**Comment by hassanctech** [comment] 2020-09-22 17:45
Ok I can confirm that it worked on Firefox v79.0 but does not work on v80.0, v81.0 or v82.0b1 -- I will look into this.

**Comment by hassanctech** [comment] 2020-09-22 17:48
I see this in their release notes for 80.0

Firefox now supports RTX and Transport-cc for improved call quality in poor network conditions and better bandwidth estimation. These features also provide better compatibility with many websites using WebRTC. (https://www.mozilla.org/en-US/firefox/80.0/releasenotes/)

**Comment by hassanctech** [comment] 2020-09-22 18:28
Ok so I see an issue, running the stock master sample and the js test page in Firefox I see the following m-line in the offer produced by Firefox:

`m=video 60149 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98`

However the answer the C SDK produces is:

`m=video 9 UDP/TLS/RTP/SAVPF 0`

We were expecting a '9' after video, I'll dig deeper into the spec and see if this is something we need to support or where the issue is.  Given this offer/answer pair it's expected that video would not be sent, so I'm going to look into this.

**Comment by hassanctech** [comment] 2020-09-22 18:29
For example here is a video m-line produced by Firefox in v79.0

`m=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97`

**Comment by hassanctech** [comment] 2020-10-06 17:32
Wanted to provide an update here so our parsing logic has a bug which assumes a particular order for MIME subtype (rts) and the payload-format-specific parameter "apt" -- which works for Chrome/Safari but the order is different in FF.  I am working on the fix for this.

**Closed** 2020-10-08 18:20 UTC
Labels: bug
