### ISSUE TITLE
Streaming fails with error STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT 0x5d00002b

### ISSUE THREAD

**Issue by sbarry157** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#848] opened 2020-10-06 19:54 UTC
**Describe the bug**
Streaming attempts occasionally fail using the viewer test page with STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT 0x5d00002b. We originally found this issue in our web app viewer, and are able to reproduce it in the test page.

**SDK version number**
commit 35fc3ea5 (oct 1)

**To Reproduce**
using the [test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html), start a viewer session with these settings:
- trickle ice on
- clientId unset (to ensure it creates a unique session id each time
- tracks: send video only
- 1280x720
- STUN/TURN
- region: us-west-2

Most of the time things work properly and streaming succeeds. But occasionally, streaming fails with logs like this:
```10-06 15:04:00.427: [I]2020-10-06 19:03:59 ERROR   signalingSendMessageSync(): operation returned status code: 0x5d00002b
10-06 15:04:00.427: [I]2020-10-06 19:03:59 ERROR   respondWithAnswer(): operation returned status code: 0x5d00002b
10-06 15:04:00.427: [I]2020-10-06 19:03:59 ERROR   handleOffer(): operation returned status code: 0x5d00002b
10-06 15:04:00.427: [I]2020-10-06 19:03:59 ERROR   signalingMessageReceived(): operation returned status code: 0x5d00002b
10-06 15:04:00.427: [I]2020-10-06 19:03:59 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x5d00002b
10-06 15:04:00.427: [I]2020-10-06 19:03:59 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 71
10-06 15:04:00.428: [I]2020-10-06 19:03:59 DEBUG   lwsWssCallbackRoutine(): Client is writable
10-06 15:04:00.428: [I]2020-10-06 19:03:59 ERROR   signalingMessageReceived(): operation returned status code: 0x00000001
10-06 15:04:00.428: [I]2020-10-06 19:03:59 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x00000001
10-06 15:04:00.428: [I]2020-10-06 19:03:59 ERROR   signalingMessageReceived(): operation returned status code: 0x00000001
10-06 15:04:00.428: [I]2020-10-06 19:03:59 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x00000001
10-06 15:04:00.428: [I]2020-10-06 19:03:59 ERROR   signalingMessageReceived(): operation returned status code: 0x00000001
10-06 15:04:01.062: [I]2020-10-06 19:03:59 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x00000001
10-06 15:04:01.062: [I]2020-10-06 19:03:59 ERROR   signalingMessageReceived(): operation returned status code: 0x00000001
10-06 15:04:01.062: [I]2020-10-06 19:03:59 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x00000001
```
[STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT_2.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5336323/STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT_2.log)

here are the logs from the test page viewer:
```
[2020-10-06T19:03:55.698Z] [INFO] [VIEWER] Starting viewer connection
[2020-10-06T19:03:56.243Z] [INFO] [VIEWER] Connected to signaling service
[2020-10-06T19:03:56.781Z] [INFO] [VIEWER] Creating SDP offer
[2020-10-06T19:03:56.789Z] [INFO] [VIEWER] Sending SDP offer
[2020-10-06T19:03:56.789Z] [INFO] [VIEWER] Generating ICE candidates
[2020-10-06T19:03:56.790Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.790Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.790Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.790Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.790Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.791Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.891Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.891Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.892Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.893Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.893Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:56.893Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:56.893Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.012Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.012Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.013Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.013Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.080Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.080Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.080Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.080Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.088Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.088Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.096Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.096Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.459Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.459Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.459Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.460Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.460Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.460Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.460Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.460Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.478Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:03:57.481Z] [INFO] [VIEWER] Generated ICE candidate
[2020-10-06T19:03:57.482Z] [INFO] [VIEWER] Sending ICE candidate
[2020-10-06T19:04:36.689Z] [INFO] [VIEWER] All ICE candidates have been generated
[2020-10-06T19:14:02.097Z] [INFO] [VIEWER] Disconnected from signaling channel```

**Comment by sbarry157** [comment] 2020-10-06 20:01
I should also mention that we haven't been able to reproduce this issue using our mobile app or alexa. We've only seen this issue using the test page and our web app, both using chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by MushMal** [comment] 2020-10-07 06:06
Are you seeing other clients attempting to connect to the master? There is a known issue with attempting to send a second message on a separate thread while a message sending is in progress. This could happen, for example, when the trickle ice which is driven by the timer queue is sending the ice candidate while the sample is responding to the offer.

We really need to handle this properly - have a work item: Issue #175

**Comment by sbarry157** [comment] 2020-10-07 16:12
@MushMal there are no other clients attempting to connect to master. It's only one client, and I wait until master's logs show that a session has stopped before starting a new one.

**Comment by MushMal** [comment] 2020-10-07 19:35
I don't see any codepath in the code that could lead to this issue in that case. Which commit are you using? Could you try a more recent commit?

**Comment by MushMal** [comment] 2020-10-07 19:36
For now, I am removing the label bug as it could simply be a networking/ICE negotiation issue.

In earlier commits we had a benign message being output with duplicate message.

**Comment by sbarry157** [comment] 2020-10-07 19:59
@MushMal we are using commit 35fc3ea. We will update to the latest and retest.

**Comment by chenek** [comment] 2020-10-08 00:37
@MushMal We don’t see any commit that is related to fixing this issue. Are you sure the latest commit would fix this issue? Can you point out which commit is related to this problem?

**Comment by MushMal** [comment] 2020-10-08 01:36
The commit that's specified is after the changes that I had in mind. It's not yet immediately clear to me what could be wrong and I am yet unable to reproduce this issue. Let me spend a little more time on this and I will get back to you. I might ask you to modify some code in the sample to  try to reproduce.

Again, my assumption is that you are working on a stock master sample with absolutely no modifications. I need to know this as I don't want to be wasting time chasing something that we know that fundamentally we might have an issue with - as I commented and included a work item that we need to fix for completeness. So, please confirm that this is reproduced with stock master on the commit https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/35fc3ea5f2132613a8439da41fdfc1b5c052c858

**Comment by MushMal** [comment] 2020-10-08 03:31
I have streamlined (serialized) access to the signaling client sending just in case it's ended up in a non-serial manner. Please give this a try.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/852

I still could not reproduce the scenario you were describing.

**Comment by MushMal** [comment] 2020-10-08 19:17
Resolving for now

**Closed by MushMal** 2020-10-08 19:17 UTC
Labels: Networking

**Comment by ycyang1229** [comment] 2020-10-13 08:13
@MushMal This one(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/852) is what I need for this issue(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/804). My explanation for my situation is that the interval between sending answer and sending local ice candidate is very close and using one single core to run this sdk. In my network, the device sent the first local ice candidate before sending answer. If the process of sending first local ice candidate is not finished, sending answer may be dropped. Context switch may happen at this line(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L1428). From the log @sbarry157 provided, it looks likes similar as my situation. Not sure the explanation is correct or not. Please correct me if I am wrong. Thanks for this pr again, and I can remove my patch in my codebase now.

**Comment by MushMal** [comment] 2020-10-13 08:20
Yeah, indeed that could happen. #852 serializing the sending allows it to not fail during the check for sending a message which could result in not being able to negotiate the appropriate ICE candidate. These are the timing issues which are super hard to hit using the static code analysis tools. Not even some of our lab devices like RPi. Thanks for being relentless in identifying these issues.
