### ISSUE TITLE
[BUG] createSignalingClientSync function takes too long to finish

### ISSUE THREAD

**Issue by nguyenduynghia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1188] opened 2021-07-09 14:25 UTC
I create one WebRTC Channel as master.
However, it takes 12 seconds to complete this function.
Please see the log file:
[2021-07-09 17:01:04]-INFO-createSignalingClientSync(): Creating Signaling Client Sync
......
[2021-07-09 17:01:16]-DEBUG-lwsWssCallbackRoutine(): Client is writable
[createWebRTCChannel.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6792034/createWebRTCChannel.log)

**Comment by juno52wendy** [comment] 2021-07-13 09:54
This is because the signaling server you set is too far away, and your own VPN or the country has overturned the fence, the delay is very long, and it is easy to fail

**Comment by nguyenduynghia** [comment] 2021-07-14 01:46
Do you mean I need to choose region which is the nearest my country?

**Comment by juno52wendy** [comment] 2021-07-14 06:51
Yes, the region is the closest to your country. It is best if your country has an AWS signaling server deployment. This is the best, otherwise the problem is basically unsolvable

**Comment by disa6302** [comment] 2021-07-27 18:48
@nguyenduynghia , 

You always need to choose a region closest to yours to get optimal performance. Closing this issue now. Feel free to reach out if you have any more questions.

**Closed by disa6302** 2021-07-27 18:48 UTC
Labels: bug
