### ISSUE TITLE
[BUG] signaling messages don't reach to the kvsWebrtcClientMaster after a long period of idling

### ISSUE THREAD

**Issue by yuma-m** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#562] opened 2020-06-23 09:53 UTC
**Describe the bug**

I use `kvsWebrtcClientMaster` and JavaScript SDK sample page to establish connection. When the viewer is started soon after the master is launched, signaling messages reach to `kvsWebrtcClientMaster`. However, a long time (> 1hour) is passed after it launches and if viewer send signaling messages, no signaling messages are reached to the master. I confirmed that signaling messages were sent on the channel from the CloudWatch metrics on the management console.

**SDK version number**
v1.2.0

**Open source building**
N/A

**To Reproduce**

1. Launch kvsWebrtcClientMaster
2. Wait an hour or more.
3. Start the viewer
4. No debug messages (e.g. `New remote ice candidate discovered` or `handleOffer(): time taken to send answer 3 ms`) is displayed on the console where master is running. "IceServerList" JSON log is displayed every 4.5 minutes.
5. There was signaling messages count at that time on the CloudWatch metrics.

I also confirmed that even after the step 4~5 is reproduced, waiting a few more hours and attempt the signaling from the viewer, the master sometimes receives signaling messages.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOSX 10.14
 - Browser: Chrome
 - Version: 83.0.4103.106

Both the kvsWebrtcClientMaster and the viewer is running on the Mac above.

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by MushMal** [comment] 2020-06-23 15:09
@yuma-m this scenario is supported and should work as expected. I am suspecting that there is a problem with dropped connection or something similar if you succeed some times.

To get this debugged further, can you please capture the debug logs from the master sample so we can see what's happened after an hour?

**Comment by yuma-m** [comment] 2020-06-24 13:50
> This scenario is supported and should work as expected.

Do you mean the master should receive signaling messages even after an hour from the launch?

I attached the logs of the master and the viewer. The time line is below.

[20200624_master.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4825738/20200624_master.log)
[20200624_viewer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4825740/20200624_viewer.log)

12:23:20 Launch master
13:39:00 Start Viewer (1st trial)
13:39:40 Start Viewer (2nd trial)
13:41:06 Start Viewer (3rd trial)

No logs like receiving signaling messages are shown on the master log.

**Comment by MushMal** [comment] 2020-06-24 19:30
@yuma-m the embedded signaling client sends pong messages to keep the connection alive for max duration the backend allows. The connection could get interrupted for multiple other reasons - for example networking problems. The signaling client should re-connect when detecting disconnect.

Looking at the master logs, I don't see any disconnect events. Nor, do I see any messages that are received.

Can I ask you to email your account ID to kinesis-video-support@amazon.com with more details on the channel name (I see the log is using demo-channel name) and the time of connect - I can assume it's around 2020-06-24 13:39:00 from the logs (what timezone is this in)

**Comment by MushMal** [comment] 2020-06-25 03:10
To provide an update... Thanks @yuma-m for the information. We are investigating this issue and will provide mitigation shortly. We are able to reproduce this.

**Comment by yuma-m** [comment] 2020-06-25 12:54
@MushMal Thank you for your update. Waiting for the good news.

**Comment by bdhandap** [comment] 2020-07-08 21:14
@yuma-m The fix has been deployed to eu-central-1 and other regions will be deployed shortly. Can you please check in eu-central-1 and confirm?

**Comment by yuma-m** [comment] 2020-07-09 11:21
@bdhandap I tried several times on eu-central-1 region and confirmed the issue didn't reproduce. Thank you for your fix.

**Comment by disa6302** [comment] 2020-07-13 17:54
@yuma-m , 

Looks like it worked. Based on your comment, I am closing this issue. Do feel free to reach out if you face any issues in the future. Thank you!

**Closed by disa6302** 2020-07-13 17:54 UTC
Labels: Signaling backend, bug, regression

**Comment by coldheartday** [comment] 2020-07-14 09:48
@bdhandap Did this fix deployed to us-west-2 ?I still meet issue [https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/493](url)

**Comment by bdhandap** [comment] 2020-07-15 17:26
@coldheartday Yes. the changes are deployed to us-west-2 on Monday. can you try again?

**Comment by SEOKHYOENCHOI** [comment] 2020-07-17 04:02
@bdhandap  Did this fix deployed to ap-northeast-2?

**Comment by bdhandap** [comment] 2020-07-30 17:13
@SEOKHYOENCHOI Yes it is deployed to ap-northeast-2
