### ISSUE TITLE
[QUESTION] Could you add a tested Master example with TURN fully disabled?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#746] opened 2020-08-25 19:37 UTC
I'm having lots of trouble ensuring that my users will never use TURN.
When I disable TURN in the Master example, the client starts failing a lot, even when I'm testing in the same network, with the camera connected to the PC in the same router.
What is needed to make everything go wrong is just making "useTurn" FALSE:
[createSampleConfiguration](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/abbdc60d1cc9788cc65f85d71efd25fb8f104064/samples/kvsWebRTCClientMaster.c#L22)
Our use case require our users to never enable a firewall or any Symmetric NAT that could cause a failure in STUN / ICE. We would like to provide low cost connections to all our customers and letting them use TURN would make our business model crash miserably.
We will be happy Kinesis users if we could rely on just direct P2P connections.

**Comment by MushMal** [comment] 2020-08-25 23:43
@fernandoc1 the reason why we have TURN in the first place is due to the fact that in 20% cases the P2P is not possible to establish due to NAT issues or firewall. The TravisCI runs operate in the default mode where the ICE attempts to resolve as fast as possible and doesn't give any preferences to P2P vs TURN. 

In your application, you could disable TURN. However, as you see, your network doesn't allow P2P ICE candidate pairing. 

You could dive deeper and dump out the logs to understand why the connection doesn't succeed - there could be numerous reasons.

**Comment by suggestedfixes** [comment] 2020-08-26 06:49
@fernandoc1 Alternatively, you can host your own turn server, or have your clients host a turn server. Turn servers themselves have to follow RFC specs, so it does not have to be an amazon one.

**Comment by fernandoc1** [comment] 2020-08-26 10:59
@MushMal, it is not reasonable to believe that our network is unable to create P2P ICE candidate pairing. We have a high success rate here when trying. However, the Master application sometimes randomly fails and we don't understand. We are using ordinary consumer network that is capable of using all sorts of P2P applications. So why Kinesis is having trouble?
In addition to what I'm saying, Kinesis is failing to create P2P connection when both devices are in the same network, connected by a cable in the same device. There should be something very strange, because the unique thing that is required to create a connection is to exchange the local IP between the peers.
@suggestedfixes hosting a TURN server is not reasonable in our case, because we would need have additional cost that are not within our business expectation. In our case we can even force our customers to change their ISP if needed. Ordinary internet connection from multiple companies here in Brazil, are capable of direct P2P.
We have another P2P technology in our camera, that always succeed and is very reliable. We are trying to use Kinesis, just because of it's WebRTC support, which is, in our evaluation, the best approach for serving video to our customers.

**Comment by MushMal** [comment] 2020-08-26 17:50
@fernandoc1 we understand the frustration and this is why we are trying to help you debug your network topology. Can we ask you to try the latest commit instead of the release as a few changes went in that might be related.

Capture the verbose logs and attach it here so we can see what the culprit can be.

Also, try to capture the output from https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1734


There are multiple reasons why P2P can't be established, not limited to the video capability exchange.

**Comment by fernandoc1** [comment] 2020-08-26 19:53
@MushMal, thank you for your attention.
I'm using the latest code from the repository ()
I have made just some changes o the master example in order to allow streaming our shared memory source and disabled the TURN.
Here is the code with the changes:
[master.c](https://gist.github.com/fernandoc1/f534064d43094fde5140ec749649be34#file-master-c-L160)

Here is the output of the discoverNatBehavior, running in our camera:
<pre>
Using stun host: stun:stun.sipgate.net:3478, local network interface (null).
2020-08-26 19:13:28 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-26 19:13:28 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
2020-08-26 19:13:28 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
2020-08-26 19:13:28 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test II. Send binding request to alternate address but primary port
2020-08-26 19:13:29 DEBUG   socketConnectionClosed(): Close socket 5
2020-08-26 19:13:30 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-26 19:13:30 DEBUG   discoverNatBehavior(): Start NAT filtering behavior test.
2020-08-26 19:13:30 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test I. Send binding request
2020-08-26 19:13:31 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test II. Send binding request with change ip and change port flag
2020-08-26 19:13:33 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test III. Send binding request with change port flag
2020-08-26 19:13:36 DEBUG   socketConnectionClosed(): Close socket 5
Detected NAT mapping behavior ENDPOINT_INDEPENDENT
Host's NAT uses same public IP address regardless of destination address. STUN is usable.
Detected NAT filtering behavior PORT_DEPENDENT
Host's NAT allows to receive UDP packet from external address and port that host had previously sent data to. STUN is usable.
</pre>

It is failing with the following messages when I try to access from some networks:

<pre>
2020-08-26 19:49:50 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-08-26 19:49:50 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client receive 
2020-08-26 19:49:51 WARN    receiveLwsMessage(): Signaling received an empty message
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client receive 
2020-08-26 19:49:51 WARN    receiveLwsMessage(): Signaling received an empty message
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client receive 
2020-08-26 19:49:51 WARN    receiveLwsMessage(): Signaling received an empty message
2020-08-26 19:49:51 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-08-26 19:49:58 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000040
2020-08-26 19:49:58 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
2020-08-26 19:49:58 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.
2020-08-26 19:49:58 INFO    onConnectionStateChange(): New connection state 5
2020-08-26 19:49:58 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: 4YUBFQZGEJX 
</pre>

I'm preparing a more verbose execution to share with you.

**Comment by chehefen** [comment] 2020-08-26 23:20
just wanna double check, do you have any firewall running on your machine? We did see people having trouble with p2p connection when their windows firewall is on.

**Comment by chehefen** [comment] 2020-08-26 23:38
Success
2020-08-26 19:59:30 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: 99mRh6kkb. Ip: 168.195.101.231:26667. Type: host. Protocol: UDP.
2020-08-26 19:59:30 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: P67zLoSy4. Ip: 168.195.101.231:26570. Type: host. Protocol: UDP.
2020-08-26 19:59:30 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: DaEcU5ilx. Ip: 192.168.18.57:56647. Type: prflx. Protocol: UDP.

Fail
2020-08-26 20:00:32 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: 9TqiiIPCg. Ip: 168.195.102.118:32145. Type: host. Protocol: UDP.
2020-08-26 20:00:32 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: JbfHaFVuS. Ip: 168.195.102.118:32740. Type: host. Protocol: UDP.

Fail
2020-08-26 20:02:12 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: IA4L5y0j6. Ip: 168.195.102.118:33027. Type: host. Protocol: UDP.
2020-08-26 20:02:12 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: y9vu9c+CG. Ip: 168.195.102.118:32175. Type: host. Protocol: UDP.

From the log, it seems that p2p works when remote candidate 192.168.18.57 is able to come through. Can you double check your NAT setup? You also need to run discoverNatBehavior on both the master and viewer to know whether p2p is possible or not.

**Comment by fernandoc1** [comment] 2020-08-27 20:37
I have created another test:
The camera (armv7l GNU/Linux) is in the office remote network with IPv4/IPv6 capabilities; My computer (Ubuntu x86_64 GNU/Linux) is in my home network with IPv4/IPv6.

Here is the output for the camera discoverNatBehavior
<pre>
Usage: ./discoverNatBehavior -i network-interface-name -s stun-hostname
Using stun host: stun:stun.sipgate.net:3478, local network interface (null).
2020-08-27 20:22:47 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-27 20:22:47 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
2020-08-27 20:22:47 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
2020-08-27 20:22:47 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test II. Send binding request to alternate address but primary port
2020-08-27 20:22:47 DEBUG   socketConnectionClosed(): Close socket 7
2020-08-27 20:22:48 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-27 20:22:48 DEBUG   discoverNatBehavior(): Start NAT filtering behavior test.
2020-08-27 20:22:48 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test I. Send binding request
2020-08-27 20:22:49 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test II. Send binding request with change ip and change port flag
2020-08-27 20:22:52 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test III. Send binding request with change port flag
2020-08-27 20:22:54 DEBUG   socketConnectionClosed(): Close socket 7
Detected NAT mapping behavior ENDPOINT_INDEPENDENT
Host's NAT uses same public IP address regardless of destination address. STUN is usable.
Detected NAT filtering behavior PORT_DEPENDENT
Host's NAT allows to receive UDP packet from external address and port that host had previously sent data to. STUN is usable.
</pre>

Here is the output for my computer discoverNatBehavior
<pre>
Using stun host: stun:stun.sipgate.net:3478, local network interface (null).
2020-08-27 20:28:05 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-27 20:28:05 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
2020-08-27 20:28:05 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
2020-08-27 20:28:05 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test II. Send binding request to alternate address but primary port
2020-08-27 20:28:05 DEBUG   socketConnectionClosed(): Close socket 5
2020-08-27 20:28:06 DEBUG   createSocket(): setsockopt() failed with errno Protocol not available
2020-08-27 20:28:06 DEBUG   discoverNatBehavior(): Start NAT filtering behavior test.
2020-08-27 20:28:06 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test I. Send binding request
2020-08-27 20:28:07 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test II. Send binding request with change ip and change port flag
2020-08-27 20:28:10 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test III. Send binding request with change port flag
2020-08-27 20:28:12 DEBUG   socketConnectionClosed(): Close socket 5
Detected NAT mapping behavior ENDPOINT_INDEPENDENT
Host's NAT uses same public IP address regardless of destination address. STUN is usable.
Detected NAT filtering behavior PORT_DEPENDENT
Host's NAT allows to receive UDP packet from external address and port that host had previously sent data to. STUN is usable.
</pre>

While both networks have IPv6 and are without an active firewall, I'm experiencing failures. I have attached log
[KINESIS_LOG.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5138701/KINESIS_LOG.txt)

**Comment by MushMal** [comment] 2020-11-08 05:57
I am going to close this issue as it seems very vague. I don't think this is an enhancement issue as the samples are designed to showcase the TURN capability so we can't remove the TURN capability.

If this is an issue with your network topology, please cut a separate ticket with detailed trace information and logs including what the observed vs expected behavior should be. In general, tracking network topology issues are super hard for us to the customers with and the reason there is TURN in the first place is because in certain topologies it's not possible to punch a hole for P2P.

**Closed by MushMal** 2020-11-08 05:57 UTC
Labels: backlog, enhancement, question
