### ISSUE TITLE
[Bug]: Run kvsWebrtcClientMaster and see that /proc/{pid}/VMRss keeps growing

### ISSUE THREAD

**Issue by remainfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1893] opened 2024-01-03 06:55 UTC
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

1、run `kvsWebrtcClientMaster`, using `https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html`, Multiple times with the viewer, view /proc/{pid}/VMRss has been growing
2、By viewing `/proc/{pid}/status`, it is found that the increase of vmrss is mainly caused by the increase of RssAnon
3、 VmRSS will not be reduced, in some small memory embedded devices insufficient memory, there will be OOM problems
4、KVS webrtc, branch: master, git commit: 0ae9ec6b80deff9df724555927fb6595a23054f1

### Expected Behavior

1、run `kvsWebrtcClientMaster`, using `https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html`, Multiple times with the viewer, view /proc/{pid}/VMRss has been growing
2、By viewing `/proc/{pid}/status`, it is found that the increase of vmrss is mainly caused by the increase of RssAnon
3、 VmRSS will not be reduced, in some small memory embedded devices insufficient memory, there will be OOM problems

### Current Behavior

1、run `kvsWebrtcClientMaster`, using `https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html`, Multiple times with the viewer, view /proc/{pid}/VMRss has been growing
2、By viewing `/proc/{pid}/status`, it is found that the increase of vmrss is mainly caused by the increase of RssAnon
3、 VmRSS will not be reduced, in some small memory embedded devices insufficient memory, there will be OOM problems
4、KVS webrtc, branch: master, git commit: 0ae9ec6b80deff9df724555927fb6595a23054f1

### Reproduction Steps

![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/10653136/a5bce916-5424-4632-8797-d9b6d563a10a)
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/10653136/09548ee1-cb4b-4bfa-bbbb-355c0e1dc7b4)

### WebRTC C SDK version being used

branch: master, git commit: 0ae9ec6b80deff9df724555927fb6595a23054f1

### Compiler and Version used

gcc version 7.5.0

### Operating System and version

ubuntu1~18.04

### Platform being used

Linux version 4.15.0-213-generic (buildd@lcy02-amd64-079) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023

**Comment by stefankiesz** [comment] 2024-01-03 20:51
Hi, can you please confirm the following:
1. What your use case is that involves viewers periodically joining and leaving.
2. Whether you have experienced the potential Out Of Memory problem.
3. Do you see the same behavior when using the [develop](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/develop) branch?
4. What you are using as a viewer (C SDK, browser Test Page, etc.).
5. How long the viewer was connected and master was running.

And please refer to discussion https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/discussions/1868 to compare with expected memory-useage behavior.

**Comment by remainfox** [comment] 2024-01-04 05:48
1、The departure is not scheduled regularly; it's like broadcasting for 5 seconds, pausing, then maybe 10 seconds next time, stopping viewing, and continuously repeating.

2、No.

3、I am using the main branch master, have not modified the source code, it is the main branch master.

4、I am using a browser, https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html, this link.

5、The duration of the viewer's connection is random.

6、VmRss leakage is inevitable, just randomly pull the stream a few times and you will find the issue of VmRss increasing. The key point is that VmRss does not decrease, which I think might not be a problem with Pthread Detach.

**Comment by niyatim23** [comment] 2024-01-08 11:33
Hi @remainfox, the memory would increase up to a certain point but it would become steady after that. Do you see anything with valgrind? We have run valgrind in the past and saw nothing: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1841#issuecomment-1787583443

**Comment by remainfox** [comment] 2024-01-09 08:23
`VmRss` increases to a critical value and then `stabilizes`. 
Checking heap memory leaks through gperftools, GCC MSAN, vargrind also doesn't find anything abnormal. 
I don't know if this is caused by linux fragmentation, I'm not sure if I can optimize these problems with memory pools

**Comment by niyatim23** [comment] 2024-01-09 08:25
That is expected behavior as the resources from PeerConnection, IceAgent, TURN / STUN are being assigned memory each time you tear down / disconnect from the viewer

**Comment by remainfox** [comment] 2024-01-12 08:58
@niyatim23 After adding the memory pool function, vmrss will still increase, the vmrss peak will decrease, the performance is the same as before, and the peak will be stable, I can not understand the multiple allocation of memory, why vmrss will increase so much

**Comment by niyatim23** [comment] 2024-01-12 09:27
@remainfox, can you elaborate on the memory pool and how are you using it? I'm not sure how it would change the behavior of our SDK

**Comment by remainfox** [comment] 2024-01-12 09:41
@niyatim23 
1、`PSampleStreamingSession`, `PKvsPeerConnection`, `ConnectionListener`, `PIceAgent`, `CreateTurnConnection`, these five structures are changed to` one-time memory allocation`. The individual struct objects are instantiated by offsets in order to reduce the number of malloc

2、`createStunPacket`, `createKvsRtpTransceiver`, `createTransactionIdStore`, `createJitterBuffer`, `createRtpRollingBuffer`, `createRollingBuffer`, `createRetransmitter`, `createSocketConnection`, `createIceCandidatePairs`, The malloc of these functions takes the form of a global memory pool (multiple memory blocks such as 2048 bytes, 4098 bytes, 32K bytes are allocated first)

**Comment by disa6302** [comment] 2024-02-07 19:48
@remainfox ,

To clarify, if the concern is high memory usage, memory pool would still not help because the objects still need to be allocated and persist in memory. However, you can try disabling TWCC which is enabled by default. TWCC consumes memory and if you are not looking to use it, you can disable by setting the flag to `TRUE` here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1159

Another option is to reduce the rolling buffer size by editing these values: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.h#L13-L14. [This](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c#L298) is where the calculation happens. We are looking at making this configurable through some options that can be set up in the sample, but no ETA yet. 

As stated earlier, the SDK does have an initial increase in memory allocation during set up and till the rolling buffer fills up after which it stabilizes. And if new viewers are added, there will be additional memory usage too. The usage would drop when the viewer disconnects and drop more once the application exists. If you would like to confirm all allocations within the SDK are freed, our sample has `RESET_INSTRUMENTED_ALLOCATORS()` which returns an error code if there is a memory leak. 

I am closing this issue assuming answered, but do feel free to reach out if you notice any memory leaks or need more support.

**Closed by disa6302** 2024-02-07 19:48 UTC
Labels: bug
