### ISSUE TITLE
Sometimes master can't receive the offer SDP and candidates from viewer.

### ISSUE THREAD

**Issue by Teresa7755** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#493] opened 2020-05-26 10:05 UTC
I found the webrtc master is connected with server, but sometimes it can't receive any offer SDP and candidates from viewer until websocket reconnection.

**Comment by lherman-cs** [comment] 2020-05-26 15:42
Hi @Teresa7755, do you mind to share the logs?

**Comment by MushMal** [comment] 2020-05-26 16:47
@Teresa7755 per @lherman-cs suggestion, please share the viewer and the master debug logs.

**Comment by Teresa7755** [comment] 2020-05-27 08:55
> Hi @Teresa7755, do you mind to share the logs?

[webrtc(Master).txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4687607/webrtc.Master.txt)
[WebRTCConnect(Viewer).zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4687608/WebRTCConnect.Viewer.zip)
Of course.  I test 7 times and all the requests from the viewer didn't be received by master. Could you please help to check this issue? Thanks.

**Comment by lherman-cs** [comment] 2020-05-27 18:35
@Teresa7755 What channel name did you use for the viewer? 

I saw that master used "749D79DD9DFF-2020CWA000299", which seems to be randomly generated. I'm afraid that your viewer didn't use the same channel name, and therefore the signaling messages from the master never arrived.

**Comment by Teresa7755** [comment] 2020-05-29 01:55
> @Teresa7755 What channel name did you use for the viewer?
> 
> I saw that master used "749D79DD9DFF-2020CWA000299", which seems to be randomly generated. I'm afraid that your viewer didn't use the same channel name, and therefore the signaling messages from the master never arrived.

The channal name that master used is MAC address and Serial number of the device. Each device has its own channel name and it will not be changed. Viewer should have the correct channel name because this issue doesn't always happen. When the websocket of master reconnect, viewer may play the live streaming successfully.

**Comment by lherman-cs** [comment] 2020-05-29 15:34
@Teresa7755 Ah I see. From the logs, I could only find that the message from the viewer somehow got lost. 

To expand our finding, I've asked our backend team to take a look into the signaling channel's log.

**Comment by Teresa7755** [comment] 2020-06-01 09:33
Hi @lherman-cs . That's strange.  In our system, App as a viewer should send offer SDP and candidates to camera, camera will always be a master and send the answer after receiving the offer.

**Comment by Teresa7755** [comment] 2020-06-01 12:18
These are the latest logs. From the logs,  master didn't receive the offer at all from viewer on 2020-06-01T183217.601+800. So the live streaming always failed from that time on. This issue often occurs during our tests. Could please help to check this issue? Thank you.
[WebRTCConnect_viewer0601.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4711133/WebRTCConnect_viewer0601.zip)
[webrtc_master0601.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4711135/webrtc_master0601.txt)

**Comment by lherman-cs** [comment] 2020-06-01 21:59
@Teresa7755 I still couldn't find any offer coming from viewers, I could only find from master.

To make sure that I'm identifying the issue correctly, would you mind to share/verify some details?
1. What's your timezone? From your logs, I found that you're in UTC+8.
2. Could you try to rerun your viewer with `AWS_KVS_LOG_LEVEL=2` environment?

**Comment by Teresa7755** [comment] 2020-06-03 04:01
> @Teresa7755 I still couldn't find any offer coming from viewers, I could only find from master.
> 
> To make sure that I'm identifying the issue correctly, would you mind to share/verify some details?
> 
> 1. What's your timezone? From your logs, I found that you're in UTC+8.
> 2. Could you try to rerun your viewer with `AWS_KVS_LOG_LEVEL=2` environment?

1. Yes, it's UTC+8
2. Viewer used Android SDK, does it have AWS_KVS_LOG_LEVEL ?

**Comment by chehefen** [comment] 2020-06-03 21:00
our log shows that there was no offer sent in channel 00C002450461-2004ISBU00001 from 2020-06-01T12:11:06 UTC to 2020-06-02T08:37:30 UTC. Can you check that app is using the right channel?

**Comment by Teresa7755** [comment] 2020-06-04 07:00
Could you please help to check if there were offer requests sent in this channel from 2020-06-01T10:32:17 UTC to 2020-06-01T10:48:40 UTC? App sent the offer requests during that time, but camera didn't receive them.

**Comment by chehefen** [comment] 2020-06-04 20:53
Log says that offer could not be sent because no master was connected. Can you check if your camera is connected to signaling channel?

**Comment by Teresa7755** [comment] 2020-06-05 03:09
Yes, the log I shared shows that camera was connected to signaling channel at 2020-06-01T10:31:31 UTC and received ping_pong callback and writable callback regularly. 
[
![D2E2EDF6-5524-4F81-BA76-56B57B05B034](https://user-images.githubusercontent.com/65950956/83831871-e0291b00-a71a-11ea-8123-2cfb3215e188.jpeg)
](url)

**Comment by chehefen** [comment] 2020-06-05 17:26
which commit of sdk are you using?

**Comment by MushMal** [comment] 2020-06-09 20:26
@Teresa7755 it seems that your viewer times out and can't connect within the 10 sec. From the viewer log it seems that it was able to connect to the websocket but the SDP exchange times out. 

While I am not yet sure what's going on, I was wondering whether you can answer also the following. How often can you reproduce this issue? Once reproduced, does the viewer keep failing? During this time, could you connect to master using JS test page?

We would like to narrow this down whether it's an issue with the master not receiving the offer or the Android client unable to send it.

**Comment by coldheartday** [comment] 2020-06-11 03:03
@MushMal 
 I reproduced it twice from the last 24 hours. In the last reproduced, app viewer keep failing and viewer through  AWS console also failed.  Attached is master's log, reproduced time is  from 2020-06-11 10:20:20( UTC+8) to 2020-06-11 10:39:29( UTC+8), chanel "749D79DD9DFF-2020CWA000299"
[webrtc_master_0611.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4762332/webrtc_master_0611.txt)

Besides, I can view another channel "749D79DD9DFC-2020CWA000296" through AWS console at the same time. 

At 06-11 10:58(UTC+8), I can view channel "749D79DD9DFF-2020CWA000299" through AWS console at the same time.

**Comment by MushMal** [comment] 2020-06-12 04:11
Sorry for the delay. I have spent some time looking through the log. Mostly, it seems just fine and I do see some playback happening. However, just around the time mentioned 10:20:20 I see disconnect in the log:

`[2020-06-11 10:21:34 711657] lwsHttpCallbackRoutine(81): Client connection failed. Connection error string: closed before established
`
Due to the fact that you are using cached calls, the state machinery doesn't issue describe/getendpoint but rather uses the cached values and circles back to connect. It does eventually get re-connected:

`[2020-06-11 10:21:38 401025] signalingClientStateChanged(123): Signaling client state changed to 9 - 'Connected'`


There are few other instances of being unable to reconnect or refresh ICE but the built-in retry mechanism is able to recover.

This said, I really can't explain why the offer doesn't get through yet. 

Is this a particular device that's exhibiting this behavior? I am trying to see whether networking could be the culprit.

Can I ask you to 

1) disable the caching for now in order to reproduce this and get more info?

`pSampleConfiguration->channelInfo.cachingPolicy = SIGNALING_API_CALL_CACHE_TYPE_NONE;`

2) Run the sample master program only without the caching and see whether this reproduces.

**Comment by MushMal** [comment] 2020-06-16 21:47
Ping

**Comment by coldheartday** [comment] 2020-06-18 01:59
Sorry for late, test environment changed recently.
This issue can happened on all device.  As suggested, I disabled the caching and reproduced this issue again. Reproduced time is from 2020-06-18 09:30:00( UTC+8) to 2020-06-17 09:35:00( UTC+8),
channel "749D79DD9DFF-2020CWA000299". Both app viewer and AWS console palyer keep failing.
![image](https://user-images.githubusercontent.com/46836038/84968527-482f2680-b149-11ea-9cf4-c55a337295cd.png)
After auto refresh the ICE Configuration at 09:35:02, viewer return to normal.
[webrtc_0618.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4795835/webrtc_0618.txt)

**Comment by coldheartday** [comment] 2020-06-18 02:21
Add one reproduce. I stop AWS console live streaming , try on app but failed. Then keep failing.
From 2020-06-18 10:00:00( UTC+8) to 2020-06-18 10:10:00, both viewer keep failing even though refreshed the ICE Configuration.  Viewer return to normal after restart Master process.
[webrtc_0618_1012.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4795905/webrtc_0618_1012.txt)

**Comment by MushMal** [comment] 2020-06-22 19:12
@coldheartday looking at the attached log (webrtc_0618_1012.txt) I don't see any offers coming to the master but the connection is OK. 

Can you clarify whether you are using stock master sample without any modifications? If not, could you keep running the stock master sample and see whether this issue reproduces? If it does then what's the output on the viewer side? Is it possible that the viewer simply can't connect to the signaling?

Unfortunately, it's impossible to help without being able to reproduce this locally so we need more details to help/suggest some course of action

**Comment by coldheartday** [comment] 2020-06-29 03:03
Hi @MushMal , we have only changed things like getting video/audio frame, cert, server path, thing name...etc. These should not affect signaling.  
Viewer offer request to server and failed with timeout while master never receive request. Could you please help to check if there were offer requests sent in this channel from 2020-06-18 10:00:00( UTC+8) to 2020-06-18 10:10:00.

**Comment by lherman-cs** [comment] 2020-06-29 16:54
This seems to be related to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/562.

**Comment by MushMal** [comment] 2020-07-31 01:13
Are we able to reproduce this after the backend changes went in?

**Comment by sharadrj** [comment] 2020-08-08 19:16
@coldheartday, @Teresa7755, 

This issue should be fixed now with the service fixes in #562. Please re-open if you can still able to reproduce it.

**Closed by sharadrj** 2020-08-08 19:16 UTC
Labels: Signaling client
