### ISSUE TITLE
[Question] Decode rate of 0 fps every 5 - 10 minutes

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#957] opened 2020-11-17 20:58 UTC
**Describe the bug**
We've been observing 30-60 seconds of 0 decode rate every 5 to 10 minutes on armv7. To allow AWS to help us as much as possible, we've tried to reproduce the problem on a common platform.
We've reproduced this on both TURN and STUN for armv7 and TURN for Mac. We are still trying to come up with better reproducible steps for STUN for Mac.

**SDK version number**
armv7: v1.3.0
mac: v1.4.0

**To Reproduce**
1. build kvs gst sample on mac.
2. use the stock webrtc viewer webpage.
3. force turn, if we can use a remote viewer, it is more reproducible.
- we can reproduce this with STUN with armv7.
- we are still trying to reproduce this with STUN with mac.
4. monitor inbound video stats graph of chrome://webrtc-internals
5. after 5 to 10 minutes, we observe a gap of 30 to 60 seconds of 0 frame decoded per second, after which we see the browser decoder recovers.

**Expected behavior**
The browser can decode.

**Screenshots**
Here are screenshots of when this is happening
The negotiated profile id is level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f for Windows 7
![0decodeMac](https://user-images.githubusercontent.com/61390265/99445097-f5ad8e00-28d1-11eb-8edb-a42819b96eb2.PNG)
![0decode3](https://user-images.githubusercontent.com/61390265/99445103-f8a87e80-28d1-11eb-8f27-2fa850b30d68.PNG)
![0decode4](https://user-images.githubusercontent.com/61390265/99445108-fb0ad880-28d1-11eb-93a7-4791721a10e0.PNG)

**Desktop (Viewer):**
 - OS: Win 7, (also reproduced with win 10 with armv7)
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (64-bit)

**Additional context**
For armv7:
- Currently, for armv7, H264, we can only test with main profile and high profile. So there is a possibility where there is a profile mismatch between negotiated browser decoder profile and device encoder profile. Currently, on the device (master) side, we prioritize selecting 42e01f decoder with packetization mode of 0. We might have to ask our device vendor to enable baseline-profile. With packetization mode of 1 selected in the SDP answer, some browsers cannot decode properly.
- We've tried PLI handling, which did not help.
- We've patched the v1.3.0 for RTP timestamp conversion for armv7. Did not help.
- We've also tried different O flags and weird flags such as with or without -Wno-psabi. Did not help.

For armv7 and Mac:
- Is it possible, for TURN connections, the TURN server will try to allocate a session that will expire after 5-10 minutes, and both browser and master has to reconnect?
- If we can reproduce this with STUN, what could be the cause?
- We are still collecting more data.

**Comment by suggestedfixes** [comment] 2020-11-17 21:06
I found the following code, turn permission lifetime of 300 seconds corresponds to 5 min, correct? So would this be relevant?
```
// https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers
--
  | #define TURN_REQUEST_TRANSPORT_UDP               17
  | #define TURN_REQUEST_TRANSPORT_TCP               6
  | #define DEFAULT_TURN_ALLOCATION_LIFETIME_SECONDS 600
  | // required by rfc5766 to be 300s
  | #define TURN_PERMISSION_LIFETIME                 (300 * HUNDREDS_OF_NANOS_IN_A_SECOND)
  | #define DEFAULT_TURN_TIMER_INTERVAL_BEFORE_READY (50 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
  | #define DEFAULT_TURN_TIMER_INTERVAL_AFTER_READY  (1 * HUNDREDS_OF_NANOS_IN_A_SECOND)
  | #define DEFAULT_TURN_SEND_REFRESH_INVERVAL       (1 * HUNDREDS_OF_NANOS_IN_A_SECOND)


```

**Comment by suggestedfixes** [comment] 2020-11-17 21:14
The screenshots from the first post is from Mac, there are a few misc Screenshots from armv7:
![zeroDecodeRate](https://user-images.githubusercontent.com/61390265/99450817-24c5fe80-28d6-11eb-9865-1d1cd4c6a476.PNG)
![123](https://user-images.githubusercontent.com/61390265/99450831-2bed0c80-28d6-11eb-9584-17e0b7281194.PNG)
![000](https://user-images.githubusercontent.com/61390265/99450838-2db6d000-28d6-11eb-9e84-4e95d9f62595.PNG)
![001](https://user-images.githubusercontent.com/61390265/99450842-30192a00-28d6-11eb-86e0-fd2bf361fccb.PNG)

Several observations/causes/effects/correlations:
- some 0 decode rate correlates to increased pli.
- some 0 decode rate are accompanied by a sharp step increase in frames dropped.
- after recovery, the frame decoded will increase, indicating something is queued up.
- nack rate is usually pretty high.

**Comment by MushMal** [comment] 2020-11-17 21:26
Turn permissions are for the initial connection and not during the streaming. 

Can you reproduce this with the stock master sample which uses canned frames instead of a real media pipeline? What’s the debug log on the master during this event? How long does the event last? What are the debug steps that you have taken?

**Comment by MushMal** [comment] 2020-11-17 21:26
Removing bug label as we are not sure whether it’s sdk related yet

**Comment by suggestedfixes** [comment] 2020-11-17 21:49
Initial results for canned frames, there is a quick dip in framesDecoded/s around 5 min mark, then it quickly recovers within a few seconds. Canned frames have SPS and PPS on each frame, correct?
![image](https://user-images.githubusercontent.com/61390265/99454738-aff5c300-28db-11eb-973b-e375317803cd.png)

**Comment by MushMal** [comment] 2020-11-17 22:10
From the graph it seems the decode issue corresponds to the packet loss.

The pre-canned frames have a few I-frames I believe which are in Annex-B format and they do have sps and pps. Need to double check but could someone confirm as I am away from my desk? @lherman-cs?

**Comment by suggestedfixes** [comment] 2020-11-17 22:20
I can use some hexdump to take a look, they do seem to recover quicker, another example:
![image](https://user-images.githubusercontent.com/61390265/99457570-0cf37800-28e0-11eb-8ae6-10298fa643f5.png)

**Comment by suggestedfixes** [comment] 2020-11-17 22:43
For canned frames, there's one every 250 frames. So it recovered pretty quickly without SPS and PPS.

**Comment by MushMal** [comment] 2020-11-17 22:44
We will also run the same long haul but my suspicion is the network packet loss. Can you perform same tests over a different network topology as well? Every decode event you have corresponds directly with a spike in intraframe delay and packet loss. Run a p2p over a stable connection to eliminate anything related to the actual encoding.

The faster recovery is simply happening due to the frequent I frame I think.

**Comment by suggestedfixes** [comment] 2020-11-17 23:10
I think our media pipeline supplies one I frame every 20 frames at 20 fps. Anything odd with the GStreamer sample for slower recovery?

**Comment by suggestedfixes** [comment] 2020-11-17 23:14
What is also odd is that the canned frames example is that it did not mark keyframes. Maybe one thing I could try is to do the same: not marking keyframes.

**Comment by MushMal** [comment] 2020-11-17 23:21
For webrtc we currently ignore the supplied flags with the frame structure - those can be used later but not right now. 

The decoder works on an elementary stream and as such it depends on the actual frames in the NAL packaging in AnnexB format.

Again, per my comment, try to eliminate the media pipeline issue by connecting p2p via good network in the same subnet. Once you see good performance without any packet loss and intraframe delay you should also see no decode issues. If this is the case then you have a networking problem. Debug your network topology

**Comment by suggestedfixes** [comment] 2020-11-17 23:40
But even with the worst case where there is a packet loss, the canned example recovered pretty quickly. I wonder if it's the exact codec match that is doing the work?
What makes the GStreamer example recover slower?

**Comment by suggestedfixes** [comment] 2020-11-17 23:47
Actually also reproduced locally with canned example:
![image](https://user-images.githubusercontent.com/61390265/99463932-c146cb80-28eb-11eb-9595-cc9d233cda19.png)

**Comment by lherman-cs** [comment] 2020-11-17 23:48
> From the graph it seems the decode issue corresponds to the packet loss.
> 
> The pre-canned frames have a few I-frames I believe which are in Annex-B format and they do have sps and pps. Need to double check but could someone confirm as I am away from my desk? @lherman-cs?

Yes, the pre-canned frames are in Annex-B and contains sps and pps

**Comment by lherman-cs** [comment] 2020-11-17 23:51
@suggestedfixes are you seeing a lot of "Frame with timestamp %ld is dropped!" logs?

> Actually also reproduced locally with canned example:

Would you mind to share the reproducible steps?

**Comment by MushMal** [comment] 2020-11-17 23:52
@suggestedfixes again, even with local (assuming p2p) you have high level of packet loss. There is little we can do to help you debug your network router.

Regarding recovery. Currently, the SDK handles the pli sdp message and calls a callback that’s not handled in the application. The recovery speed depends on many factors including the dropped packet type, how tolerant the decoder is to the packet loss, etc... in case if the decoder fails entirely then the consequent p-frames will be lost so frequent I-frames make it recover earlier.

**Comment by suggestedfixes** [comment] 2020-11-17 23:55
Currently, I believe we have SPS and PPS embedded in the I-frame and sending an I-frame every second. The decoder should in theory recover in a few seconds if not one second.

**Comment by lherman-cs** [comment] 2020-11-18 00:01
> Currently, I believe we have SPS and PPS embedded in the I-frame and sending an I-frame every second. The decoder should in theory recover in a few seconds if not one second.

Could you try to reduce the bitrate? So we can make sure that this is not a network issue.

**Comment by suggestedfixes** [comment] 2020-11-18 00:12
I will try that, current bitrate is 1Mbps variable.

**Comment by suggestedfixes** [comment] 2020-11-18 02:48
To me, this is also predictable, it always occurs every 5 +/- 1 minute and always around 30 +/- 30 seconds. So I wonder if there is a periodic process that hogs the resources.

**Comment by suggestedfixes** [comment] 2020-11-18 02:51
Also if there are multiple sessions running, they all stop decoding at the same time. If it's packet loss, it should have been more random.

**Comment by suggestedfixes** [comment] 2020-11-18 05:21
armv7, local, h264 baseline, no packet loss, 0 nack count, occurring every 5 minutes. Also note when the decode rate is 0, the incoming bitrate did not drop. (possibly reproducible with the GStreamer sample)
![image](https://user-images.githubusercontent.com/61390265/99487283-ccfdb680-291a-11eb-9dc2-50ea958e6127.png)

**Comment by MushMal** [comment] 2020-11-18 05:27
Not sure why you have a lot of frames dropped in the graph which also then corresponds to the inter frame delay.

I will leave it there pending your debugging. We will also give it a quick try and see if we can reproduce any of what you are seeing in our environment with stock components. 

Try to isolate the networking first with the stock master sample

**Comment by suggestedfixes** [comment] 2020-11-18 06:08
I see what's going on! Because timestamps are UINT32, it rotates after (2^32 - 1) / 60e7 = 7.15 minutes. I was using GETTIME(), so it is even less.

**Comment by suggestedfixes** [comment] 2020-11-18 06:08
So I will try to make video timestamp and audio timestamp UINT64.

**Comment by suggestedfixes** [comment] 2020-11-18 06:09
Background: we found that decreasing timestamps can throw off decoders, especially the timestamps that wrap around.

**Comment by MushMal** [comment] 2020-11-18 06:11
Hmm OK. I am glad we didn't sink too much time into this then. Do you mind resolving this once verified it's related to your timestamp issue?

**Comment by suggestedfixes** [comment] 2020-11-18 06:13
I need to run this overnight. It might have been another cause. I just identified a minor detail.

**Comment by suggestedfixes** [comment] 2020-11-19 01:28
Would a good action item list be?
- try to reproduce the problem with the GStreamer sample.
- changing sample timestamps to be UINT64 near here:
    - https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Samples.h#L115

**Comment by MushMal** [comment] 2020-11-19 02:23
RE: the audio and video timestamps in the Samples.h - I really have no idea how this was made 32 bit. This MUST be 64 bit. I am not sure what the action item is with the GStreamer sample - would look forward if you repro something.

PS: Please let me know if you are going to send a fix for the 32->64 bit timestamps

**Closed** 2020-11-20 02:07 UTC
Labels: question
