### ISSUE TITLE
[QUESTION] Max [peer count]/[remote candidates] reached

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#839] opened 2020-10-02 19:10 UTC
This is related to this issue.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/469
We are still seeing cases of add peer failed using v1.3.0.

We wonder if it's possible from the app side to purge zombie peers periodically?

**Comment by suggestedfixes** [comment] 2020-10-02 19:17
For now, I think it might be safe for me to test with a MAX_PEER_COUNT, but are we sure they are no cases where there's no extra peer build up?

**Comment by suggestedfixes** [comment] 2020-10-02 20:30
Also getting:
iceAgentCheckPeerReflexiveCandidate(): max remote candidate count exceeded
Steps:
v1.3.0
- master gst example
- open https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
- fill in credentials with client id = a
- open another tab with the same client id, open and close viewer connections.

**Comment by suggestedfixes** [comment] 2020-10-07 07:41
Got a lot better with v1.3.0 SDK, but with the newest sample app. I will test a bit more.

**Comment by MushMal** [comment] 2020-10-07 17:13
@suggestedfixes could you please summarize what the issue is? I can't immediately tell whether there is an issue with the master sample or what kind of issue there is. Please resolve if no issues

**Comment by suggestedfixes** [comment] 2020-10-07 17:27
It's a combination of SDK max peer set and old v1.3.0 sample not able to salvage ice candidates.
The newest sample uses a hash table to keep track of ice candidates and in theory, will clean those up properly.
I will try to reproduce with the latest sample.

**Comment by MushMal** [comment] 2020-10-07 17:47
OK. Resolving this issue. Please cut a new issue or reopen if needed.

**Closed by MushMal** 2020-10-07 17:47 UTC
Labels: question
