### ISSUE TITLE
[QUESTION] Why does sample not stop sending after disconnect?

### ISSUE THREAD

**Issue by atyshka** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1057] opened 2021-01-29 17:12 UTC
When running sample code for sending frames, the program keeps sending frames even after I close the webrtc session in the browser. It should be possible to detect a disconnect and stop sending frames, if so, it would be great to see this demonstrated in the examples. My only modifications to the kvsmaster example were adding a printf before calling sendFrame to demonstrate that frames were still being sent.

**Comment by MushMal** [comment] 2021-01-29 18:25
During streaming the only way the peer "learns" about the session stop when the DTLS detects a disconnect. After a period of time of retry it goes to failed state which then the samples listen to and properly close the session. If the peer doesn't "gracefully" tear down the DTLS session the other peer will take some time to go into failed state. This is the async nature of the RTP.

The master sample should properly detect a DTLS disconnect from the stock browser (Chrome, FireFox) webrtc implementation if the stop button is clicked. Are you not seeing a stop of the session on the master after this? Does your master keep sending frames forever?

**Comment by atyshka** [comment] 2021-02-01 14:46
It seems to keep sending frames forever. I am testing using the builtin viewer on the KVS console. in Chrome

**Comment by MushMal** [comment] 2021-02-01 18:30
I am not sure what the root cause is but I can't repro this on the latest master and the Chrome console playback.

Could you please include a lot more details? Are you using absolutely stock master sample latest commits? Are you using the same channel name? Can you use the latest Chrome or FireFox? Are you sure there is a single viewer running? Please include the detailed debug/verbose level logs so we can see if we can pinpoint the issue? 

As I mentioned, regardless of the case, there will be session termination - either gracefully or via timeout.

**Comment by hassanctech** [comment] 2021-02-09 05:42
@atyshka Just wanted to say we're still waiting for some more detailed information as requested by @MushMal to help debug this issue.  If you are no longer encountering the problem please feel free to close this issue.

**Closed** 2021-02-10 14:41 UTC
Labels: assume answered, question
