### ISSUE TITLE
webrtc master received audio background noise amplified problem

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#657] opened 2020-07-24 10:05 UTC
Hi, Sir,
We've done implementing the WebRTC C SDK in our IOT device (as a webrtc viewer) and we only send G.711 format audio while using webrtc for our telephony application; the audio transfer between WebRTC test page and our device is O.K., but one issue is 
that the audio background noise is amplified while hearing the audio (sent from the viewer) in the master side, however, we've tested dumping the audio before sending out in the viewer; the dumped audio is no background noise. The attachment is the recorded audio from test page master side (to show what the background noise is); the background noise is more apparent between each speaking Chinese words.

Our device (webrtc viewer side) send 1KB G.711 audio out every 125 milli-second; I'm curious if this issue is related to the audio packet segmentation ?? or do you have other thought for this ?

[Master_side_recorded_backgroundNoise.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4971294/Master_side_recorded_backgroundNoise.zip)

**Comment by MushMal** [comment] 2020-07-24 16:55
Not really sure. Depending on your reproducing device audio path (the decoder + the DSP + speakers) you might get weird artifacts if timing is not correct. You might want to validate it with your audio experts. When it comes to WebRTC, you could check whether the timing is impacted by poor network and re-transmitting of some of the packets.

**Comment by ajjiang48** [comment] 2020-07-27 10:10
@MushMal I do save the audio stream to the file before calling writeFrame to the C SDK; the file is clean without noise, so the issue happens from the audio frame segment transmission; don't know which parts cause it.
On the other hand,  you mentioned "re-transmitting of some packets", how do I know which audio frame I should do the re-transmission ??, and, do you think that background noise caused by the audio frame lost ?? 
Thanks,
A.J.

**Comment by lherman-cs** [comment] 2020-07-27 16:23
@ajjiang48 do you mind to check rtp inbound stats from chrome://webrtc-internals? I'm afraid that there's a lot of packet loss or jitters. This will provide more insight to the root cause.

**Comment by ajjiang48** [comment] 2020-07-29 07:11
@MushMal @lherman-cs after doing some buffering/timing related codes modification, it looks this issue is caused by the inaccurate timestamp value (frame.presentationTs variable) before calling writeFrame; I get and send 8 audio frames per seconds, so it should be 125ms per audio frame, however, it looks change the increment to 130ms~135ms  to presentationTs  won't have the background noise; it's still under testing. Thank you for the input.
A.J.

**Comment by MushMal** [comment] 2020-07-29 07:26
Do you mind resolving this issue please?

**Comment by shiv50084** [comment] 2020-07-29 07:45
@ajjiang48 
We are facing 2 problems with master:
1). One is  background noise on master (decoder Init at 8KHz, chn =1) .When we are sending G711A audio from Viewer from JS test page,
2). When we are sending G711A audio from master to viewer (JS test page) . Then we are not able to hear any sound on viewer test page.

Can you please help us for this?

**Comment by ajjiang48** [comment] 2020-07-30 09:16
@MushMal @shiv50084 I don't think I could help much on your problem (I'd like to if I can); let me clarify, my adjustment for the frame.presentationTs value (125 to 130~140) is audio codec/driver specific (not pure software related) and I use webrtc C SDK implementing webrtc viewer instead of JS SDK; it looks your issue 1 and 2 are all related to JS SDK implementation.
btw, what's your background noise sound? could you upload the sound clip? and, do you use C or JS SDK to implement master/viewer ?
Thanks, A.J.

**Comment by shiv50084** [comment] 2020-07-30 09:42
@ajjiang48 
My issue is resolved after changing timestamp and encoder settings. I am working on IOT camera which works as master.

I am using C SDK for my platform.

For background noise if i am sending a audio from JS test page which running on system its comes always.

If same audio i am sending from mobile generic testing app. Its come without any noise.

**Comment by ajjiang48** [comment] 2020-07-30 10:26
@shiv50084 you use webrtc C sdk implementing webrtc master on an IOT camera, right? so, your IOT camera has a speaker or audio out for receiving and playback the webrtc viewer's audio ? (looks weird for an camera, so I'm confirming). As for the incoming audio frame process, do you use a single thread for processing those audio frame? and do your player playback the G711A audio directly? or you need to transcode it to PCM?  and the last, what do you mean "mobile generic testing app" for your last sentence?
Thanks,
A.J.

**Comment by shiv50084** [comment] 2020-07-30 10:34
@ajjiang48 
My IOT Camera support 2-Way talk feature.I am receiving G711A directly from encoder to send it to webrtc Client and Receiving G711A audio from webrtc Client send it directly to G711A decoder ( without transcoding to PCM ) without using any thread.

From this link you will get Android SDK to make an generic APP:-
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-android.html

**Comment by ajjiang48** [comment] 2020-07-30 10:42
@shiv50084 what is the size of each G711A audio frame ? what's your receiving buffering architecture? do you try gather more G711A audio frames and combine them to 1 bigger G711A audio frame then send it once to the audio decoder ??
Thanks,
A.J.

**Comment by shiv50084** [comment] 2020-07-30 10:58
@ajjiang48 
My Current G711A packet size 480 Bytes .Which is 60ms, sampling at 8KHz,

I am not accumulation G711A audio buffer into 1 bigger buffer.
Whatever audio buffer i am receiving from encoder i am directly sending it to writeframe API.
and whatever i am receiving from webrtc client i am directly sending it to decoder without combining it into 1 bigger buffer.

**Comment by MushMal** [comment] 2020-07-30 17:05
This is a great discussion going on in this thread. I would like to resolve the ticket but keep the discussion going or using another issue to discuss it.

In general, we have seen 1:1 mapping of encoded g711 to frames. From the perspective of RTP - that's the case but some media pipelines might have particular needs to batch them together (never heard of those).

**Closed by MushMal** 2020-07-30 17:05 UTC
Labels: question

**Comment by ajjiang48** [comment] 2020-07-31 03:34
@MushMal so, do I reply here or another thread ?

**Comment by MushMal** [comment] 2020-07-31 04:48
We generally try to keep the open issues to items that have active actionable following. We are strongly encouraging folks to comment on costing issues even if the issue is in a resolved state - we still monitor and contribute. We also encourage opening separate issues if they need any traction
