### ISSUE TITLE
[BUG] onFrameDroppedFunc leads to Segmentation fault.

### ISSUE THREAD

**Issue by aws-tec** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#821] opened 2020-09-24 17:40 UTC
**Describe the bug**
When playing stream from viewer(Test Webpage) side for a while, the master(C SDK) side will lead to segmentation fault because of pTransceiver->statsLock can not be accessed.

**SDK version number**
Commit ID: 8c1eaf09d8f27d13efdac3808b3d6b7cd554fa74

**To Reproduce**
It's easy to reproduce. Run the kvsWebrtcClientMaster and connect to master via test webpage. It takes random time to take place. Sometimes it can be reproduced via connecting and disconnecting loop. 

**Screenshots**
![螢幕快照 2020-09-25 上午1 34 44](https://user-images.githubusercontent.com/59637783/94179684-6edec500-fecf-11ea-910a-045ffdfcc0f8.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome, running as viewer via test webpage
 - Version: 85.0.4183.102

**Master Device (please complete the following information):**
 - Device: Raspberry Pi 4, Macbook Pro
 - OS: Raspberry Pi OS Buster 2020-08-20, macOS Mojave 10.14.6

**Comment by disa6302** [comment] 2020-09-24 17:47
@aws-tec ,

Can you please run your app under a debugger and provide a stack trace?

**Comment by aws-tec** [comment] 2020-09-25 01:52
@disa6302 
Please check the attached log file.
[segmentation_fault.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5280089/segmentation_fault.log)

**Comment by disa6302** [comment] 2020-09-26 00:17
@aws-tec ,

It is not immediately clear how the segfault is caused. Will spend some time on this to pin point the issue. For starters, I am going to try to reproduce this.

**Comment by MushMal** [comment] 2020-09-26 00:42
There were a set of fixes that went in around the jitter buffer allocations. @aws-tec Could you please include the commit version? Is this reproducible and how easy is it to repro on the latest commits?

**Comment by MushMal** [comment] 2020-09-28 17:44
I am looking at the crash dump but none of the lines match. From the look of it it seems there is a NULL deref somewhere. If I were to trust the line numbers, I would map it to the transceivers lock being NULL which is not possible on the normal path as it's created with the transceiver and if it failed to create then the transceiver itself would have failed.

Another issue if your code is freeing the transceiver but even here I am having a hard time understanding how it's possible as we free a number of auxiliary objects first - like jitter buffer, rtp, etc.. before tearing down the lock.

Could you please include some information whether you've applied any changes to the stock application or not. How do you reproduce this?

**Comment by aws-tec** [comment] 2020-09-29 02:49
I just downloaded the latest version of master branch. The commit id is 8c1eaf09d8f27d13efdac3808b3d6b7cd554fa74.
Same as I described above, I was running kvswebrtcClientMaster with gdb.
There is no specific reproduction was but run it up and disconnect and connect again.
The attached file is the latest gdb log with LOG_LEVEL_VERBOSE.
The region is ap-northeast-1 and I've enabled trickle ICE.
[gdb.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5296056/gdb.txt)

**Comment by MushMal** [comment] 2020-09-30 07:01
Seems to be related to issue #827 

Can you verify you are looking at 32 bit device?

**Comment by zwei333** [comment] 2020-09-30 14:07
Sounds familiar.  In issue #827, it crashes at exactly the same line

**Comment by disa6302** [comment] 2020-10-05 19:29
Issue is fixed in #827 . 

Closing this.

**Closed by disa6302** 2020-10-05 19:29 UTC
Labels: bug
