### ISSUE TITLE
[BUG] onFrameDroppedFunc has Segmentation fault problem

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#772] opened 2020-09-04 08:27 UTC
**Describe the bug**
**A mark**: %ld should be %lu for UINT32 type value
**B mark**: when process go here will has Segmentation fault problem
![image](https://user-images.githubusercontent.com/58592084/92218116-339e3700-eecb-11ea-9433-719979678ab5.png)

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that
![image](https://user-images.githubusercontent.com/58592084/92217718-a6f37900-eeca-11ea-8c6a-21dce58d9cd3.png)

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/58592084/92217487-55e38500-eeca-11ea-868e-2e9cf37024c4.png)

**Comment by disa6302** [comment] 2020-09-04 16:34
@henryChmn , 

The seg fault need not be due to `onFrameDroppedFunction`, Do you have a stack trace we could look at to pin point the problem? 

As for A. , thanks for pointing it out. Will fix it. 

Also, which version/commit of SDK are you using?

**Comment by henryChmn** [comment] 2020-09-07 03:27
console_sighandler:
Received signal 11, code(1)
Signal originates from process 1200
console_print_trace:
STACK: Obtained 3 stack frames.
STACK: ./aws_client() [0x29380]
STACK: ./aws_client() [0x28348]
STACK: /lib/libc.so.6(__default_rt_sa_restorer+0) [0x768f5190]

**Comment by MushMal** [comment] 2020-09-07 03:31
@henryChmn any chance you can capture the stack trace on a debug build? The attached info is not actionable.

@disa6302 any chance to reproduce the crash? I believe there was another instance reported after one of the latest commits.

**Comment by disa6302** [comment] 2020-09-08 16:54
@henryChmn ,

A full stack trace would be helpful. 

@MushMal , I have not been able to reproduce it in the usual sample runs.

**Comment by zhuker** [comment] 2020-09-14 14:02
@henryChmn +1 for full stack trace, please compile with debug symbols

**Comment by MushMal** [comment] 2020-09-14 18:57
@henryChmn have you had a chance to reproduce this and capture the crash stack?

**Comment by henryChmn** [comment] 2020-09-15 01:06
We had chance to reproduce this in poor connection condition, but not capture the crash stack in debug build yet.

**Comment by MushMal** [comment] 2020-09-15 01:36
Thanks, please try to run multiple different devices to maximize the chance. Try to run debug bits either under the debugger or with an OS crash stack capture.

I am afraid we will need detailed repro or the crash stack in order to be able to help

**Comment by zhuker** [comment] 2020-09-15 14:07
by looking at the code i dont understand where it may have crashed
the only idea i have is that pointer is used after it was freed

**Comment by MushMal** [comment] 2020-09-15 15:20
Perhaps, double check the callback or any other custom code you’ve added

**Comment by MushMal** [comment] 2020-09-16 07:21
Resolving this for now. Please cut a separate issue with the detailed crash dump of debug bits for us to be able to transact on

**Closed by MushMal** 2020-09-16 07:21 UTC
Labels: awaiting response, bug
