### ISSUE TITLE
[Bug]: Clonning "project_libopenssl" failed during cmake

### ISSUE THREAD

**Issue by Moadib129** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1904] opened 2024-01-19 05:46 UTC
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [x] I have all the details the issue requires

### Describe the bug

I am building the samples for my RaspberryPi 3B, and when i run the cmake command it fails
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/5d093eb9-2146-4eae-a17f-00b3b4dd3342)

### Expected Behavior

It should run the cmake command

### Current Behavior

But it is not doing that
![Screenshot 2024-01-19 104338](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/0b44c448-6def-40c1-84d7-f2a74f99bb09)

### Reproduction Steps

N/A

### WebRTC C SDK version being used

Latest

### Compiler and Version used

N/A

### Operating System and version

Rasbian OS

### Platform being used

Raspberry Pi

**Comment by disa6302** [comment] 2024-01-19 06:44
Wondering if the issue is related to using http2? Can you try setting this and then re-running?

```
git config --global http.version HTTP/1.1
```

**Comment by Moadib129** [comment] 2024-01-19 06:59
I have tried that, still the same issue

**Comment by disa6302** [comment] 2024-01-19 07:01
How about setting the http buffer size to a large value?
```
git config --global http.postBuffer <large-value>
```

**Comment by Moadib129** [comment] 2024-01-19 07:02
I have tried this too i tried 1048576000, but it takes me back to same issue again

**Comment by Moadib129** [comment] 2024-01-19 07:14
By the way, the repo was not clonning into raspberry pi same issue was happening. So, i used --depth=1 which resolved the issue
@disa6302  do you think it is due to using the --depth=1

**Comment by disa6302** [comment] 2024-01-22 04:42
It should not require a --depth=1, unless your device is extremely slow or low on memory. 
Openssl cloning does take time in general and with device constraints it could be worse.

There is also an option to build our SDK with dependencies off, in which case system openssl is used. So that is another option you can explore to save time and space in the build process.

Resolving since the issue is resolved. Feel free to reach out if you face any more issues.

**Closed by disa6302** 2024-01-22 04:42 UTC
Labels: bug, awaiting-requester-response
