### ISSUE TITLE
[Bug]: Wrong SDP answer when the codec doesn't match with viewer

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#2025] opened 2024-07-05 09:55 UTC
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Please answer the following prompt

- [X] This issue is replicable using the unmodified sample application

### Describe the bug

I switch to the latest version, and set the video codec to h265. When the viewer doesn't not support H264, the device will create a fake transceiver. But it creates a wrong media attribute of rtpmap.

### Expected Behavior

It create a valid sdp answer.

### Current Behavior

 Here is is the SDP answer:
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 127.0.0.1
a=candidate:2 1 udp 2130706431 192.168.2.106 60377 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=msid:fakeStream fakeTrack
a=ssrc:806117966 cname:QH4BKBHw9jx3IknE
a=ssrc:806117966 msid:fakeStream fakeTrack
a=ssrc:806117966 mslabel:fakeStream
a=ssrc:806117966 label:fakeTrack
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:n376
a=ice-pwd:c+R0wbpkxp/O9ny1pB427UyH
a=ice-options:trickle
a=fingerprint:sha-256 A6:93:AC:8B:13:93:BC:7F:D4:6A:B2:75:AD:B6:18:A2:0A:DA:14:1E:96:B1:15:CF:84:69:DC:1B:5C:D7:76:1F
a=setup:active
a=mid:1
a=inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:4294967295 VP8/90000
a=ssrc:806117966 cname:QH4BKBHw9jx3IknE
a=ssrc:806117966 msid:fakeStream fakeTrack
a=rtcp-fb:4294967295 goog-remb
a=rtcp-fb:4294967295 transport-cc

The m-line is 96, but rtpmap is 4294967295, 4294967295 = 0xffffffff.
In populateSingleMediaSection, after hashTableGet, the value of payloadType is been modified.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4f1d3add4c0f88212fe6646898e5aba140ecbb3c/src/source/PeerConnection/SessionDescription.c#L800-L802

I print the address of payloadType  and rtpMapValue:
payloadType = 0xb6074298, rtpMapValue = 0xb6074294

Since the type of rtpMapValue  is PCHAR, the size is 4 bytes, and the pValue is UINT64, it can modify the value of payloadType to 0xffffffff.
STATUS hashTableGet(PHashTable pHashTable, UINT64 key, PUINT64 pValue)

It can't be solved unless I change the code to the following.
        UINT64 rtpMapValueAddr;
        CHK_STATUS(hashTableGet(pUnknownCodecRtpmapTable, unknownCodecHashTableKey, (PUINT64) &rtpMapValueAddr));
        rtpMapValue = rtpMapValueAddr;

### Reproduction Steps

    pSampleConfiguration->videoCodec = RTC_CODEC_H265;

Start a viewer from WebRTC Test Page.

### WebRTC C SDK version being used

1.10.2

### Compiler and Version used

arm-buildroot-linux-uclibcgnueabihf-gcc-4.9.4

### Operating System and version

Linux (none) 4.9.84

### Platform being used

 armv7l

**Comment by hassanctech** [comment] 2024-07-25 17:21
@Nomidia I have run this in the manner you suggested but I cannot reproduce this, for me the answer [irrelevant parts redacted] looks like this:
```
m=video 9 UDP/TLS/RTP/SAVPF 96\r\n
c=IN IP4 127.0.0.1\r\n
a=msid:fakeStream fakeTrack\r\n
a=ssrc:456375337 cname:pXdbHrm5jPQ/Ur9w\r\n
a=ssrc:456375337 msid:fakeStream fakeTrack\r\n
a=ssrc:456375337 mslabel:fakeStream\r\n
a=ssrc:456375337 label:fakeTrack\r\n
a=rtcp:9 IN IP4 0.0.0.0\r\n
a=ice-options:trickle\r\n
a=setup:active\r\n
a=mid:1\r\n
a=inactive\r\n
a=rtcp-mux\r\n
a=rtcp-rsize\r\n
a=rtpmap:96 VP8/90000\r\n
a=ssrc:456375337 cname:pXdbHrm5jPQ/Ur9w\r\n
a=ssrc:456375337 msid:fakeStream fakeTrack\r\n
a=rtcp-fb:96 goog-remb\r\n
a=rtcp-fb:96 transport-cc\r\n"}
```

Using the C SDK with H265 and the JS test page as the viewer.

What you're saying makes sense the hash table is expecting a UINT64 to write into / read from and it's only getting the 4 bytes which seems problematic, I want to see why I cannot reproduce.

**Comment by hassanctech** [comment] 2024-07-25 18:14
Can you please try this out:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/2033 ?

**Comment by Nomidia** [comment] 2024-07-26 05:37
> I print the address of payloadType and rtpMapValue:
> payloadType = 0xb6074298, rtpMapValue = 0xb6074294

On my device, the locations of payloadType and rtpMapValue are next to each other.

Problem can be solved if I merge #2033 .

**Comment by hassanctech** [comment] 2024-07-26 13:10
Yes, please try it and confirm!

**Comment by hassanctech** [comment] 2024-07-26 23:10
Fix has been merged.

**Closed by hassanctech** 2024-07-26 23:10 UTC
Labels: bug, needs-triage, v1.10.2

**Comment by xiangxud** [comment] 2025-12-10 15:36
SessionDescription.c file seam fixed as follow PCHAR UINT64 convert rtpmap max value 4294967295 in 32bit cpu system

} else if (pRtcMediaStreamTrack->codec == RTC_CODEC_UNKNOWN) {
        UINT64 rtpMapValueAddr;
        CHK_STATUS(hashTableGet(pUnknownCodecRtpmapTable, unknownCodecHashTableKey, (PUINT64) &rtpMapValueAddr));
        rtpMapValue = (PCHAR)(uintptr_t)rtpMapValueAddr;
        STRCPY(pSdpMediaDescription->sdpAttributes[attributeCount].attributeName, "rtpmap");
        amountWritten =
            SNPRINTF(pSdpMediaDescription->sdpAttributes[attributeCount].attributeValue,
                     SIZEOF(pSdpMediaDescription->sdpAttributes[attributeCount].attributeValue), "%" PRId64 " %s", payloadType, rtpMapValue);
        CHK_ERR(amountWritten > 0, STATUS_INTERNAL_ERROR, "Full Unknown rtpmap could not be written");
        attributeCount++;
    }
