### ISSUE TITLE
[BUG] Race condition of `signalingClientHandle` in the sample code

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#801] opened 2020-09-16 14:38 UTC
Hi experts,

In the sample code, `signalingClientHandle` is freed and recreated at https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L904
`recreateSignalingClient` is atomic, however is it possible  that `signalingClientHandle` is accessed by multiple threads?

Not very familiar with the implementation of signaling state machine, couldn't get confident answer by myself, any help is appreciated!

Thank you.

**Comment by staowyze** [comment] 2020-09-16 22:58
@MushMal what do you think?

**Comment by MushMal** [comment] 2020-09-16 23:11
@staowyze there is indeed a chance of a race condition as we are not interlocking. The race could happen when we receive a message (either trickle ICE candidate or an offer for example) - this is handled on a separate thread that's created within the signaling client. The race could happen if we are still within the thread handling the message and an error gets triggered by the signaling (either due to ICE refresh failure or reconnect failure) and we execute the free call before the message thread terminates.

While this is not possible to hit in practice due to the retry logic in the signaling client, it's still possible to hit this in an odd timing case when the signaling client is configured with no retry or no reconnect.

This should be properly addressed in the samples.

I am changing the title and the label to BUG. Thanks for reporting.

**Comment by staowyze** [comment] 2020-09-16 23:26
Thanks for confirming @MushMal ! Could you please elaborate why it is not possible to hit in practice due to the retry logic in the signaling client?
My metrics show there are crashes on our devices, especially when they are in trouble to reconnect signaling channel, i am wondering is it possible that, ICE refreshing could hit the race condition?

**Comment by MushMal** [comment] 2020-09-16 23:34
It is possible to hit race condition even with the retries in refreshing ICE config. This said, I would recommend capturing the crash stack to ensure it's not something else that's crashing.

We will prioritize the fix for this

**Comment by staowyze** [comment] 2020-09-16 23:42
thank you! this is the top issue I have seen on my devices.

**Comment by staowyze** [comment] 2020-09-18 20:20
@MushMal any updates on this?

**Comment by MushMal** [comment] 2020-09-18 20:23
Sorry, nothing yet. We will update as soon as we have something

**Comment by MushMal** [comment] 2020-09-20 03:34
Just had a chance to look into this. I believe the crashes you were seeing are related to the NULL deref. There is also the race condition that's been fixed in this PR: #810 - please take a look. We will get this through and push this into master branch ASAP.

**Comment by staowyze** [comment] 2020-09-21 17:05
yeah, the NULL deref is part of the cause of crashes, I have deployed the NULL deref fix, but still see crashes with the following logs
```
[09-19 10:42:58][2020-08-19 02:42:58] [KVS]freeSignalingClient(): Freeing Signaling Client
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]createSignalingClientSync(): Creating Signaling Client Sync
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000001, Next state: 0x0000000000000002
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000004
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000010
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000040
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]signalingClientConnectSync(): Signaling Client Connect Sync
[09-19 10:42:59][2020-08-19 02:42:59] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000080
```
I am not able to collect crash dump from devices due to infra limits.
I will take a look at #810, thank you!

**Comment by staowyze** [comment] 2020-09-21 17:11
#810 is not related to my crashes, since all the crashes happened without active sessions, i.e. no offer, answer, etc.
I suspect it's related to signaling client recreation, as I always see logs about recreating signaling client just before the crash.

**Comment by MushMal** [comment] 2020-09-21 17:36
@staowyze we will need a little more info about the crash to repro or at least have some theories. As such, it's unactionable

**Comment by staowyze** [comment] 2020-09-21 19:15
is #810 going to fix the race condition of `signalingClientHandle`? @MushMal

**Comment by MushMal** [comment] 2020-09-21 19:18
Yes, it contains the fix for the NULL deref (which I believe would be the root cause for the crash) and a fix for a race. We have a lock that controls the access.

**Comment by staowyze** [comment] 2020-09-21 19:29
would it possible some background thread is still using `signalingClientHandle` while it's been freed by `freeSignalingClient`? Just curious, not sure it's another race.

**Comment by MushMal** [comment] 2020-09-21 19:30
Not in the sample. Please make sure if you modify the sample, then you need to do the same interlocking. 

pSampleConfiguration->sampleConfigurationObjLock

**Comment by MushMal** [comment] 2020-09-22 01:13
Resolving this issue as the original issue has been addressed. Please cut a new issue once you update the codebase and get the debug crash stacks

**Closed by MushMal** 2020-09-22 01:13 UTC
Labels: bug
