### ISSUE TITLE
[BUG] Memory leak in function signalingMessageReceived

### ISSUE THREAD

**Issue by GuoGuangya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1784] opened 2023-08-24 08:20 UTC
### in the file samples/Common.c

If this statement in case SIGNALING_MESSAGE_TYPE_OFFER
pSampleConfiguration->sampleStreamingSessionList[pSampleConfiguration->streamingSessionCount++] = pSampleStreamingSession
an error occurred later，the clean up, not free pSampleStreamingSession, and streamingSessionCount not --

Is this a bug?

**Comment by niyatim23** [comment] 2023-09-13 17:13
Hi @GuoGuangya, this is not a bug. The streamingSession is not cleaned up because it is a possibility that the incoming offer was not accepted but there could be future offers in that particular session that may be. The session is cleaned up every time on a disconnection in `sessionCleanupWait`:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/15e60193456709a3786f7c0f237c49ea7bd9c81f/samples/Common.c#L1254

Closing assuming answered

**Closed by niyatim23** 2023-09-13 17:13 UTC
Labels: bug, needs-triage
