### ISSUE TITLE
[QUESTION] Viewer play-stop-play will have error happen

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#773] opened 2020-09-04 08:39 UTC
A one liner description about the use case and what you are trying to achieve
When client's app for live video play will have such problem happen.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **
![image](https://user-images.githubusercontent.com/58592084/92219035-93e1a880-eecc-11ea-8604-7f9af0a55ab7.png)

**Comment by disa6302** [comment] 2020-09-04 16:31
@henryChmn , 

It is not clear from your description what happens. About **status code** `0x5d00002b`, it means that the signaling client has received a message that already exists in the queue and all it does is ignore the message to be queued. So, it shouldn't cause any problem. 

About 0x40100001, it means that the hash table cannot find the key passed in as part of hashTable calls. From the logs, my hunch is, the error is returned from this [line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/a7da1e06166ca2931c626b11e24f4bb2c05d4a0f/src/source/Ice/IceAgent.c#L2433). Nevertheless, it should not have any catastrophic effect. 

Can you provide more clarity on what the issue is?

**Comment by henryChmn** [comment] 2020-09-09 11:25
I have some logs for this question,
The problem happen when continues start viewer  and stop viewer, not sure what happen.

[teraterm_aws_client_fault.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5194760/teraterm_aws_client_fault.txt)
[teraterm_aws_client_sdk_malloc.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5194762/teraterm_aws_client_sdk_malloc.txt)
[teraterm_aws_client_sdk_malloc_2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5194763/teraterm_aws_client_sdk_malloc_2.txt)

**Comment by MushMal** [comment] 2020-09-09 17:00
@henryChmn the description of the issue is unclear. Do you mind perhaps rephrasing the question? What's the asset you are using? Which sample? I took a quick look at the attached logs which have a lot of spew in them which makes it unusable. However, I see there is a usage of KVS streams and not WebRTC.

As is, this is unactionable.

**Comment by MushMal** [comment] 2020-09-16 07:14
Resolving due to staleness. Please re-open with more detailed info

**Closed by MushMal** 2020-09-16 07:14 UTC
Labels: question
