### ISSUE TITLE
failed to connect webrtc with amazon ehcoshow.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#369] opened 2020-04-21 08:46 UTC
@chehefen Here are the logs we discussed today.
These logs are provided by @juno52wendy. 
Case#1: connecting kvsWebClientMaster(in Shenzhen) with echoshow(in Shenzhen), and it barely works. It looks like the sdp negotiation failed.
[3)----webrtclog.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4508731/3.----webrtclog.txt)
[3)----webrtlog3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4508732/3.----webrtlog3.txt)

Case#2: connecting kvsWebClientMaster(in Ohio EC2) with echoshow(in Shenzhen), and it barely works. It looks like the the process of stun failed but sdp negotiation succeed.
[4)----ec2-webrtc-linux-demp.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4508749/4.----ec2-webrtc-linux-demp.txt)

Case#3: connecting web test page(in Shenzhen) with echoshow(in Shenzhen), and it sometimes works. The success rate is around 10%~20%.
[5)----kvs webrtc page.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4508759/5.----kvs.webrtc.page.txt)

Not sure what happens, but the connection between Ring and echoshow works well.
[ring_webrtc.pcapng.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4508761/ring_webrtc.pcapng.zip)

**Comment by ycyang1229** [comment] 2020-04-21 08:50
3)----webrtlog3.txt
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000021
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 VERBOSE turnConnectionSendData(): TurnConnection not ready to send data
2020-04-13 09:30:19 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000021
2020-04-13 09:30:19 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000100
2020-04-13 09:30:19 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a000013
2020-04-13 09:30:19 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_FAILED.
2020-04-13 09:30:19 INFO    onConnectionStateChange(): New connection state 5
2020-04-13 09:30:19 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:19 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: D8SN5XYIL8 
2020-04-13 09:30:19 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000021
2020-04-13 09:30:21 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-13 09:30:21 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-13 09:30:21 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-13 09:30:28 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:31 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-13 09:30:31 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-13 09:30:31 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-13 09:30:33 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:38 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:41 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-13 09:30:41 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-13 09:30:41 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-13 09:30:43 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:48 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-13 09:30:51 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-13 09:30:51 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-13 09:30:51 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-13 09:30:53 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
^C2020-04-13 09:30:53 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
[KVS Master] Streaming session terminated
[KVS Master] Cleaning up....
2020-04-13 09:30:53 INFO    freeSignalingClient(): Freeing Signaling Client
2020-04-13 09:30:53 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 71
2020-04-13 09:30:53 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 71
2020-04-13 09:30:53 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-13 09:30:53 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 75
2020-04-13 09:30:53 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 30
2020-04-13 09:30:53 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 28
2020-04-13 09:30:53 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 28
[KVS Master] Cleanup done
# 


4)----ec2-webrtc-linux-demp.txt
2020-04-15 09:24:00 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 71
2020-04-15 09:24:00 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:00 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:00 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
2020-04-15 09:24:00 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
2020-04-15 09:24:00 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer 3.94.105.122
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer 3.94.105.122
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer 3.94.105.122
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer 3.94.105.122
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 8
2020-04-15 09:24:00 DEBUG   lwsWssCallbackRoutine(): Client receive 
2020-04-15 09:24:00 WARN    receiveLwsMessage(): Signaling received an empty message
2020-04-15 09:24:00 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:00 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:54876
2020-04-15 09:24:00 VERBOSE turnConnectionSendData(): Unable to send data through turn because turn channel is not established with peer with address 3.94.105.122:63203
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.94.105.122, port: 63203, channel number 16385
2020-04-15 09:24:00 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.94.105.122, port: 54876, channel number 16386
2020-04-15 09:24:01 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_BIND_CHANNEL
2020-04-15 09:24:01 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY
2020-04-15 09:24:05 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:08 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000008, Next state: 0x0000000000000040
2020-04-15 09:24:08 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a000013
2020-04-15 09:24:08 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_FAILED.
2020-04-15 09:24:08 INFO    onConnectionStateChange(): New connection state 5
2020-04-15 09:24:08 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:08 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: 024dc0c9-38b6 
2020-04-15 09:24:08 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_READY to TURN_STATE_CLEAN_UP
2020-04-15 09:24:10 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:10 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:10 DEBUG   turnConnectionHandleStun(): TURN Allocation freed.
2020-04-15 09:24:10 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:24:16 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:20 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:20 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:20 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:24:21 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:26 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:30 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:30 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:30 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:24:31 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:36 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:40 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:40 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:40 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:24:41 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:46 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:50 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:24:50 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:24:51 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:24:51 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:24:56 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:25:01 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:25:01 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-04-15 09:25:01 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:25:01 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-04-15 09:25:06 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:25:11 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-04-15 09:25:11 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-04-15 09:25:11 DEBUG   lwsWssCallbackRoutine(): Client is writable

**Comment by suggestedfixes** [comment] 2020-04-21 16:12
I can make a couple of comments since I worked on a similar thing.
- Make sure you disable trickle ice. It's the first TRUE/FALSE argument in createSampleConfiguration.
- For your Lambda, make sure you turn on provisioned concurrent instances and set your lambda timeout to around 60 seconds.
- For your Lambda, it helps to write it in python/golang/c++ to reduce the cold start that will cause a timeout (Echo show has a hard coded timeout of 6 seconds). Setting up a provisioned concurrency will reduce cold startup time.
- Make sure your Lambda region is as close as to your device as possible, it helps to create an EC2 instance in the same region as Lambda to simulate your device. Then gradually optimize timeouts
- Pregenerate certificates, see instructions in README
- Reduce the number of generated DTLS bits to 1024 instead of 2048

**Comment by suggestedfixes** [comment] 2020-04-21 16:42
I can make a couple of comments since I worked on a similar thing.
### Device Settings
- Make sure you disable trickle ice. It's the first TRUE/FALSE argument in createSampleConfiguration.
- Pre-generate certificates, see instructions in README
- Reduce the number of generated DTLS bits to 1024 instead of 2048

**Comment by chehefen** [comment] 2020-04-22 01:46
I see that turn is enabled in your log. You dont need TURN in order to connect with alexa, not event STUN. Also you need to disable trickle ice. You can do it by setting the follow two parameters to FALSE:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L20-L21

Then comment out this line:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L323

**Comment by juno52wendy** [comment] 2020-04-22 02:07
@chehefen  @suggestedfixes    
The advice you gave me was handled in the code a long time ago, but it has no practical effect.
One more thing, the code for stun / turn / ice has been implemented, the theory is familiar, and the code for kvs is also familiar!

**Comment by lingdhox** [comment] 2020-04-22 08:00
Alexa doesn't need stun/turn. and it needs to disable trickle ice.
In particular, it is important to control the time.
The time from lambda receiving offer to device returning answer should be limited to 6 seconds.  
Some things will make the process timeout, such as the generation of dtls or the network is too slow
PS: The network from China to Alexa is terrible

**Comment by juno52wendy** [comment] 2020-04-22 08:14
@lingdhox 
1. Alexa can communicate successfully without using stun or turn. For example, Amazon's own doorbell product Ring can be achieved by capturing the package by sip / sdp / rtp. The experience in China is also good. The audio and video delay is about 1s. , Intercom is also very good.
2. The network in China is not so bad. The network in European countries is worse than that in China. This is what our actual product users get.
3. We have a vpn dedicated line to Hong Kong, including lambda, kvsserver, region = ap-east-1, so the network is not an absolute factor of impact, the product must consider various scenarios and applications, stun, turn packet punching interaction must also be available Yes, but for now, it is not mature, for productization.

**Comment by lingdhox** [comment] 2020-04-22 08:33
@juno52wendy 
I think the discussion on this page covers all the key points. You may need to recheck carefully. 
en. Maybe you can test the connectivity with the web (simulating the Alexa server) first, which can verify that the native code you modified is correct

**Comment by juno52wendy** [comment] 2020-04-22 08:40
@lingdhox  
The demos are up-to-date, and the revised points have been revised. Except for using js viewer and echoshow once, and never again, at least c sdk is like this. SDK authentication is currently 2-3s time-consuming, as long as the sdp exchange is successful , Alexa will not quit in 6s, will make further holes, this process will take a while to time out, if not successful, lambda, c sdk and Amazon technical support have been checked.
PS: Amazon technical support has not been tested successfully in China!

**Comment by suggestedfixes** [comment] 2020-04-22 19:41
I wasn't sure if you were using Lambda. Here are some Lambda optimizing techniques:
- Turn on provisisoned concurrency to minimze probability of a cold start, this could get expensive (Java cold start could be as long as 40s to spin up)
- Increase Lambda timeout.
- If necessary, rewrite your lambda in Python/Golang/C++, those have very fast cold startup time.

**Comment by suggestedfixes** [comment] 2020-04-22 19:48
This also relates to low turn success rate, I think. One of the previous commits back in February might have worked better.

**Comment by juno52wendy** [comment] 2020-04-23 01:27
@suggestedfixes 
The Python / go used by lambda has been written, and the lambda is also provided by the Amazon technical team, and the code has been confirmed with each other!
I don't think it has much to do with the lambda and server region. They are all configured to the nearest node according to the requirements. There are also dedicated line VPNs, so there is no problem.
So it has a great relationship with the high failure rate of turn.

**Comment by MushMal** [comment] 2020-05-21 04:59
@juno52wendy Can I ask folks to summarize what the latest is on this issue? I wouldn't want this to go stale and close the issue due to staleness.

**Comment by sharadrj** [comment] 2020-05-22 15:52
Echo show connectivity should be much improved with the changes we have made in last 2-3 weeks. We are soon going to publish an Integration guide with Alexa, and push reference lambda code on github.

**Comment by chehefen** [comment] 2020-06-04 21:02
closing the issue as connection with echo show should be fine after release https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/v1.1.0

**Closed by chehefen** 2020-06-04 21:02 UTC
Labels: ICE/Connectivity

**Comment by pai-da-xin** [comment] 2020-08-21 07:46
@ycyang1229 Hi,Sir,how do you connect kvsWebClientMaster with Amazon echo show.
