### ISSUE TITLE
TurnConnection shutdown did not complete within 1 seconds

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1049] opened 2021-01-19 08:10 UTC
Hi, Experts,
After I successfully exchanged the offer and answer, TURN Allocation succeeded and create permission succeeded. TurnConnection state changed to TURN_STATE_READY. 
But now the function [executeFailedIceAgentState](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgentStateMachine.c#L637) displays an error: IceAgent failed with 0x5a00000d. Then Ice agent state changed to ICE_AGENT_STATE_FAILED, TurnConnection state changed from TURN_STATE_READY to TURN_STATE_CLEAN_UP. And function [iceAgentShutdown](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L713) displays: TurnConnection shutdown did not complete within 1 seconds.
How to solve this problem?

**Comment by MushMal** [comment] 2021-01-19 15:56
It’s not clear what could cause this. A simple explanation might be a network issue so you might need to debug this further. You might also want to include a lot more details about your scenario, platform, debug logs, etc.
As is, this issue is not actionable.

**Comment by pai-da-xin** [comment] 2021-01-20 02:08
I use [send_alexa_offer_to_master](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesis-video-signaling.html#KinesisVideoSignalingChannels.Client.send_alexa_offer_to_master) API and [SendAlexaOfferToMaster](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_AWSAcuitySignalingService_SendAlexaOfferToMaster.html) API, they are implemented in different ways. I've tried both ways. I can send an offer to the master, but I can't get an answer. I'm just saying that I'm using this API, If you have any help, I would appreciate.

**Comment by MushMal** [comment] 2021-01-20 02:12
Shutdown sequence shouldn’t make any difference whether you are using Alexa offer or going directly from a viewer app.

**Comment by pai-da-xin** [comment] 2021-01-20 03:20
I use echo show to send an offer, I found that the offer didn't use Base64 encoding, Send offer directly in plaintext. So the answer sent by the master should not be encoded, echo show and master cannot establish a P2P connection， Will it be caused by this reason.

**Comment by MushMal** [comment] 2021-01-20 04:31
Signaling message should be base64 encoded. I am not sure what you are seeing but Alexa API should also use base64 encoding.

I would suggest to focus on the original question about the shutdown sequence and not diverge.

Please cut a separate issue with the base64 encoding and inability to establish a connection or whatever you are observing. However, in order to get some action from the service team, you will need to do a LOT more debugging on your end and provide a LOT more details with VERBOSE logs.

**Comment by pai-da-xin** [comment] 2021-01-20 09:26
It should be because echo show did not receive an answer from the master, So the establishment of connection between echo show and master failed. Error "TurnConnection shutdown did not complete within 1 seconds" occurred.

**Comment by MushMal** [comment] 2021-01-20 20:54
@pai-da-xin at this stage I am absolutely not sure what the issue is and what we are discussing. I am not sure where the Base64 issue or signaling comes from. The original question is about the turn termination sequence I believe but you've provided no details and no logs.

I am resolving this issue.

Please cut a new issue with detailed description of the issue including verbose logs.

**Closed by MushMal** 2021-01-20 20:54 UTC
Labels: awaiting response, question
