### ISSUE TITLE
Change printf in samples to DLOGx 

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#142] opened 2020-01-13 22:46 UTC

**Comment by Sean-Der** [comment] 2020-01-13 23:42
@MushMal I forget where this feedback came from, but we were asked to remove any KVS-isms from our public samples.

It might be easier for developers learning/reading if we just use 'Pure C' in our public samples, but keep everything KVS internal.

**Comment by MushMal** [comment] 2020-01-13 23:45
I am fine either way - just not the mix of all of them.

1) DLOGx - PIC
2) LOG_DEBUG - C++
3) gstreamer log
4) printf

We can use just one of them but having a mix seems to be bad

**Comment by Sean-Der** [comment] 2020-01-16 06:58
Closing as dupe of #124

**Closed by Sean-Der** 2020-01-16 06:58 UTC
