### ISSUE TITLE
[QUESTION] Kinesis Video Streams with WebRTC browser stops displaying new frames when using TURN with large frame sizes

### ISSUE THREAD

**Issue by plt-joey** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1719] opened 2023-05-24 21:16 UTC
I am working on a project that requires sending very large video (about 400KB per frame) at 1fps in as close to real time as possible from a server to one or more web clients. I was able to modify the C SDK sample master to send the video with an acceptable latency to a browser viewer, but am running into a strange issue specifically when using TURN;

After 181 frames the video feed stops displaying new frames.

- According to `nettop` and `chrome://webrtc-internals/` the viewer is still receiving the new frames, as the bytes-in continues to rise at the same rate until either the viewer or server is stopped, but the web browser stops displaying them. This was tested with both Google Chrome and Firefox, on both the JS SDK sample and the AWS console video viewer with the same result.
- The number of frames it displays does not seem to be affected by the frame rate, length of the video, or elapsed time. However it does seem to be affected by the size of the frames. If I use a more compressed version of the video (approx. 150KB per frame) the number changes from 181 frames to 505 frames. It does not stop at a consistent total size though, the 181 frame test totals 74.4MB and the 505 frame test totals 83MB.
- The issue seems to stop occurring if the frame size is reduced to at or below 100KB on average (in the case of my test video that happens around CRF 28), at which point the quality stops being ideal for our use case
- This shouldn't be an issue of going over the 5Mbps TURN server quota, as I am only hitting at most 3Mbps.
- I also can't find any information about the TURN server having a frame size limitation
- Disabling NAT traversal and just running the test localhost to localhost causes the issue to disappear, and I am unable to find a consistent setup to test this with STUN.
- I get no error messages from either end in these tests
- The videos are h.264 encoded using ffmpeg (CRF 15 ultrafast, yuv 4:2:0) with no audio

Here is some `webrtc-internals` data from a different run that got 300 frames in:
![Pasted image 20230524141420](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/66274832/92953d24-f2db-4f28-a9f2-20f4c6c2aab6)
In this graph frames received / decoded per second is the red and bytes received per second is the blue line, you can see that the channel is still receiving data, it just stops decoding it.

and here:
![Pasted image 20230524141444](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/66274832/8f01691b-b00e-45bc-ac1f-18a6b3fecb80)
In this graph frames received / decoded per second is the red, packets received per second is the yellow line and total packets lost is the purple line. The total number of lost packets steadily increases after the video stops, but it does not come close to the number of packets still coming in per second.

This can be repro'd with only a couple simple changes to the master (just changes necessary to point it to a new video):
- `NUMBER_OF_H264_FRAME_FILES` in `Samples.h` changed to `67`, the length of my test video
- `DEFAULT_FPS_VALUE` in `Samples.h` changed to `1`
- `SAMPLE_STATS_DURATION` in `Samples.h` changed to `((NUMBER_OF_H264_FRAME_FILES / DEFAULT_FPS_VALUE) * HUNDREDS_OF_NANOS_IN_A_SECOND)`
- `encoderStats.width` on line `262` of `kvsWebRTCClientMaster.c` set to `1024`
- `encoderStats.height` on line `263` of `kvsWebRTCClientMaster.c` set to `1024`
- `encoderStats.targetBitrate` on line `264` of `kvsWebRTCClientMaster.c` set to `4000000` or 4 Mbps
- A sample video with frame sizes around 400KB each

The test video is created from a set of images with the following two ffmpeg commands from a small set of images
```
ffmpeg -y -loglevel error -hide_banner -f image2 -i "input/frame-%04d.png" -profile:v baseline -c:v libx264 -crf 15 -preset ultrafast -pix_fmt yuv420p "output-full.h264"
ffmpeg -y -loglevel error -hide_banner -i "output-full.h264" -f image2 -vcodec copy -r 1 "output/frame-%04d.h264"
```

I am at a bit of a loss as to how to even debug this issue further. Can anyone provide either a suggestion as to why this might be happening, or other steps I can take to further diagnose this issue?

**Comment by niyatim23** [comment] 2023-06-08 21:17
Hi @plt-joey, there is no limit on the frame size from the TURN server as these are sent as RTP packets and frames are broken down into smaller packets before they reach the TURN server. Please share a sample video that you're trying to upload for us to investigate this

**Comment by plt-joey** [comment] 2023-06-09 12:40
Hello, The AWS support team have passed along the repro sample I gave to them, which stops after about 134 frames.

**Comment by niyatim23** [comment] 2023-06-11 05:01
Hi @plt-joey, I tried reproducing the issue with the frames shared. I was not able to reproduce the issue with release 1.7.3 with the changes from your post. Can you double check your network and see if you're consistently able to reproduce this? I tested with Chrome (Version 114.0.5735.106 (Official Build) (x86_64)) and Firefox (113.0 (64-bit)) on MacOS.

**Comment by plt-joey** [comment] 2023-06-12 19:04
I have done a bunch of testing across several other computers and have come to the realization that this issue happens very inconsistently, but still frequently, on most machines. I just got lucky that it is very consistent on the specific machine in the specific environment I was testing it in (windows WSL running Ubuntu 20.04). I have been able to test it on multiple networks as well and that doesn't seem to have any affect. The web browser also seems to have little to no affect.

A couple of things that I found that seem to increase the frequency of the issue occurring:
1. Running the master in Windows WSL Ubuntu 20.04 (it still seems to happen in 22.04, but it is much more frequent in 20.04)
2. having the web client be connected to a VPN (or otherwise adverse network conditions)

I have not been able to get the master to compile on my M1 Mac, or in Windows itself, so I haven't been able to test it outside of Windows WSL.

I am still looking for a way to consistently reproduce it on any machine.

**Comment by disa6302** [comment] 2023-06-13 00:02
@plt-joey , 

Trying to find out if it is TURN specific, but do you see this issue when the two peers are on the same network? Looking for host candidates being selected for media transfer.

**Comment by plt-joey** [comment] 2023-06-13 00:12
I have only been able to reproduce this issue when going between machines
on a different network (usually via a VPN), or when using "force TURN" in
the JavaScript sample viewer.

**Comment by disa6302** [comment] 2023-06-13 00:22
Any reason you are forcing TURN though?

**Comment by plt-joey** [comment] 2023-06-13 00:43
I am only forcing TURN to reproduce the issue, when running localhost to
localhost without forcing TURN I have not seen the issue. Localhost to
localhost is the only way I have been able to reliability force a non-TURN
connection, machines I test on the same network end up connecting via TURN
anyways even if I don't force it, forcing TURN just makes things more
consistent.

**Comment by plt-joey** [comment] 2023-06-15 23:09
To run the provided .tar file for the docker container

1. `docker load -i kvs-turn-frame-bug-test.tar`
2. `docker run --detach -e AWS_ACCESS_KEY_ID=<access_key> -e AWS_SECRET_ACCESS_KEY=<secret_key> -e AWS_DEFAULT_REGION=us-east-2 kvs-turn-frame-bug-test`

it will create a channel called `test_channel` on the account provided, and will start streaming when a viewer connects.

**Comment by niyatim23** [comment] 2023-06-15 23:09
As discussed on the call, this is what we use for generating our sample h264 videos:
GStreamer Pipeline to reproduce sample frames
```sh
-gst-launch-1.0 videotestsrc pattern=ball num-buffers=1500 ! timeoverlay ! videoconvert ! video/x-raw,format=I420,width=1280,height=720,framerate=25/1 ! queue ! x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! multifilesink location="frame-%04d.h264" index=1
```
-Note: since the fps is 25, we need 1500 frames to create a 60 seconds video

**Comment by niyatim23** [comment] 2023-06-20 05:27
Hi @plt-joey, did you run into any issues while building the `master` on AMI `al2023-ami-2023.0.20230614.0-kernel-6.1-x86_64`? Can you please try using `develop` branch and see if you run into the any issues with that? Please be sure to wipe the build clean with `git clean -ffxd` from repository root and rebuilding before trying.

**Comment by plt-joey** [comment] 2023-06-20 12:12
@niyatim23 I didn't compile it directly on the EC2 instance for my test, I used the docker container

**Comment by niyatim23** [comment] 2023-06-22 16:36
Hi @plt-joey, following are the action items for your team from yesterday's discussion:
1. Run the KVS [Producer C SDK](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c) sample with your sample frames and see if it fits your use case. You can use [this](https://aws-samples.github.io/amazon-kinesis-video-streams-media-viewer/) webpage to use HLS to view the media.
2. Try using [this](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) viewer page with the same options as attached in the image below.
<img width="1194" alt="KVS's browser options" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/27426488/ef3a3b5e-7532-4be6-b82e-dcca9d30c775">

3. Investigate / Profile how much memory / resources is the tab running the viewer using in the browser and if there are any limitations enforced by the browsers on your setup by default

**Comment by plt-joey** [comment] 2023-06-23 17:55
I shared the original sample video as per our discussion. The command I used to create png frames from the original sample video is: `ffmpeg -y -loglevel error -hide_banner -i sample_video.mp4 -f image2 "input/frame%04d.png"`

if I recall correctly, when I re-encoded it to h264 I used `-crf 20`, otherwise the command to convert back to h264 is the same.

**Comment by unicornss** [comment] 2023-06-23 20:34
`ffmpeg -y -loglevel error -hide_banner -i sample_video.mp4 -f image2 "input/frame-%04d.png"`
to match the h264 commands posted earlier in this thread.

**Comment by niyatim23** [comment] 2023-06-28 17:04
Hi @plt-joey, we recommend you use a smaller GOP size since the frames are large and if two I-frames are far apart, it would need a larger buffer which could have been causing the issues with the viewer:
```
ffmpeg -y -loglevel error -hide_banner -f image2 -i "test/frame%04d.png" -profile:v baseline -c:v libx264 -x264-params keyint=5:scenecut=0 -bf 0 -crf 15 -preset ultrafast -pix_fmt yuv420p "output-full.h264"
ffmpeg -y -loglevel error -hide_banner -i "output-full.h264" -f image2 -vcodec copy -r 1 "webrtc/frame-0%03d.h264"
```
Can you please check if the video generated this way works?

**Comment by unicornss** [comment] 2023-06-28 17:29
As Niyati mentioned please try with smaller GOPs  (1 or 2) - because we noticed that the default was using high number of frames GOP 
```
ffmpeg -y -loglevel error -hide_banner -f image2 -i "input/frame%04d.png" -profile:v baseline -c:v libx264 -x264-params keyint=2:scenecut=0:bf=0 -crf 15 -preset ultrafast -pix_fmt yuv420p "output-full.h264"
10048  ffmpeg -y -loglevel error -hide_banner -i "output-full.h264" -f image2 -vcodec copy -r 1 "output/frame-%03d.h264"
```

**Comment by plt-joey** [comment] 2023-06-28 17:38
I discovered this is also recommended in the ffmpeg documentation yesterday. I tested with a similar setup setting the `keyint=1` (I used the `-g 1` argument, but it is effectively the same thing) and it worked. I was unable to reproduce the issue with this setting. In fact we were even able to stream between Canada and Australia very smoothly with this setup.

Given this result we wanted to figure out why your team didn't see the same issue using the same source and files, just to confirm we aren't barking up the wrong tree. My suspicion is that using TURN from here created network conditions _just_ adverse enough to drop a handful of packets, and the viewer couldn't cope with both the large buffer size and the error correction at the same time.

Would you be able to test running the sample I gave in more adverse network conditions to try and replicate it? maybe try it with a channel in a further away region to connect through a further away TURN server?

**Comment by niyatim23** [comment] 2023-07-07 20:25
Hi, I changed the network conditions on the viewer by throttling the network (Slow 3g) with Chrome with your docker container as master and I did not see any issues with the video

**Comment by plt-joey** [comment] 2023-07-17 12:10
commenting to keep this open until we can have a meeting again

**Comment by disa6302** [comment] 2023-07-24 15:53
Closing this issue based on offline discussions. Feel free to reopen if there is anything to report.

**Closed by disa6302** 2023-07-24 15:53 UTC
Labels: question, pending-action, needs-triage
