### ISSUE TITLE
Missing partial-reliability option for data channel

### ISSUE THREAD

**Issue by enobufs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#364] opened 2020-04-20 07:37 UTC
I have just noticed that this library [ignores RtcDataChannelInit](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/d69dca161241e62e67b2c68ad274119529309932/src/source/PeerConnection/DataChannel.c#L12) passed to createDataChannel() method. :(

Would initiating a data channel with a partial reliability option become available any time soon?

**Comment by disa6302** [comment] 2020-04-30 18:42
@enobufs ,

Can you explain what you mean by partial reliability? And what your use case is?

**Comment by enobufs** [comment] 2020-04-30 19:37
You can learn what WebRTC DataChannel offers re reliability options with these links:

* https://www.w3.org/TR/webrtc/#methods-11
* https://www.html5rocks.com/en/tutorials/webrtc/datachannels/
* https://tools.ietf.org/html/rfc3758

Over a lossy connection, WebRTC data channel may keep retransmitting lost packets, which would cause large latency with a head-of-line blocking.  Partial reliability option would help you reducing such head-of-line blocking (by giving up the retransmissions with certain conditions you specify) to deliver subsequent packets with less delay.

**Comment by disa6302** [comment] 2020-04-30 21:47
@enobufs ,

Providing the partial reliability option was not in the plan, but I do not see why not! Adding it should not be difficult. I will keep this ticket open to track this feature request.

**Comment by disa6302** [comment] 2020-05-07 21:13
@enobufs 

The change is in :D
Let us know if you face any issues with it.

**Comment by zhiyua-git** [comment] 2020-05-10 05:23
Partial-reliability option for data channel is provided in latest master branch. Closing the issue and feel free to open new issue when you try out the function.

**Comment by enobufs** [comment] 2020-05-11 08:51
@disa6302 @zhiyua-git The changes you made passes the settings to the remote using DCEP, but it does not seem to write up the settings to usrsctp at all.

> Partial-reliability option for data channel is provided in latest master branch.

What are your criteria for concluding that the new feature was provided? May I expect the feature was tested?

Also, there are couple of questions:

## Enable unreliable transfer with maxRetransmits set to 0.
In WebRTC API (JavaScript), if dc.maxRetransmits is set to null, it would do the normal reliable transfer. If it is set to 0, it would do up to 0 retransmission (no retransmission). But your change does not allow the application to configure "no-retransmission" because you take the value 0 to be "reliable" (normal) ops.

## How can the remote node would know what partial-reliability options were used?
The partial reliability options (maxRetransmits, maxPacketLifeTime, order) are communicated to the peer using DCEP, but I do not see the API that allow for the remote node to learn what settings were used for a new data channel.

See: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel

Currently, RtcDataChannel only exposes "name" (the label). Application will need:
* ordered
* maxRetransmits
* maxPacketLifeTime

And again, you will need to invent a way to express in C for the cases where maxRetransmits and maxPacketLifeTime set to null for Javascript...

**Comment by disa6302** [comment] 2020-05-11 19:58
@enobufs , 

1. I just spun a unit test locally to see if the parameters get set appropriately in the DCEP call. I am unsure on how to do an end to end test for this feature. I think I know what the issue is and the flag I missed setting. Let me push a change for that into a branch and it would be great if you try it out locally to see if it works as expected.
2. Enable unreliable transfer with maxRetransmits set to 0 : Did not stumble upon this part of the spec. Let me look into it. My implementation was based on this: https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-09#section-5.1
3. Let me fix it. Thanks for pointing it out :) . Will be back with the changes ASAP.

**Comment by enobufs** [comment] 2020-05-11 21:29
Re 1, Google's libwebrtc does it in this file: https://webrtc.googlesource.com/src/+/refs/heads/master/media/sctp/sctp_transport.cc#169
(find: CreateSctpSendParams() method that creates params to actually send data with the partial-reliability parameters)

Of course, I will do test on my end for my app, but you will need to test it at the library level somehow otherwise you wouldn't be able to detect potential regression right? ;)

**Comment by disa6302** [comment] 2020-05-11 21:33
Ofcourse. We want to include some end to end tests for this at library level, but, just have not figured out a good way to do that.

**Comment by disa6302** [comment] 2020-06-02 22:43
@enobufs , 

Just wanted to update you. The logic is fixed and sitting in a branch. Working on the tests. Will update this ticket once the tests are in! Thanks!

**Comment by enobufs** [comment] 2020-06-03 01:02
That's good news! I hope it would solve #508 all together!

**Comment by enobufs** [comment] 2020-07-09 15:59
@disa6302 may I ask you if there was any progress on this?

**Comment by disa6302** [comment] 2020-07-09 16:04
@enobufs ,

I have a WIP PR for this. Will update once it is reviewed and merged.

**Comment by disa6302** [comment] 2020-07-17 20:48
@enobufs , 

Apologies for the delay. The changes are in this PR. 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/599

I have added unit test to verify the parameters that are being set. 

> How can the remote node would know what partial-reliability options were used?

About this, I will focus on this in a separate PR. Will add in the parameters in RtcDataChannel so that the information can be read by the application. Again, thank you for your patience while I get this done!

**Comment by disa6302** [comment] 2020-07-22 00:30
@enobufs , 

The changes are in. Let me know if you face any issues.

**Comment by sharadrj** [comment] 2020-08-08 22:12
Closing as the requested feature has been implemented. 

@enobufs, please reopen if needed.

**Closed by sharadrj** 2020-08-08 22:12 UTC
Labels: enhancement, ongoingwork
