### ISSUE TITLE
[QUESTION]  What is error STATUS_IOT_EXPIRATION_OCCURS_IN_PAST, 0x15000017?

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1136] opened 2021-05-05 19:26 UTC
We recently have seen an error multiple times in different environments.
createCredentialProvider function call fails error code 0x15000017. 
The error  is STATUS_IOT_EXPIRATION_OCCURS_IN_PAST.  What cause the failure?

**Comment by MushMal** [comment] 2021-05-05 19:45
This is the code piece that checks for the expiration: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/Common/Util.c#L51

What this means is that the expiration that was supplied to the credential provider happens in the past. If you have not modified the credential provider code then it's likely caused by the fact that your device clock has drifted forward. Check your device clock. Most solutions rely on some sort of NTP service tie-up at the boot time.

**Comment by disa6302** [comment] 2021-05-09 15:10
Assuming question is answered, closing

**Closed by disa6302** 2021-05-09 15:10 UTC
Labels: question
