### ISSUE TITLE
[QUESTION]createSampleConfiguration(): operation returned status code: 0x15000011

### ISSUE THREAD

**Issue by Zevolusion** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1180] opened 2021-06-21 03:55 UTC
I already follow [1] and [2], then [1] is working, but [2] got an error

2021-06-21 02:29:09 WARN    lwsIotCallbackRoutine(): Client connection failed. Connection error string: client connect failed
2021-06-21 02:29:09 VERBOSE lwsIotCallbackRoutine(): HTTPS callback with reason 30
[KVS Master] createSampleConfiguration(): operation returned status code: 0x15000011
[KVS Master] Terminated with status code 0x15000011[KVS Master] Cleaning up....
[KVS Master] Cleanup done

But when I use the script below with same credentials and config is working

AWS_ACCESS_KEY_ID=$(jq --raw-output '.credentials.accessKeyId' token.json) AWS_SECRET_ACCESS_KEY=$(jq --raw-output '.credentials.secretAccessKey' token.json) AWS_SESSION_TOKEN=$(jq --raw-output '.credentials.sessionToken' token.json) aws kinesisvideo describe-signaling-channel --channel-name kvs_camera_1

[1] https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-iot.html
[2] https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#setup-iot

**Comment by disa6302** [comment] 2021-06-23 05:41
@Zevolusion ,

Can you confirm the required environment variables are exported while using the script in the repository?

**Comment by Zevolusion** [comment] 2021-06-25 09:04
@disa6302 
I don't understand what u mean, I guess is that like below?

export AWS_IOT_CORE_THING_NAME=kvs_camera_1
export AWS_IOT_CORE_CREDENTIAL_ENDPOINT=xxx.credentials.iot.us-west-2.amazonaws.com
export AWS_IOT_CORE_CERT=/xxx/certificate.pem
export AWS_IOT_CORE_PRIVATE_KEY=/xxx/private.pem.key
export AWS_IOT_CORE_ROLE_ALIAS=KvsCameraIoTRoleAlias
export AWS_KVS_LOG_LEVEL=1

**Comment by juno52wendy** [comment] 2021-07-13 13:31
This is really a misunderstanding problem. The main reason is that the area where your network is located is too far away from the aws signaling server deployment or there is a firewall in the middle, causing https requests to often fail. It is recommended that you find the nearest network service or apply for ecs to the nearest Service experience is much better。

**Comment by disa6302** [comment] 2021-07-27 18:51
@Zevolusion ,

Are you still facing this issue? 

I meant it is possible the environment variables are getting set up correctly using the default script.

**Comment by Zevolusion** [comment] 2021-08-12 07:07
@LiuAriel 
I used the same region which is us-west-2 in my whole aws service.
And if that is what you said about the network problem, then how can my kvs is working find in [1]

**Comment by LiuAriel** [comment] 2021-08-12 07:31
@Zevolusion   You can set the region in the readme: RUN--export AWS_DEFAULT_REGION, but this region should be a region that can be deployed in your country. Otherwise, even if you set up a server close to your country, because there is Failure caused by firewall or network packet loss and other reasons is normal. You need to understand that no matter how many versions of the library are updated, the problem cannot be solved fundamentally.
It is for this reason that the link is as follows, you can refer to:
[https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1189](url)

**Comment by Zevolusion** [comment] 2021-08-12 08:19
When I use new version, it works perfectly, thanks much!

**Comment by disa6302** [comment] 2021-08-12 23:58
@Zevolusion ,

Closing since it is resolved.

**Closed by disa6302** 2021-08-12 23:58 UTC
Labels: question
