### ISSUE TITLE
[QUESTION] the  #1219 issue , I test , but is don't success

### ISSUE THREAD

**Issue by zz-svg** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1237] opened 2021-08-20 03:28 UTC
I use #1227 function test , But it did not quit , So I think this modification was unsuccessful.
![Uploading image.png…]()

**Comment by zz-svg** [comment] 2021-08-20 03:34
![image](https://user-images.githubusercontent.com/65853976/130175185-e718b879-417e-44e3-ac62-d3dfd317c3fc.png)

**Comment by disa6302** [comment] 2021-08-20 21:51
The logs do not display "Canceling media thread"?

**Comment by ycyang1229** [comment] 2021-08-22 12:43
I think you are using the pthread_cancel incorrectly, and the flag indicates the live time of media sender thread.
If you want to cancel the thread, you probably need to remove the "!" and put the pthread_cancel before pthread_join(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L466). And remember to take care of the pthread_tid.

**Comment by zz-svg** [comment] 2021-09-22 03:02
What I mean is that the APP is no longer watching videos, and the thread that sends audio and video is not closed, and audio and video data is still being sent.

**Comment by disa6302** [comment] 2021-09-23 19:58
There is a fix that was pushed. Closing now. 
Please reopen if the issue is not resolved.

**Closed by disa6302** 2021-09-23 19:58 UTC
Labels: pending-research
