### ISSUE TITLE
Bitrate of viewer video

### ISSUE THREAD

**Issue by Ben8823** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#918] opened 2020-11-03 16:58 UTC
How do I control/increase the bitrate of the return feed from the browser?

I'm using the SDK as a master to send a video stream and receive video streams from several browser viewers. The master's feed is held at a fixed configurable bitrate (ignoring the bandwidth estimation), which doesn't seem to influence things at all.
The browsers report an outgoing bitrate of around 300 kbps and their video looks appropriately bad. There's no code running in the browser that tries to adjust the bitrate or anything else for that matter.
If I use the KVS test page and run the master in a browser, I get an outgoing bitrate of about 2.3 Mbps from the viewer (also using the test page).
Both master and viewer are on the same local network, in both scenarios. The network is obviously able to support the high bitrate.
Since the bitrate is dynamically negotiated by the peers, it seems the SDK is limiting the viewer somewhere.

**Comment by MushMal** [comment] 2020-11-03 17:39
If you are referring to the master sample in the C SDK then it's using pre-packaged frames at a certain resolution/bitrate. If you are referring to the GStreamer application then you need to configure the encoder to produce the right bitrate for you.

The JS test page configures the default camera with the default settings. If you need more info please cut an issue against that repository. There are few params to control the bitrate I believe in browsers webrtc implementation.

The bitrate is not dynamically negotiated. The video parameters are negotiated. The rtsp protocol allows for certain SDP packets controlling the network congestion and we support some of them in the form of callbacks in the SDK. Check the w3c specification.

**Comment by Ben8823** [comment] 2020-11-03 17:52
I've adapted the master sample to send a live stream. This one is not the issue, just mentioned it for completeness.

The browser part of my app basically does the same as the test page, no further camera configuration besides requesting 720p resolution (like the test page). Just connected with the test page to my master and it also sends just 300 kbps.

So the issue is clearly the master: My app as master - viewer sends 300 kbps; test page as master - viewer sends 2.3 Mpbs.
How do I get the KVS SDK to accept a higher bitrate incoming stream/entice the browser to send a higher bitrate?

**Comment by MushMal** [comment] 2020-11-03 18:07
SDK does not control your media pipeline. You need your application to configure your media source/encoder to produce the density/bitrate/quality you need.

**Comment by Ben8823** [comment] 2020-11-03 18:11
I have no issues with my media pipeline. I can send from the master with 10 Mbps and receive 10 Mbps in the browser.

The issue is that the *same* media pipeline in the browser behaves differently when sending to my master/the master sample vs sending to the test page running as master in a browser.

**Comment by MushMal** [comment] 2020-11-03 18:15
@Ben8823 I am not following really. Let's start with your setup. You are running the master test page and using KVS WebRtc C viewer sample? Is your question about the browsers implementation of WebRtc? Can you elaborate and explain your setup with the assets and their versions and clarify your scenario?

**Comment by Ben8823** [comment] 2020-11-03 18:22
I'm sorry if I'm not making myself clear. This is my setup:
- KVS C master sample (adapted)
- KVS test page as viewer/my app in the browser as viewer
The issue is in the stream the browser sends to my master - it is a very low bitrate.

To see if the browser is at all capable of sending a higher bitrate, I've tried the following:
- KVS test page as master
- KVS test page as viewer
In this scenario the browser is able to send a nice high bitrate video.

Since its the same KVS test page as the viewer in both scenarios, I concluded that it must be something in the C master that prevents the browser from using the higher bitrate. This is my question: How do I get the browser to send a higher bitrate video?

**Comment by MushMal** [comment] 2020-11-03 18:34
I see what you are referring to. The browsers implementation should have some control on selecting/confining the bitrate. @lherman-cs any idea?

**Comment by lherman-cs** [comment] 2020-11-03 20:04
@Ben8823 In browsers, the encoding happens in the transceiver layer. Therefore, when you add your video/audio tracks to the transceiver, you can configure the underlying codec.

With the [addTransceiver API](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver), you can set the optional `sendEncodings` which accepts [RTCRtpEncodingParameters](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpEncodingParameters). Even though you can configure the codec through this API, the options are very limited and many of these options are not available in major browsers. For bitrate specific, you can specify the maximum bitrate to be higher. 

But, even with specifying the maximum bitrate, I don't think this will help your situation since the browser is allowed to lower the bitrate whenever it sees fit (the congestion control happens in the background, and the browser can reconfigure its codec during runtime).

As @MushMal  has mentioned, we don't control your media pipeline. It's very hard to believe that our SDK lowers your bitrate. You mentioned that you're using master to act an SFU, retrieves the media data and resend the data back the viewers. Could you try to observe the master incoming bitrate? I'm afraid that the browser simply randomly lowered its bitrate, and therefore the SDK returns a lower bitrate video. 

Another thing, you could also configure [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) to force the resolution to be higher. Make sure that you use `exact` instead of `ideal` constraints, as `ideal` constraints don't guarantee that you'll get your specified resolutions.

**Comment by Ben8823** [comment] 2020-11-03 20:18
The point is that the browser behaves differently depending on the master, without any codec configuration. I'm observing the outgoing bitrate in the browser in chrome://webrtc-internals.

The browser is not randomly lowering the bitrate, its reproducible every time. When the master is the KVS test page, it manages to send the high bitrate. When the master is the C app, it sends the low bitrate.

My master implementation is not really an SFU, it generates its video feed independently. As I said before, I'm ignoring the bandwidth estimation as I can't use it. If a client has trouble receiving the stream, tough luck. But that should not affect the browser's outgoing bitrate.

**Comment by lherman-cs** [comment] 2020-11-03 21:56
@Ben8823 Oh I see the video is independent. 

Another possibility that I can think of is that the browser's encoder is configured with a low profile. This can happen if the master responded with a low profile. As of now, we return the last profile that the offer gives us, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c#L237. 

From my test, I could reproduce your issue. The selected profile seems to be fine, `H264 (123, level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032)`. This profile id maps to High profile with 3.2 level (https://tools.ietf.org/html/rfc6184). With this profile, the maximum bitrate should be around 25 Mb/s according to Annex A from http://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-H.264-200305-S!!PDF-E&type=items.

So, I wonder if there's a Chrome bug for H264 encoder profile selection. I saw that when it's browser-to-browser scenario, Chrome seems to prefer VP8 over H264. Could you try to change the supported codecs in C SDK to use VP8 instead?

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/9d643eb20d426c9f40ed371464f61b6776bd31f2/samples/Common.c#L417-L422

**Comment by lherman-cs** [comment] 2020-11-03 21:57
@Ben8823 Also, if your source code is public, would you mind sharing it too? This way, I can try to run your program on my side, and try to play with possible fixes.

**Comment by Ben8823** [comment] 2020-11-03 22:12
Good to hear that you can reproduce it, now we're getting somewhere :)

My app is already using vp8 because h264 looks even worse at low bitrates, I forgot to mention that. Sending vp8 and accepting only vp8. But I'm pretty sure the same happens with h264 from the looks of it.
Unfortunately the code is not public, but you should be able to reproduce it using the stock master.

**Comment by lherman-cs** [comment] 2020-11-04 15:56
@Ben8823 after some research, Chrome seems to use REMB to determine how much bitrate it should configure its codec. If no REMB supplied/supported, Chrome will choose the lowest reasonable bitrate? (need to look deeper into their implementation). 

You can view what Chrome thinks about the appropriate bitrate through chrome://webrtc-internals with the legacy API (non-standard version):

![Screen Shot 2020-11-04 at 7 43 08 AM](https://user-images.githubusercontent.com/15654932/98132650-85365400-1e71-11eb-82ad-bb28359bfebb.png)

Other people also experience this behavior when the sender side doesn't send REMB, https://groups.google.com/g/discuss-webrtc/c/J_sXHMlxXag.

Unfortunately, our SDK doesn't support sending REMB packets yet.

**Comment by Ben8823** [comment] 2020-11-04 16:24
thanks for investigating this.
is there an eta for adding support of sending REMB packets?

**Comment by MushMal** [comment] 2020-11-04 16:38
@lherman-cs thanks for the info.
@Ben8823 we don’t have any timelines yet. Any contributions are welcome though

**Comment by MushMal** [comment] 2020-12-09 22:08
Resolving this for now. We have plans to add more support for different types of handling of congestion control

**Closed by MushMal** 2020-12-09 22:08 UTC
Labels: enhancement, question
