### ISSUE TITLE
There different scenarios where master not able to send audio and video to viewer

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#797] opened 2020-09-15 12:31 UTC
**Describe the bug**
when i am starting viewer and try to see AV master fails on my device.
Please see attached log where Master giving an error and giving different error logs in error condition and didn't show any AV on viewer

PFA....
[working_scenario.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224686/working_scenario.txt)
[working_scenario_2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224687/working_scenario_2.txt)
[not_wroking_scenario_1.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224688/not_wroking_scenario_1.txt)
[not_wroking_scenario_2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224690/not_wroking_scenario_2.txt)
[not_wroking_scenario_3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224691/not_wroking_scenario_3.txt)

**SDK version number**
Latest commit from GIT master branch : 580cf87c37d81279bec0791f8330e2adb057cb9b

**To Reproduce**
1. i ported master branch on my platform and taken sample master code on my device and try to run with my platform taken audio and video directly from encoder

**Expected behavior**
Its should show audio and video on viewer

**Desktop (please complete the following information):**
 - OS: embedded linux

**Smartphone (please complete the following information):**
 - Device: Windows JS text page i am using as viewer

**Comment by MushMal** [comment] 2020-09-16 07:20
@shiv50084 can you please deduce from the logs what's going on? What assets are you using? Are you using master sample without any modification? Which viewer sample are you using - I assume it's the stock JS but which browser are you using?

It's hard to look through tons of logs searching for something that's not immediately clear.

I am removing the BUG label as this is a question a this stage

**Comment by shiv50084** [comment] 2020-09-16 09:24
@MushMal I am using master sample on my embedded (MIPS, compiled with uclibc) device and i am using as viewer JS test page
https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html on google-chrome browser. 

from "not_wroking_scenario_1.txt" log try to search "ERROR" string. You will find out at line number 182-184 and 191-192 . This error occur when master start after boot of device and JS test page start as viewer.

**Comment by MushMal** [comment] 2020-09-16 17:09
Status code of 0x5200002b (STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT) is generated when there are duplicate messages in the queue. What this means is that a thread is calling a send message API which is synchronous while another thread is already in the process of sending a message with the same correlation ID. Currently, we only support blocking send message calls.

What is happening likely is that your device or your network is too slow sending ICE candidate message and during the trickle ICE another viewer attempts to connect. This is what I am deducing from it.

Recommend stabilizing your software on an open platform such as a PC running Linux. Once your application runs as it's intended to, try to port it to your device. Start with non-Trickle ICE.

**Comment by shiv50084** [comment] 2020-09-18 05:12
@MushMal 
First client connect properly.When i try to connect same client (Viewer) after closing previous connection then this error occurs.

**Comment by MushMal** [comment] 2020-09-18 05:27
If the client uses the same client Id and if the mater hasn’t yet cleared the session then you will have connection failure. Either modify the master to handle different sessions with the same client id somehow or wait until the session clears out. Normal path is to use a different client if.

**Comment by MushMal** [comment] 2020-09-18 05:28
Client ID that is.

**Comment by shiv50084** [comment] 2020-09-18 07:24
@MushMal According to my understanding this function "sessionCleanupWait" is responsible for clean up am i right?

and where i need to modify in master ?

**Comment by MushMal** [comment] 2020-09-18 15:34
Yes, that's the code that's responsible for the cleanup. Not sure what your design is to suggest what you want to do. There is some wording in the WebRTC spec stating how to "determine" the session termination. This is done in the PeerConnection properly on the SDK part. The sample listens to the state changes and kicks off the cleanup in the session cleanup when needed. The issue is that there is no way to know immediately that the other peer is "finished".

I would recommend looking at modifying your viewer to use perhaps a different client ID for a quick follow-up session.

**Comment by chehefen** [comment] 2020-09-21 03:45
@shiv50084 can you try the stock master sample? In the not working log I see cases where not remote ice candidate was discovered, seems that you did not implement the sample properly.

**Comment by hsinghaowang** [comment] 2020-09-23 05:40
@MushMal May I know what exactly the "Client ID" is used? Is there any log example? like:

**Comment by MushMal** [comment] 2020-09-23 06:06
Both are the same. ClientID is a KVS Signaling service concept. This is done so the master can identify the viewers. Say you have multiple viewers - all authenticated and authorized via AWS. Master can chose to add additional logic to respect the offers coming from them or not. The client ID can then be used to map the sessions. The message contains the recepient id which is the client id of the peer.

**Comment by shiv50084** [comment] 2020-09-30 06:19
@MushMal Where can i handle in master if same client ID is coming and master should send AV data to viewer. and in Master where can i find ( which is member variable of structure ) viewer client ID.

**Comment by MushMal** [comment] 2020-09-30 06:31
I couldn't understand what you mean. The client id is specified in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1109

Your master could check/validate/do something on the receive offer functionality

**Comment by MushMal** [comment] 2020-10-10 22:48
Resolving. If you have a any further questions, please cut a new issue with detailed description so we can act on it

**Closed by MushMal** 2020-10-10 22:48 UTC
Labels: question
