### ISSUE TITLE
Consultation on the causes of Segmentation fault

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#868] opened 2020-10-14 09:39 UTC
Hi,Dear Experts,I have a problem now,
When I compile the amazon-kinesis-video-streams-webrtc-sdk-c into a library, suppose it is named ipcam.so, and put it into an embedded device. And I have changed the name of the main function in kvswebrtcclientmaster.c to master_init. 
However, Invoking in embedded devices ipcam.so, when Execute to in master_init function the initkvswebrtc(), a Segmentation fault was generated,The printed log is as follows:

> [KVS Master] Using trickleICE by default
[KVS Master] Created signaling channel ScaryTestChannel
[KVS Master] Finished setting audio and video handlers
Segmentation fault

I wrote a demo, using the dl library to call the master_init function, and there will also be errors when executing initkvswebrtc(),The printed log is as follows:

> [KVS Master] Using trickleICE by default
[KVS Master] Created signaling channel ScaryTestChannel
[KVS Master] Finished setting audio and video handlers
./test_kvs: can't resolve symbol 'pthread_mutexattr_init'

Therefore, I would like to ask whether the problem is caused by the initkvswebrtc() function, or problems caused by embedded devices.How to solve this problem is still unknown.

**Comment by lherman-cs** [comment] 2020-10-14 16:24
@pai-da-xin it's not clear to me where the problem is. Could you share the stack trace and the commit hash?

**Comment by pai-da-xin** [comment] 2020-10-15 01:25
@lherman-cs Oh,sorry,I don't know what to do share the stack trace and the commit hash.How do I get stack traces and create hashes, because I debug directly on the embedded device, this embedded device is a MIPS platform, not an X86 platform, So this is also a problem.

**Comment by lherman-cs** [comment] 2020-10-15 16:17
@pai-da-xin getting a stack trace without a debugger will be varied based on your OS. You can get the commit hash by going to the SDK directory, and run `git rev-parse HEAD`. 

Since you're debugging on the embedded device, do you have access to a debugger, e.g. gdb or lldb? If so, you can run the program in the debugger, and when it crashed, you can get the stack trace by running `bt` in the debugger shell. 

If not, does your embedded device have an OS? If yes, I'd highly recommend to find more general information about how to get the stack trace on your OS.

**Comment by pai-da-xin** [comment] 2020-10-16 03:02
@lherman-cs The debugger is not available for this embedded device, e.g. gdb or lldb. My embedded device is a camera, so it doesn't have an operating system either.
But, after I added printing in the code for debugging, I found that when I executed to [https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L1281](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L1281), printed a sentence " can't resolve symbol 'pthread_mutexattr_init' ", I'm not using data channels at this time. 

The print I added to the code is as follows:
>  STATUS initKvsWebRtc(VOID)
{
    printf("****begin init KvsWebRtc****\n");
    ENTERS();
    STATUS retStatus = STATUS_SUCCESS;
    CHK(!ATOMIC_LOAD_BOOL(&gKvsWebRtcInitialized), retStatus);
    SRAND(GETTIME());
    CHK(srtp_init() == srtp_err_status_ok, STATUS_SRTP_INIT_FAILED);
    printf("****begin init Endianness****\n");
    // init endianness handling
    initializeEndianness();
    KVS_CRYPTO_INIT();
    printf("****begin init SctpSession****\n");
    CHK_STATUS(initSctpSession());
    printf("****SctpSession init end****\n");
    ATOMIC_STORE_BOOL(&gKvsWebRtcInitialized, TRUE);
    printf("****init end****\n");
CleanUp:
    LEAVES();
    return retStatus;
}

The log I printed after execution is as follows: 
> [KVS Master] Using trickleICE by default
[KVS Master] Created signaling channel ScaryTestChannel
[KVS Master] Finished setting audio and video handlers
****begin init KvsWebRtc****
****begin init Endianness****
****begin init SctpSession****
 can't resolve symbol 'pthread_mutexattr_init'

Is pthread_mutexattr_init used in initsctpsession function, or pthread_mutexattr_init in other places, Or pthread_mutexattr_init is not used in the entire SDK.

**Comment by pai-da-xin** [comment] 2020-10-16 04:01
@lherman-cs Excuse me, what is the use of this data channel

**Comment by MushMal** [comment] 2020-10-16 04:24
I am not sure I understand what the issue is. From the information I am guessing/gathering is that you are getting a runtime crash with can't resolve symbol 'pthread-mutexattr_init'. It's possible that the ussctp library (open source library that we use for data channels) is attempting to load a library and in the attempt to load it it uses the API that's not available for the platform you are using. We won't be able to fix the ussctp library as we don't own it.

However, the latest commits contain conditional compilation for enabling/disabling the data channels

ENABLE_DATA_CHANNEL

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L1280

Simply set ENABLE_DATA_CHANNEL to off during compilation - something like this

`cmake .. -DENABLE_DATA_CHANNEL=OFF`


Please resolve this issue once you've run it

**Comment by pai-da-xin** [comment] 2020-10-21 07:14
@lherman-cs @MushMal 
Excuse me, can [initKvsWebRtc function](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L1265) be masked.

**Comment by MushMal** [comment] 2020-10-21 08:12
Do you mean commented out? It does do certain initialization. Again, I am not sure why you are asking these questions. Could you try to debug the source of your crash or if it’s not a crash then could you state the problem you have?

**Comment by pai-da-xin** [comment] 2020-10-21 08:24
Sorry, Can initKvsWebRtc functions be annotated?  
When I use other libraries to call the [function](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L7), When executing to the initKvsWebRtc function, the program crashes, I don't know why. If I try to annotated the initKvsWebRtc function, the program will still crash.

**Comment by MushMal** [comment] 2020-10-21 17:11
I am sorry but I don't know what to suggest. Without understanding what your crash is I can't recommend anything. The API does the library initialization. Among other things, it detects and initializes the endianness, sets the random seed and initializes a couple of dependent libraries.

I would strongly recommend doing some deep dives into your code. Try to run the sample as is on various standard platforms like Linux, Mac. Make sure you get the latest commit and build it properly.

If the crash is happening on your specific platform or your specific application then you need to find a way to capture the stack traces for all of the threads to get some idea what could be wrong. 

Aside from that, we won't be able to help

**Comment by disa6302** [comment] 2020-10-21 21:56
@pai-da-xin ,

I am closing this ticket because of lack of information. Feel free to reach out when you are able to capture a stack trace.

**Closed by disa6302** 2020-10-21 21:56 UTC
Labels: question

**Comment by realizing85** [comment] 2023-10-30 07:20
@pai-da-xin 
Have you solved this problem? 
I too have the same problem. If it has been resolved, please reply.
