### ISSUE TITLE
HTTPS callback with reason 30

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1075] opened 2021-02-18 11:44 UTC
What does lwsHttpCallbackRoutine's reason code 30 mean?
And What should I check?

** Log ** 
[KVS] Using trickleICE by default
[KVS] set log level to 1
[KVS] Created signaling channel 8981300023236415289
[KVS] Finished setting audio(2004) and video(0) handlers
[KVS] KVS WebRTC initialization completed successfully
KVS_INF createSignalingClientSync: Creating Signaling Client Sync
KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 21
KVS_VER signalingClientStateChanged: Signaling client state changed to 1 - 'New'
KVS_DBG stepStateMachine: State Machine - Current state: 0x0000000000000001, Next state: 0x0000000000000002
KVS_VER signalingClientStateChanged: Signaling client state changed to 2 - 'Get Security Credentials'
KVS_DBG stepStateMachine: State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000004
KVS_VER signalingClientStateChanged: Signaling client state changed to 3 - 'Describe Channel'
KVS_VER lwsCompleteSync: Perform secure synchronous call for URL: https://kinesisvideo.ap-northeast-1.amazonaws.com/describeSignalingChannel
KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 27
KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 85
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER signalingClientGetCurrentState: Signaling Client Get Current State
KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 30
KVS_ERR createSignalingSync(179): operation returned status code: 0x0000000f
KVS_VER lwsHttpCallbackRoutine: HTTPS callback with reason 28
[KVS] createSignalingClientSync(): operation returned status code: 0x0000000f
[KVS] Terminated with status code 0x0000000f[KVS] Cleaning up....
KVS_VER signalingClientGetMetrics: Signaling Client Get Metrics
[KVS] signalingClientGetMetrics() operation returned status code: 0x00000001KVS_INF freeSignalingClient: Freeing Signaling Client
[KVS] Cleanup done

Thanks.

**Comment by disa6302** [comment] 2021-02-18 18:11
@lhuijae , 

It looks like your signaling client connection timed out (`0x0000000f`). It could be a network issue. Try to debug your network to see what could be causing this. 

About reason 30, it is an indication that the websocket instance is destroyed. The issue is there is a potential network issue that could be causing the signaling client to timeout. I would recommend getting started with the stock master sample and ensure it runs clean with the network set up before making modifications.

For more information on what the reason codes mean, check [this](https://libwebsockets.org/lws-api-doc-main/html/group__usercb.html#ggad62860e19975ba4c4af401c3cdb6abf7aca834dc035b7f7486f9ce40fde54fe9e).

**Comment by MushMal** [comment] 2021-02-18 18:44
Thanks @disa6302 . It will also help to build the debug version of the libWebSockets. Search the issues to get more information on how to build the debug version and enable the debug spew from it.

**Comment by lhuijae** [comment] 2021-02-19 00:05
Thanks. I will debug the network and libwebsockets.

**Comment by MushMal** [comment] 2021-02-19 00:09
Closing the issue. Please re-open or cut a new issue once you have more information

**Closed by MushMal** 2021-02-19 00:09 UTC
Labels: question
