### ISSUE TITLE
[BUG]  Connecting to signaling server ends up with 0x0000000f, timeout error

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1190] opened 2021-07-16 17:05 UTC
We recently have seen failures to create websocket connection in multiple users' cameras. When webrtc initializing connection to signaling server, it first creates a secured connection for iot credentialing, and then creates another websocket connection for the signaling channel.  The first connection usually is successful, but the second one fails frequently. 

Most cameras actually work OK.  But for the cameras failing, they would fail consistently, only occasionally succeed.
We have restarted the router but it hasn't helped.  Cameras are in different wifi network.

On one camera, we flashed the special fw to print debug level log for libwesocket.  Log is attached.
[webrtc_fail2021167.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6832257/webrtc_fail2021167.txt)

I have noticed in the log that after this line
[2021/07/16 13:29:10:6834] I: lws_client_connect_2: 0x72e591a8: address m-b94e17e0.kinesisvideo.us-east-1.amazonaws.com:443
There have been 5~6 seconds with no lws activity.

At this moment, I am not sure where is the problem, whether it is in the system network stack or kvs sdk.
I wonder if we can have a joint debug meeting to work on this to speed up investigation and discovery.

SDK version number
1.5.0

**Comment by juno52wendy** [comment] 2021-07-17 04:24
The region is the closest to your country. It is best if your country has an AWS signaling server deployment. This is the best, otherwise the problem is basically unsolvable。

**Comment by has253** [comment] 2021-07-21 23:13
Additional logs from the customer -

"We see logs like the one pasted below where the LWS callback returns 1 with an error string  "HS: Rejected at CLIENT_ESTABLISHED". Can you help us understand what causes this error?



2021-07-21 20:28:12 VERBOSE signalingClientStateChanged(): Signaling client state changed to 8 - 'Connecting'
2021-07-21 20:28:12 VERBOSE lwsCompleteSync(): Perform secure synchronous call for URL: wss://m-26d02974.kinesisvideo.ap-northeast-1.amazonaws.com?X-Amz-ChannelARN=arn:aws:kinesisvideo:ap-northeast-1:161127818829:channel/webrtc_icatch_qa/1589276000734
2021-07-21 20:28:12 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 85
2021-07-21 20:28:17 ERROR   connectSignalingChannelLws(): operation returned status code: 0x0000000f
2021-07-21 20:28:17 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 29
2021-07-21 20:28:17 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 19
2021-07-21 20:28:17 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
2021-07-21 20:28:17 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
2021-07-21 20:28:17 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
2021-07-21 20:28:17 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
2021-07-21 20:28:17 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
2021-07-21 20:28:17 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 24
2021-07-21 20:28:18 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 2
2021-07-21 20:28:18 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 3
2021-07-21 20:28:18 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 1
2021-07-21 20:28:18 WARN    lwsWssCallbackRoutine(): Client connection failed. Connection error string: HS: Rejected at CLIENT_ESTABLISHED
2021-07-21 20:28:18 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 75
2021-07-21 20:28:18 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 30
2021-07-21 20:28:18 ERROR   signalingConnectSync(): operation returned status code: 0x0000000f string


We appreciate any insight you can offer into this problem."

**Comment by MushMal** [comment] 2021-07-21 23:26
You can get more info on the lws reason codes from this link: https://libwebsockets.org/lws-api-doc-main/html/group__usercb.html

Looking at the log you've attached, it's not immediately clear what this could be. You should look for the latency info from the logs - how long did it take to get the error and how long did it take to establish the connection. There is a default 5 second limit on the connection in the signaling client lws configuration. Perhaps, you are hitting the limit there.

After all the retries are exhausted, the signaling client will return the timeout - which is 0x0000000f status code - so it's a consequence and not the root cause.

Recommend:

* Ensure you are getting a good run on a stable network
* Build and run a debug version of lws. Search the project issues for "debug lws" to get some pointers on how to build the debug version and how to enable the lws debug output.

**Comment by zwei333** [comment] 2021-07-21 23:46
When the problem happens, video recording (kvs producer) still works fine.  So we think the network is OK.
failure log with lws debug attached here
[webrtc_fail2021167.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6859286/webrtc_fail2021167.txt)

**Comment by MushMal** [comment] 2021-07-21 23:57
Took a quick look and it seems that the signaling client retries 3 times before reaching its own timeout. Each retry does timeout in 5 seconds. There is errno 11 being returned which is E_AGAIN which is a likely indicator of a timeout in SSL stack. 

The ongoing HTTP connection might not be the best indicator of the networking issues.

I would also recommend someone from the KVS team to look at the backend for the potential issues but primarily, I would recommend your team to eliminate the networking issues yourselves.

**Comment by sharadrj** [comment] 2021-07-22 23:33
@zwei333, 

Were you able to build the debug version of lws as mushmal suggested?

**Comment by hassanctech** [comment] 2021-07-23 20:19
We are currently working on cutting a release with an updated version of libwebsockets (v4.2.1) we will notify you once that is ready.

**Comment by zwei333** [comment] 2021-07-27 17:51
[websocket_log5_failure.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6887650/websocket_log5_failure.txt)
[websocket_log4_success.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6887651/websocket_log4_success.txt)
Please see most recent logs. One for successful streaming, and the other for 0x0000000f error
In both logs, webrtc/websocket logs and tcpdump logs are interleaved

**Comment by zwei333** [comment] 2021-07-27 18:32
[error trace.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6887874/error.trace.txt)
I might have seen something interesting.  Please check this file

**Comment by hassanctech** [comment] 2021-07-27 23:56
@zwei333 can you please test with the latest commit: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/71401605a7c6197fba57cd1f2282152233221f6c

We intend to cut a release shortly and this is close to a release candidate.  We're still working out some issues with libwebsockets on Windows but if you're on any linux/mac platform it should work fine.  We've updated the version of libwebsockets, libusrsctp, libsrtp so there are a more than a year of updates in libwebsockets that we have so I'm really curious to see if you continue to see these issues with the new version.

**Comment by zwei333** [comment] 2021-07-28 17:47
Seems like this patch can solve the problem

diff --git a/lib/roles/http/client/client-handshake.c b/lib/roles/http/client/client-handshake.c
index 21df052b..deacdfd7 100644
--- a/lib/roles/http/client/client-handshake.c
+++ b/lib/roles/http/client/client-handshake.c
@@ -20,7 +20,7 @@ lws_getaddrinfo46(struct lws *wsi, const char *ads, struct addrinfo **result)
 	} else
 #endif
 	{
-		hints.ai_family = PF_UNSPEC;
+		hints.ai_family = AF_INET;
 	}
 
 	return getaddrinfo(ads, NULL, &hints, result);

**Comment by disa6302** [comment] 2021-07-28 20:51
I suspect this has something to do with the older `libwebsockets` version. I do not see this file in the newer versions which makes me wonder what broke all of a sudden. What `libwebsockets` version are you using?

**Comment by zwei333** [comment] 2021-07-28 21:45
v3.2.3.
I did check the latest version for this issue.  libwebsockets adds a lot of error checking, but the patch is still needed

**Comment by zwei333** [comment] 2021-07-28 21:47
Our testing result is promising. For a specific router, the failure of Ipv6 dns response was roughly 40%, and the failure (error 0x0000000f) to stream was almost 90%
With the patch, Ipv6 dns request is skipped and we see zero failure of error 0x0000000f

**Comment by zwei333** [comment] 2021-07-29 04:00
This issue can be closed.  It is not a kvs sdk bug

**Comment by disa6302** [comment] 2021-07-29 17:48
Sure. Can you update this issue with any updates from libwebsockets with this change? 
If a PR is opened with this patch on libwebsockets and approved, we can pull it into our SDK as well.

**Comment by disa6302** [comment] 2021-08-02 06:26
Closing since it is not an SDK issue. Will track libwebsockets for any changes that could be included in our SDK.

**Closed by disa6302** 2021-08-02 06:26 UTC
Labels: bug
