### ISSUE TITLE
The status is ICE_AGENT_STATE_READY, but the web test page has no images

### ISSUE THREAD

**Issue by CoinHan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#126] opened 2020-01-07 10:25 UTC
HI:
 

>   I'm using the aws-sdk-kvs /2.1.0 migration to the MIPS platform.

  

>  The output information of Internet of things devices is as follows:

 ```
2020-01-07 10:13:46 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   turnConnectionHandleChannelDataTcpMode(): operation returned status code: 0x5a000024
2020-01-07 10:13:46 DEBUG   turnConnectionIncomingDataHandler(): operation returned status code: 0x5a000024
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   turnConnectionHandleChannelDataTcpMode(): operation returned status code: 0x5a000024
2020-01-07 10:13:46 DEBUG   turnConnectionIncomingDataHandler(): operation returned status code: 0x5a000024
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   handleStunPacket(): Dropping response packet because transaction id does not match
2020-01-07 10:13:46 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000004, Next state: 0x0000000000000008
2020-01-07 10:13:46 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_CONNECTED.
2020-01-07 10:13:46 DEBUG   onConnectionStateChange(): New connection state 3
2020-01-07 10:13:46 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000008, Next state: 0x0000000000000020
2020-01-07 10:13:46 DEBUG   executeReadyIceAgentState(): Selected pair ip address: 34.215.13.39, port 65470, local candidate type: relay
2020-01-07 10:13:46 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CONNECTED to ICE_AGENT_STATE_READY.
2020-01-07 10:13:51 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:01 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:11 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:22 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:33 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:43 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:14:54 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:15:04 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-01-07 10:15:15 DEBUG   lwsWssCallbackRoutine(): Client is writable
```
[mips_0x0000000f_20200107.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4033445/mips_0x0000000f_20200107.txt)

[mips_ICE_AGENT_STATE_READY_20200107.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4050227/mips_ICE_AGENT_STATE_READY_20200107.txt)

> The usage method is the same as Ubuntu, using the resource file h264SampleFrames&opusSampleFrames that comes with the SDK

What is the cause of this, thank you!

**Comment by zhiyua-git** [comment] 2020-01-12 04:25
Hi @CoinHan ,

mips_0x0000000f_20200107.txt shows you are getting timeout when connecting to KVS signaling service. Are you seeing the same issue with ubuntu or it is only happening on your mips device?
``signalingConnectSync(): operation returned status code: 0x0000000f``

It is not clear why you are not able to view the video/audio on browser for above log. Can you provide device information so we can try to reproduce? Thanks.

**Comment by CoinHan** [comment] 2020-01-12 05:24
Hi @zhiyua-git ：
    Thanks for your reply!

> 1.  Unable to view video/audio in browser

     Sorry, log file uploads don't match.
     [mips_ICE_AGENT_STATE_READY_20200107.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4050223/mips_ICE_AGENT_STATE_READY_20200107.txt)

     Device information:
     ` Chip name: T20
     CPU：XBurst single core, up to 1GHz.
                MXU2.0 IVS engine, innovative 128-bit SMID extension instruction.
                32KB L1 i-cache and 32KB L1 d-cache.
                128kb L2 unified cache.
                Hardware floating point unit.
     Chip architecture: MIPS
     Cross-compilation tool: mips-linux-uclibc-gnu`
    

> 2.  getting timeout when connecting/create to KVS signaling service. 

     `signalingConnectSync(): operation returned status code: 0x0000000f`
     `createSignalingSync(): operation returned status code: 0x0000000f`

      [mips_0x0000000f_20200107.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4050233/mips_0x0000000f_20200107.txt)

     Ubuntu and MIPS exist the same way, and the odd thing is that Ubuntu works better with the same network environment as MIPS.

**Comment by MushMal** [comment] 2020-01-29 07:33
Just looking at the logs, mips_0x0000000f_20200107.txt seems to be caused by the network timeout connecting to the signaling. It attempts to connect within 15 seconds but can't establish the connection. The first log is more interesting mips_ICE_AGENT_STATE_READY_20200107.txt - we get the connection established, exchange the SDPs and ICE candidates. The ICE state machine reaches Connected and then Ready. For some reason no exchange is going on. Need to look closer

**Comment by chehefen** [comment] 2020-03-03 08:04
@CoinHan Closing this issue for now since it's almost three months old. Please open a new issue if the problem still remains.

**Closed by chehefen** 2020-03-03 08:04 UTC
