### ISSUE TITLE
[QUESTION] Build help

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#547] opened 2020-06-12 22:31 UTC
I'm trying to build this commit
f0ff7e6d58a9218ff829f22f99a296832eaf681a

Right now I'm stuck at this message, any idea how to solve it?
[ 26%] Building C object CMakeFiles/kvsCommonLws.dir/src/source/Common/Auth.c.o
In file included from /root/project/arm/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libkvsCommonLws/build/src/libkvsCommonLws-download/src/source/Common/Auth.c:5:0:
/root/project/arm/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libkvsCommonLws/build/src/libkvsCommonLws-download/src/source/Common/Include_i.h:41:27: fatal error: libwebsockets.h: No such file or directory
 #include <libwebsockets.h>
                           ^
compilation terminated.
CMakeFiles/kvsCommonLws.dir/build.make:62: recipe for target 'CMakeFiles/kvsCommonLws.dir/src/source/Common/Auth.c.o' failed
make[5]: *** [CMakeFiles/kvsCommonLws.dir/src/source/Common/Auth.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/kvsCommonLws.dir/all' failed
make[4]: *** [CMakeFiles/kvsCommonLws.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
CMakeFiles/libkvsCommonLws-download.dir/build.make:111: recipe for target 'build/src/libkvsCommonLws-download-stamp/libkvsCommonLws-download-build' failed
make[3]: *** [all] Error 2
make[2]: *** [build/src/libkvsCommonLws-download-stamp/libkvsCommonLws-download-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libkvsCommonLws-download.dir/all' failed
make[1]: *** [CMakeFiles/libkvsCommonLws-download.dir/all] Error 2
make: *** [all] Error 2
Makefile:83: recipe for target 'all' failed
CMake Error at CMake/Utilities.cmake:61 (message):
  CMake step for libkvsCommonLws failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:78 (build_dependency)

**Comment by suggestedfixes** [comment] 2020-06-12 22:33
My environment is similar to this in the travis file
    - name: "ARM Cross-compilation"
      os: linux
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
            - binutils-arm-linux-gnueabi
      compiler: gcc
      before_install:
        # TODO: Remove the following line. This is only a workaround for enabling IPv6, https://github.com/travis-ci/travis-ci/issues/8891.
        - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
      before_script:
        - export CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++
        - mkdir build && cd build
        - cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi
      script: make

**Comment by lherman-cs** [comment] 2020-06-12 22:36
@suggestedfixes the issue is related to a typo within our `CMakeLists.txt`. We already have a PR in progress to fix this exact problem, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/546. We'll merge it as soon as it passes all the CI checks.

**Comment by suggestedfixes** [comment] 2020-06-12 23:01
Weird, did CI cache previous open-source folder?

**Comment by MushMal** [comment] 2020-06-12 23:13
This is indeed weird. We are not yet entirely sure of the root cause why this build clean on Linux subsystems and some MacOS-es

**Comment by disa6302** [comment] 2020-06-13 00:01
@suggestedfixes ,

The fix is in. Please checkout the new commit. Thank you!

**Comment by suggestedfixes** [comment] 2020-06-13 00:03
Great!!

**Comment by suggestedfixes** [comment] 2020-06-13 01:36
I cloned the newest commit, still not working. I did a search for libwebsockets.h and it is located at ./open-source/include/, I think this folder was included before but got removed. Trying to include this rule.

**Comment by suggestedfixes** [comment] 2020-06-13 01:39
Nvm it is still there
include_directories(${OPEN_SRC_INSTALL_PREFIX}/include)

**Comment by disa6302** [comment] 2020-06-13 21:45
@suggestedfixes ,

If the build is working fine, can you close this ticket? Thanks!

**Comment by disa6302** [comment] 2020-06-15 04:29
Closing this. Feel free to open a new ticket if you face any issues.

**Comment by suggestedfixes** [comment] 2020-06-15 15:36
@disa6302 Was not able to make a new build, still building.

**Comment by disa6302** [comment] 2020-06-15 16:51
@suggestedfixes , 

Can we help with any of your build issues?

**Comment by suggestedfixes** [comment] 2020-06-15 17:56
I think it is because newly added dependency libkvsCommonLws needs libwebsockets. And include files are specified after installing libkvsCommonLws

**Comment by suggestedfixes** [comment] 2020-06-15 17:57
So I'm currently shuffling include_directories() around and make libkvsCommonLws to build dependencies. Am I on the right track?

**Comment by MushMal** [comment] 2020-06-15 18:48
@suggestedfixes could you please do git clean -ddfx to get rid of all directories and start anew. For some reason, git clean -ddfx doesn't remove open-source directory and you might need to manually remove it. Try to build it again afterwards. It should build LWS first before it attempts to build common library so the installed library and the includes should already be present.

**Comment by suggestedfixes** [comment] 2020-06-16 14:25
It is likely due to one of the previous commits was installing libwebsocksets.pc into system PKG_CONFIG_PATH. Now there are two versions of libwebsockets.pc, pkg-config got confused on which version to grab.

**Comment by suggestedfixes** [comment] 2020-06-16 16:22
Yep, pkgconfig got confused and loaded the directory of my global one.

**Closed** 2020-06-16 16:23 UTC
