### ISSUE TITLE
[BUG] The root cafile for turns used by Tls_mbedtls.c:createTlsSession is set as Compile-time path

### ISSUE THREAD

**Issue by vc60er** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1550] opened 2022-09-09 09:05 UTC
**Logging**
1999-12-31 16:00:13 ERROR   turnConnectionStepState(): operation returned status code: 0x15000020
1999-12-31 16:00:13 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x15000020. Aborting TurnConnection
1999-12-31 16:00:14 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x15000020. Aborting TurnConnection
2022-09-05 08:59:20 ERROR   turnConnectionStepState(): operation returned status code: 0x15000020
2022-09-05 08:59:21 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x15000020. Aborting TurnConnection
2022-09-05 08:59:22 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x15000020. Aborting TurnConnection

**Describe the bug**
The root cafile for turns used by Tls_mbedtls.c:createTlsSession is set as Compile-time path, it could not be used in run-time, this issue can cause error 0x15000020(STATUS_INVALID_CA_CERT_PATH) when allocate relay candaite from turns server

```c
// src/source/Crypto/Tls_mbedtls.c
STATUS createTlsSession(PTlsSessionCallbacks pCallbacks, PTlsSession* ppTlsSession)
{
...
    CHK(mbedtls_ctr_drbg_seed(&pTlsSession->ctrDrbg, mbedtls_entropy_func, &pTlsSession->entropy, NULL, 0) == 0, STATUS_CREATE_SSL_FAILED);
    CHK(mbedtls_x509_crt_parse_file(&pTlsSession->cacert, KVS_CA_CERT_PATH) == 0, STATUS_INVALID_CA_CERT_PATH);
...    
}

// CMakeLists.txt

# pass ca cert location to sdk
add_definitions(-DKVS_CA_CERT_PATH="${CMAKE_SOURCE_DIR}/certs/cert.pem")
add_definitions(-DCMAKE_DETECTED_CACERT_PATH)

// Compile log 
/mips-gcc472-glibc216-64bit/bin/mips-linux-gnu-gcc -DCMAKE_DETECTED_CACERT_PATH -DDETECTED_GIT_HASH -DINSTRUMENTED_ALLOCATORS -DKVS_CA_CERT_PATH=\"/home/amazon-kinesis-video-streams-webrtc-sdk-c/certs/cert.pem\" -DKVS_USE_MBEDTLS -DSDK_VERSION=\"ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47\" -I/home/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/include -I/home/amazon-kinesis-video-streams-webrtc-sdk-c/src/include -I/home/amazon-kinesis-video-streams-webrtc-sdk-c/src/ice -I/home/amazon-kinesis-video-streams-webrtc-sdk-c/configs -DMBEDTLS_USER_CONFIG_FILE='<config_mbedtls.h>'  -muclibc -fPIC -O3 -DNDEBUG -MD -MT CMakeFiles/kvsWebrtcClient.dir/src/source/Crypto/Tls_mbedtls.c.o -MF CMakeFiles/kvsWebrtcClient.dir/src/source/Crypto/Tls_mbedtls.c.o.d -o CMakeFiles/kvsWebrtcClient.dir/src/source/Crypto/Tls_mbedtls.c.o -c /home/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Crypto/Tls_mbedtls.c
```

**SDK version number**
v1.7.3

**Open source building**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
.

**Comment by hassanctech** [comment] 2022-09-13 15:58
Indeed that seems problematic, can you modify this line:
`add_definitions(-DKVS_CA_CERT_PATH="${CMAKE_SOURCE_DIR}/certs/cert.pem")` 
and confirm that it works?

**Comment by vc60er** [comment] 2022-09-17 12:54
> Indeed that seems problematic, can you modify this line: `add_definitions(-DKVS_CA_CERT_PATH="${CMAKE_SOURCE_DIR}/certs/cert.pem")` and confirm that it works?
> 
> Modify the path to be where the file is located on your device that is running the SDK.

Yes, I have modified it, and works well.
Also, I think this variable can configure in runtime would be better。

**Comment by niyatim23** [comment] 2022-09-18 23:26
Closing since the issue is resolved

**Closed by niyatim23** 2022-09-18 23:26 UTC
Labels: bug
