### ISSUE TITLE
[BUG] kvsWebrtcClientMasterGstSample: rtcpReportsCallback(): sender report - 0 packets 0 bytes - TLS handshake issue?

### ISSUE THREAD

**Issue by mc256** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1558] opened 2022-09-24 22:08 UTC
**Describe the bug**
`sample/kvsWebrtcClientMasterGstSample` does not work. Getting errors that are similar to #1557 

I followed the instructions to build the project on Raspberry Pi (`Linux 5.15.61-v8+ aarch64 GNU/Linux`).

`sample/kvsWebrtcClientMasterGstSample` does not work. To locate the error, I tried other examples. `sample/kvsWebrtcClientMaster` does seem to work as expected. So I compared the logs from these two binaries, and it seems that is missing in the logs from `sample/kvsWebrtcClientMasterGstSample`
```
socketConnectionTlsSessionOnStateChange(): TLS handshake done. Time taken 350 ms
```

**Logging**

`sample/kvsWebrtcClientMasterGstSample`, This does not work. In this case, we can see `0 packets 0 bytes` so no video from the viewer side.
```


2022-09-24 21:39:43 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000008, Next state: 0x0000000000000010, Current local state retry count [0], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:43 DEBUG   iceAgentReadyStateSetup(): Selected pair MEkt9t226_azHT3s+a3, local candidate type: host. Round trip time 3 ms. Local candidate priority: 2130706431, ice candidate pair priority: 7926369428998979582
2022-09-24 21:39:43 DEBUG   iceAgentReadyStateSetup(): Freeing Turn allocations that are not selected. Total turn allocation count 2
2022-09-24 21:39:43 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
2022-09-24 21:39:43 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_CLEAN_UP
2022-09-24 21:39:43 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_CLEAN_UP
2022-09-24 21:39:43 INFO    onConnectionStateChange(): New connection state 3
2022-09-24 21:39:43 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
2022-09-24 21:39:43 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
2022-09-24 21:39:43 DEBUG   rtcPeerConnectionGetMetrics(): ICE local candidate Stats requested at 16640555836915745
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate IP Address: 172.18.1.160
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: host
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 34526
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate priority: 2130706431
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: udp
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: N/A
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate Ice server source: N/A
2022-09-24 21:39:43 DEBUG   rtcPeerConnectionGetMetrics(): ICE remote candidate Stats requested at 16640555836916247
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate IP Address: 172.18.1.10
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: prflx
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 64139
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate priority: 1845501695
2022-09-24 21:39:43 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp
2022-09-24 21:39:43 VERBOSE signalingClientGetCurrentState(): Signaling Client Get Current State
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 63150, channel number 16385
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 64702, channel number 16386
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 52219, channel number 16387
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 49618, channel number 16388
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 52570, channel number 16389
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer 3.96.45.41, port: 53458, channel number 16390
2022-09-24 21:39:43 DEBUG   socketConnectionClosed(): Close socket 17
2022-09-24 21:39:43 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2022-09-24 21:39:43 VERBOSE pregenerateCertTimerCallback(): New certificate has been pre-generated and added to the queue
2022-09-24 21:39:43 VERBOSE incomingRelayedDataHandler(): Candidate id: kVHpLXplz
2022-09-24 21:39:43 DEBUG   turnConnectionHandleStun(): TURN Allocation freed.
2022-09-24 21:39:43 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 8
2022-09-24 21:39:43 DEBUG   socketConnectionClosed(): Close socket 16
2022-09-24 21:39:43 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2022-09-24 21:39:43 DEBUG   dtlsSessionChangeState(): DTLS init completed. Time taken 300 ms



2022-09-24 21:39:44 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:45 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598975203142144 149765002768849 : 0 packets 0 bytes
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598975204474443 79874668143401 : 0 packets 0 bytes
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598976089510866 149765002787422 : 0 packets 0 bytes
2022-09-24 21:39:46 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2022-09-24 21:39:46 DEBUG   lwsWssCallbackRoutine(): Client is writable
2022-09-24 21:39:46 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598976429293889 79874668157089 : 0 packets 0 bytes
2022-09-24 21:39:46 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598977078426226 79874668164344 : 0 packets 0 bytes
2022-09-24 21:39:46 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598977348846387 149765002813812 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598978148162993 149765002830561 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598978255839542 79874668177502 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598979209771964 149765002852807 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598979364411832 79874668189892 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598979906099121 79874668195945 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598980451927187 149765002878836 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598981122119467 79874668209536 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598981302998579 149765002896670 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598981806007539 149765002907210 : 0 packets 0 bytes
2022-09-24 21:39:47 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598981925892961 79874668218518 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598982790512828 149765002927840 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598982970097866 79874668230188 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598983731754481 149765002947564 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598983915862120 79874668240758 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1287975148 16634598984411175787 149765002961801 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598984749549202 79874668250075 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:39:48 VERBOSE rtcpReportsCallback(): sender report 1377246212 16634598985385678526 79874668257185 : 0 packets 0 bytes
2022-09-24 21:39:48 VERBOSE signalingClientGetCurrentState(): Signaling Client Get Current State
...
```

 ---

Log from `sample/kvsWebrtcClientMaster` , This works. We can see it has `2022-09-24 21:38:48 DEBUG   socketConnectionTlsSessionOnStateChange(): TLS handshake done. Time taken 350 ms` which does not exist in the previous log. So I suspect that this is the problem. But I have no clue how to fix it....

```
2022-09-24 21:38:48 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000008, Next state: 0x0000000000000010, Current local state retry count [0], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:38:48 DEBUG   iceAgentReadyStateSetup(): Selected pair m+SX3VZNe_oVBrb6STw, local candidate type: host. Round trip time 3 ms. Local candidate priority: 2130706431, ice candidate pair priority: 7926369428998979582
2022-09-24 21:38:48 DEBUG   iceAgentReadyStateSetup(): Freeing Turn allocations that are not selected. Total turn allocation count 2
2022-09-24 21:38:48 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
2022-09-24 21:38:48 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_CLEAN_UP
2022-09-24 21:38:48 DEBUG   socketConnectionTlsSessionOnStateChange(): TLS handshake done. Time taken 350 ms
2022-09-24 21:38:48 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_CLEAN_UP
2022-09-24 21:38:48 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
2022-09-24 21:38:48 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
2022-09-24 21:38:48 INFO    onConnectionStateChange(): New connection state 3
2022-09-24 21:38:48 DEBUG   rtcPeerConnectionGetMetrics(): ICE local candidate Stats requested at 16640555286694421
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate IP Address: 172.18.1.160
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: host
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 38219
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate priority: 2130706431
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: udp
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: N/A
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate Ice server source: N/A
2022-09-24 21:38:48 DEBUG   rtcPeerConnectionGetMetrics(): ICE remote candidate Stats requested at 16640555286694617
2022-09-24 21:38:48 VERBOSE signalingClientGetCurrentState(): Signaling Client Get Current State
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate IP Address: 172.18.1.10
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: prflx
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 54057
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate priority: 1845501695
2022-09-24 21:38:48 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp
2022-09-24 21:38:48 VERBOSE incomingRelayedDataHandler(): Candidate id: YXWb1oo97
2022-09-24 21:38:48 DEBUG   socketConnectionClosed(): Close socket 17
2022-09-24 21:38:48 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2022-09-24 21:38:48 VERBOSE incomingRelayedDataHandler(): Candidate id: be1jAR8+G
2022-09-24 21:38:48 DEBUG   turnConnectionHandleStun(): TURN Allocation freed.
2022-09-24 21:38:48 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 8
2022-09-24 21:38:48 DEBUG   socketConnectionClosed(): Close socket 16
2022-09-24 21:38:48 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2022-09-24 21:38:48 DEBUG   dtlsSessionChangeState(): DTLS init completed. Time taken 300 ms
2022-09-24 21:38:48 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 8
2022-09-24 21:38:48 VERBOSE pregenerateCertTimerCallback(): New certificate has been pre-generated and added to the queue



2022-09-24 21:38:49 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:38:50 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598738681986957 232331 : 329 packets 56423 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598738682678876 123895 : 128 packets 21760 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598739263383365 130385 : 135 packets 22950 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598739515870748 249805 : 354 packets 61744 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598740036347770 260711 : 369 packets 64814 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598740144414731 140231 : 145 packets 24650 bytes
2022-09-24 21:38:51 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598740883303725 278459 : 395 packets 70881 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598741133038464 151280 : 156 packets 26520 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598741571329998 292877 : 415 packets 75104 bytes
2022-09-24 21:38:51 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598741705135838 157674 : 162 packets 27540 bytes
2022-09-24 21:38:52 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598742031750492 302525 : 430 packets 78312 bytes
2022-09-24 21:38:52 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598742337386378 164740 : 169 packets 28730 bytes
2022-09-24 21:38:52 VERBOSE rtcpReportsCallback(): sender report 232384961 16634598742569504020 313793 : 445 packets 81818 bytes
2022-09-24 21:38:52 VERBOSE rtcpReportsCallback(): sender report 1524395231 16634598742922374238 171277 : 176 packets 29920 bytes
2022-09-24 21:38:52 DEBUG   dtlsSessionProcessPacket(): Detected DTLS close_notify alert
2022-09-24 21:38:52 INFO    onConnectionStateChange(): New connection state 6
2022-09-24 21:38:52 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: jlpfn6honlqjxq5zu35jg 
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 15
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 14
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 13
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 12
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 11
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 10
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 9
2022-09-24 21:38:52 DEBUG   socketConnectionClosed(): Close socket 8
2022-09-24 21:38:54 VERBOSE signalingClientGetCurrentState(): Signaling Client Get Current State
[KVS Master] Streaming session terminated
[KVS Master] Cleaning up....
```

**SDK version number**
v1.7.3

**Comment by niyatim23** [comment] 2023-02-06 17:33
Hi @mc256, can you please check with a sample GStreamer pipeline if it works fine on your system?

**Comment by jagdish24** [comment] 2023-02-07 13:55
I have a similar issue, I am getting a video stream from UDP source and transmitting it. 

The simple pipeline which works in my scenario from the shell,

```
gst-launch-1.0 -v udpsrc port=PORT ! h264parse ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=STREAM_NAME access-key=ACCESS_KEY secret-key=SECRET_KEY aws-region=AWS_REGION
```

Can anyone help me convert it for `gst_parse_launch` function?

**Comment by mc256** [comment] 2023-02-13 03:51
Thanks @niyatim23 ,

I preliminary tested `./kvsWebrtcClientMasterGstSample` and `./kvsWebrtcClientMaster`, and they work. (I made no changes what so ever, did you fix something on the server side?)

Library version: [v1.7.3](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.7.3)
OS version: `Linux alpha 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux`

I will continue testing other components to make sure that it works.

**Comment by niyatim23** [comment] 2023-02-13 16:53
Hi @mc256, that's awesome! We did not change anything though. Have you updated your GStreamer version? Can you please share the GStreamer version with which this is working so that @jagdish24 can check as well?

**Comment by mc256** [comment] 2023-02-13 22:01
FYI, if this helps
@niyatim23  @jagdish24 
```
➜  ~ dpkg -l | grep gstreamer

ii  gir1.2-gstreamer-1.0:arm64             1.18.4-2.1                       arm64        GObject introspection data for the GStreamer library
ii  gstreamer1.0-alsa:arm64                1.18.4-2                         arm64        GStreamer plugin for ALSA
ii  gstreamer1.0-libav:arm64               1.18.4-3                         arm64        ffmpeg plugin for GStreamer
ii  gstreamer1.0-omx-bellagio-config       1.18.3-1                         arm64        OpenMax plugins for GStreamer
ii  gstreamer1.0-omx-generic               1.18.3-1                         arm64        OpenMax plugins for GStreamer
ii  gstreamer1.0-omx-generic-config        1.18.3-1                         arm64        OpenMax plugins for GStreamer
ii  gstreamer1.0-plugins-bad:arm64         1.18.4-3                         arm64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base:arm64        1.18.4-2                         arm64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base-apps         1.18.4-2                         arm64        GStreamer helper programs from the "base" set
ii  gstreamer1.0-plugins-good:arm64        1.18.4-2+deb11u1+rpt1            arm64        GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:arm64        1.18.4-2                         arm64        GStreamer plugins from the "ugly" set
ii  gstreamer1.0-tools                     1.18.4-2.1                       arm64        Tools for use with GStreamer
ii  gstreamer1.0-x:arm64                   1.18.4-2                         arm64        GStreamer plugins for X11 and Pango
ii  libgstreamer-gl1.0-0:arm64             1.18.4-2                         arm64        GStreamer GL libraries
ii  libgstreamer-plugins-bad1.0-0:arm64    1.18.4-3                         arm64        GStreamer libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:arm64   1.18.4-2                         arm64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-dev:arm64 1.18.4-2                         arm64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.0-0:arm64                1.18.4-2.1                       arm64        Core GStreamer libraries and elements
ii  libgstreamer1.0-dev:arm64              1.18.4-2.1                       arm64        GStreamer core development files
```

**Comment by mc256** [comment] 2023-02-14 01:58
```
2023-02-14 01:47:25 DEBUG   handleStunPacket(): Ice candidate pair sdmmrssdW_2yxrUZ4sZ is connected. Round trip time: 3ms                                                                               [0/1105]
2023-02-14 01:47:25 DEBUG   receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
2023-02-14 01:47:25 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:47:25 ERROR   handleRemoteCandidate(): operation returned status code: 0x5a000012
2023-02-14 01:47:25 ERROR   signalingMessageReceived(): operation returned status code: 0x5a000012
2023-02-14 01:47:25 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x5a000012
2023-02-14 01:47:25 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_CONNECTED.
2023-02-14 01:47:26 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CONNECTED to ICE_AGENT_STATE_NOMINATING.
2023-02-14 01:47:26 DEBUG   handleStunPacket(): Ice candidate pair ZJv79DM6n_2yxrUZ4sZ is connected. Round trip time: 8ms
2023-02-14 01:47:26 DEBUG   iceAgentReadyStateSetup(): Selected pair sdmmrssdW_2yxrUZ4sZ, local candidate type: host. Round trip time 3 ms. Local candidate priority: 2130706431, ice candidate pair priority: 7962083765692399614
2023-02-14 01:47:26 DEBUG   iceAgentReadyStateSetup(): Freeing Turn allocations that are not selected. Total turn allocation count 2
2023-02-14 01:47:26 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
2023-02-14 01:47:26 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_CLEAN_UP
2023-02-14 01:47:26 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_CLEAN_UP
2023-02-14 01:47:26 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
2023-02-14 01:47:26 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
2023-02-14 01:47:26 INFO    onConnectionStateChange(): New connection state 3
2023-02-14 01:47:26 DEBUG   rtcPeerConnectionGetMetrics(): ICE local candidate Stats requested at 16763392460953174
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate IP Address: fd95:9b9e:5fe4:0000:703d:d22a:3169:a9d7
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: host
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 46386
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate priority: 2130706431
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: udp
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: N/A
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate Ice server source: N/A
2023-02-14 01:47:26 DEBUG   rtcPeerConnectionGetMetrics(): ICE remote candidate Stats requested at 16763392460955813
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate IP Address: fd95:9b9e:5fe4:0000:101a:56b0:0054:e76d
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: prflx
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 49993
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate priority: 1853817087
2023-02-14 01:47:26 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp
[5:31:37.197264627] [23575]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3866-0c55e522
2023-02-14 01:47:26 DEBUG   socketConnectionClosed(): Close socket 12
2023-02-14 01:47:26 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2023-02-14 01:47:26 DEBUG   socketConnectionClosed(): Close socket 13
2023-02-14 01:47:26 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
2023-02-14 01:47:26 DEBUG   dtlsSessionChangeState(): DTLS init completed. Time taken 300 ms
[5:31:37.403283189] [23575]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3866-0c55e522
[5:31:37.427741405] [23579]  INFO Camera camera.cpp:1035 configuring streams: (0) 1280x720-YUYV
2023-02-14 01:47:28 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:47:38 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:47:48 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:47:58 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:48:08 DEBUG   lwsWssCallbackRoutine(): Client is writable
2023-02-14 01:48:19 DEBUG   lwsWssCallbackRoutine(): Client is writable
^[2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Current duration: 60 seconds
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Selected local candidate ID: sdmmrssdW
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Selected remote candidate ID: 2yxrUZ4sZ
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Ice Candidate Pair state: 3
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Nomination state: nominated
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Packet send rate: 9.733333 pkts/sec
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Packet receive rate: 0.216667 pkts/sec
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Outgoing bit rate: 3469.600000 bps
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Incoming bit rate: 136.266667 bps
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Packet discard rate: 0.000000 pkts/sec
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Current STUN request round trip time: 0.003025 sec
2023-02-14 01:48:25 DEBUG   getIceCandidatePairStatsCallback(): Number of STUN responses received: 1
```

The `./samples/kvsWebrtcClientMasterGstSample` binary is able to detect the USB camera but no video stream from the AWS console. I don't know what causes this problem.

**Comment by niyatim23** [comment] 2023-02-14 17:04
That's great! Thanks for sharing this information. Closing this ticket assuming the issue is resolved. Feel free to open a new issue for anything else

**Closed by niyatim23** 2023-02-14 17:04 UTC
Labels: bug, needs-triage
