### ISSUE TITLE
[QUESTION] How to reduce video delay?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#642] opened 2020-07-22 13:30 UTC
I'm using Kinesis in a camera we are developing, but I found that there is a huge delay in the video being streamed. This delay is up to 1 minute.
My camera produces H264 frames at 22fps. When I play theses frames directly using ffplay, there is no delay. But on Kinesis, it is showing this behaviour. Is there any parameters, or anything I should tune to get a better result?

**Comment by suggestedfixes** [comment] 2020-07-22 19:35
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/637

Also this sdk has a 2 second jitterbuffer that drops the newest frames, we can send a request to drop older frames

**Comment by MushMal** [comment] 2020-07-22 19:43
@fernandoc1 how do you measure the delay? Can you please provide more information on your scenario? In case of WebRTC, there is a small jitter buffer that can re-send the frame packets but that's defaulted to 10 seconds I believe. There is absolutely nothing that can hold a buffer of 1 minute.

**Comment by suggestedfixes** [comment] 2020-07-22 19:56
@MushMal We found that gstreamer can hold the buffer for arbitrarily long by default and had to drop frames on latency.

**Comment by suggestedfixes** [comment] 2020-07-22 19:57
@MushMal I do not know fernadoc1, he's probably working on another device.

**Comment by MushMal** [comment] 2020-07-22 20:01
Which GStreamer element are you referring to? Rtsp source elements do have their own jitter buffer (which I am not sure what the default configuration is) but even they will have to drop frames as you've mentioned as they won't be able to store minutes worth of frame packets.

**Comment by fernandoc1** [comment] 2020-07-22 20:05
Probably I made some mistake about the length of the delay. But I wish to decrease it to be almost live streaming.
I created a video to show how I'm measuring the delay: [CameraDelay](https://youtu.be/0zSGglYlD6o)
In the left, I'm showing a stopwatch screen and at the right is my kinesis streaming.

**Comment by suggestedfixes** [comment] 2020-07-22 20:07
The element I'm referring to is rtspsrc,
drop-on-latency is disabled by default.

**Comment by MushMal** [comment] 2020-07-22 22:33
Interesting. It fluctuates between 20 seconds initially and around 1 minute mark the difference is about 10 seconds. I am inclined to think that this is more to do with the GStreamer source.

What's the source you are using? Is there a way to tune it somehow? Can you run the master sample and check the delay?

**Comment by fernandoc1** [comment] 2020-07-22 23:13
I'm just sharing the changes I made to the "kvsWebRTCClientMaster.c"
[main.cpp](https://gist.github.com/fernandoc1/1c31743a696833026147ef9371fa9070)
It is just a modification in the function that read packets from the filesystem, to a function that read from my shared memory source.
When I play this source directly with ffplay, there is less than 2 seconds delay. However, with Kinesis, the delay is huge.

**Comment by MushMal** [comment] 2020-07-22 23:29
The most the SDK latency will add is 10 seconds in bad network condition when retrying the RTP packets. Are you using JS viewer/Console playback on the player side?

**Comment by fernandoc1** [comment] 2020-07-23 00:06
Yes, I'm using the same code on the playback as it is available in your "amazon-kinesis-video-streams-webrtc-sdk-js" examples folder.
[amazon-kinesis-video-streams-webrtc-sdk-js examples](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/tree/master/examples)

**Comment by MushMal** [comment] 2020-07-23 00:26
Wondering if part of the latency is added by the browsers WebRTC implementation... Not yet sure. We really need to somehow splice in a timer in the master sample canned video @lherman-cs - what are your thoughts on this?

**Comment by lherman-cs** [comment] 2020-07-23 20:06
@MushMal I think that's a good idea. The only issue is that the video is really short, about 8 seconds. So, ideally, if we want to include a timer, I think we should at least have a 60 seconds video so that the timer can wrap around when it hits 60. This also means that we'll store 7.5x more frame data in the repo. What do you think @MushMal? I can expand the video and add the timer if this sounds good to you too.

Or we can modify the frame before pushing it, but we need to decode and encode the frames, or, if we used raw frames instead, we still need to encode it. So, I think this approach will be less favorable.

**Comment by lherman-cs** [comment] 2020-07-23 20:15
@fernandoc1 do you mind to share the inbound rtp stat graphs from chrome://webrtc-internals/? We should see a lot of NACKs. If not, I'm afraid that it's related to your media pipeline, ffmpeg.

**Comment by fernandoc1** [comment] 2020-07-23 20:47
Here you are:
![image](https://user-images.githubusercontent.com/249402/88337076-77b6ed00-cd0c-11ea-92a5-08242f44e842.png)

![image](https://user-images.githubusercontent.com/249402/88337113-87363600-cd0c-11ea-9e61-1494a167e78f.png)

**Comment by MushMal** [comment] 2020-07-23 21:17
@lherman-cs the number of frames is short but that's OK and they can be streamed in a loop. The timer, though, can be blitted on top of the current frame and will be continuous from the moment the frame is "produced" into the transceiver.

**Comment by lherman-cs** [comment] 2020-07-23 21:55
@fernandoc1 I'm still not sure what caused the delay. But, I noticed that there's no network issue, your nack count is 0. This implies that the frames are not pushed fast enough. 

Which WebRTC C SDK version are you using? Were you connected through TURN or peer-to-peer?

**Comment by lherman-cs** [comment] 2020-07-23 21:58
@fernandoc1 Also, could you try to use Firefox and see if the issue is reproducible?

**Comment by fernandoc1** [comment] 2020-07-24 12:00
I have tried in Firefox, but the Javascript code is not working there. Even the official amazon code found here is unable to connect [amazon-kinesis-video-streams-webrtc-sdk-js](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html). It throws the following error:
![image](https://user-images.githubusercontent.com/249402/88389037-0fa7eb80-cd8c-11ea-8cae-e7bd6f1080e3.png)

**Comment by lherman-cs** [comment] 2020-07-24 20:55
@fernandoc1 I'm sorry for the inconvenience. This is a known issue. Our WebRTC C SDK currently ignores the transceiver directions that we get from remote descriptions. For some Firefox versions, the browser API will return an error when the answer contains wrong transceiver direction. The issue is tracked here, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/468.

To avoid this issue, could you enable video and audio from the JS side? This way the transceiver direction from the JS side will be `sendrecv` instead of `recvonly`.

**Comment by fernandoc1** [comment] 2020-07-27 17:13
I've created a video in Firefox, showing how is my direct streaming with a TCP socket, compared to the Kinesis streaming.
[TCP Streaming X Kinesis streaming](https://youtu.be/biLbMQL18W0)

**Comment by chehefen** [comment] 2020-07-27 17:22
Hi @fernandoc1, can you show us the logs from the webrtc sdk during the delay?

**Comment by fernandoc1** [comment] 2020-07-27 19:02
I have created another video with the terminal output, running on Google Chrome.
[Terminal output](https://youtu.be/4AHNCm8gfRQ)

**Comment by MushMal** [comment] 2020-07-28 08:24
Seems to be a steady 15 second delay. Any change if you try running it in a different network configuration? I am interested in eliminating the media pipeline from it. Do you have the debug logs

**Comment by fernandoc1** [comment] 2020-07-28 10:32
Actually, I'm running the setup in the same network, with a Gigabit switch linking the camera and the computer. I can't make that better. The other option I have is to try to connect the computer to the mobile network and try to access the camera. The source code with the changes I made, is still available here ([main.cpp](https://gist.github.com/fernandoc1/1c31743a696833026147ef9371fa9070)). I have no idea on how to make this flow faster, because the streaming I'm showing on the TCP connection is the same I'm serving on the Kinesis setup. The last test I created, Kinesis is running on the PC, which is quite fast. I don't know where Kinesis is buffering the video stream to make such a huge delay.
In order to get the debug logs, what are your recommendations?

**Comment by fernandoc1** [comment] 2020-07-28 16:43
Finally I was able to fix the issue.
What was happening is that I had two sleeps in sequence. One waiting for my frame to became ready and another at the end of the write frame loop in the Kinesis code, here ([kvsWebRTCClientMaster.c#L249](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/325bf161329638a20c25be21d74c6064894d9f75/samples/kvsWebRTCClientMaster.c#L249)).
By just commenting that line, now, my streaming is in realtime.

**Comment by MushMal** [comment] 2020-07-28 16:51
D’oh..

Resolving

**Closed by MushMal** 2020-07-28 16:51 UTC
Labels: question
