### ISSUE TITLE
[BUG] CI build fails due to missing secrets

### ISSUE THREAD

**Issue by thinkski** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1415] opened 2022-02-23 23:16 UTC
`sample-check` CI workflow is failing -- secrets are unavailable to CI:
```
Error: Input required and not supplied: aws-region
```

**Comment by disa6302** [comment] 2022-02-23 23:17
@thinkski ,

It is not a bug but the nature of GHA CI that does not allow using secrets on forked branches. We will look into it.

**Comment by thinkski** [comment] 2022-02-24 00:37
Thank you. It's showing up on PR CI builds.

**Comment by niyatim23** [comment] 2022-02-25 19:20
Hi @thinkski, thank you for bringing this up. I have an update to fix this in the `develop` branch. Can you please rebase from `develop` to see if it works for you?

**Comment by disa6302** [comment] 2022-03-03 00:39
@thinkski ,
Can you please rebase your PR to pick the changes? Thank you!

**Comment by disa6302** [comment] 2022-03-09 07:31
Closing due to no response. 
@thinkski , please rebase your PR to include the change. We will reopen if the test still fails

**Comment by thinkski** [comment] 2022-03-09 07:44
@disa6302 Sorry, didn't see this earlier. I rebased on the Feb 25 commit `b4f4516`. Unfortunately, still encounter same issue.

**Comment by disa6302** [comment] 2022-03-09 07:48
We will look into this then. Thank you for confirming!

**Comment by sirknightj** [comment] 2023-02-10 23:12
Should be fixed as of #1631 and #1634

**Closed by sirknightj** 2023-02-10 23:12 UTC
Labels: bug, pending-action
