### ISSUE TITLE
[Enhancement] Use a Hashtable to Store Sessions

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#450] opened 2020-05-13 16:51 UTC
The current sample code works well for PC for iterating through sessions, but in devices, every bit of tiny optimization helps. Usually, C does not include a standard library for hash tables and it's usually time-consuming to build it from scratch. We found that PIC had a HashTable data structure. This improvement could allow more efficient lookups/insertions/deletions to sessions.

**Comment by MushMal** [comment] 2020-05-13 17:15
@suggestedfixes it is true that PIC has an optimized hash table implementation that we use throughout the derived codebases. However, I am not sure whether you will see any improvements with a hash table vs list iteration on a dozen or so elements representing sessions. Worse, if you use generic hash table (not the tight-packed optimized version in PIC) you will actually decrease the performance due to likely cache locality thrashing.

Could you please include more details?

**Comment by suggestedfixes** [comment] 2020-05-13 17:34
You are right. Theoretical complexity is better than iteration. I agree that there could some overheads for multiple levels of indirection or client ids map to the same bucket.

**Comment by suggestedfixes** [comment] 2020-05-13 17:35
Use case would be faster lookups joining and deleting sessions.

**Comment by MushMal** [comment] 2020-05-13 17:51
Are you referring to sessionCleanupWait function in Samples/Common.c? This function has a loop where it iterates through the sessions and cleans up the ones that have expired: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L769

The issue is that replacing this loop with hash table recursion will be at most as performant as linear lookup that's there.

Another question is the emulation of the wait for the media pipeline https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L774 Perhaps, here we can have a timeout that will kill the media thread instead of blocking. This said, I would like to understand whether on your platform you actually have any performance bottlenecks when it comes to iterating an array of max 10 elements?

**Comment by suggestedfixes** [comment] 2020-05-13 18:39
I think what we are solving right now is to cleanup stale sessions greedily. One way to do that is do a quick lookup by ClientId and evict the Session. But one thing I failed to consider is that we have to wait for locks to unlock anyways.

**Comment by suggestedfixes** [comment] 2020-05-13 18:40
But like you mentioned, it might not worth the effort and the performance could be worse.

**Comment by suggestedfixes** [comment] 2020-05-13 23:03
For the second question, what would be the consequences of replacing the spinlock with a RW lock?

**Comment by MushMal** [comment] 2020-05-14 00:44
We certainly can replace the spinlock with the conditional variable. Just not sure if on a real application case it will provide any perf gains. This said, I would like that solution more as it's more scalable. Can I ask you to open a separate issue that tracks the conditional variable changes?

**Comment by chehefen** [comment] 2020-05-14 20:37
@suggestedfixes I think what you really need is some kind of magic word that triggers tear down of streaming sessions. You can send the magic word through data channel to trigger tear down of a streaming session.

**Comment by suggestedfixes** [comment] 2020-05-15 00:20
@chehefen Nice idea! Since we not not familiar with the code base, is it safe to free streamming session right at the data channel callback?

**Comment by chehefen** [comment] 2020-05-15 20:55
@suggestedfixes you cant because the callback originates from within the RTCPeerConnection, it cannot free itself. You need to set a flag like we did in the connection state changed callback and clean it up in another thread.

**Comment by MushMal** [comment] 2020-05-21 05:14
@suggestedfixes any further action on this issue? Can you close this and open a separate issue tracking the cleanup?

**Comment by MushMal** [comment] 2020-05-23 08:32
Going to resolve this. Please re-open if needed

**Closed by MushMal** 2020-05-23 08:32 UTC
