### ISSUE TITLE
[QUESTION] Undefined Symbols When Attempting to Integrate into MacOS Project

### ISSUE THREAD

**Issue by kyledecot** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#753] opened 2020-08-26 19:21 UTC
I'm attempting to use this library in a MacOS project however when building I'm getting the following errors:

```
Undefined symbols for architecture x86_64:
  "_acceptStateMachineState", referenced from:
      _signalingGetIceConfigInfoCout in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetIceConfigInfo in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _acceptSignalingStateMachineState in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
  "_base64Decode", referenced from:
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_base64Encode", referenced from:
      _sendLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_compareJsonString", referenced from:
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _describeChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _createChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _getChannelEndpointLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _getIceConfigLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_createFile", referenced from:
      _createFileIfNotExist in libkvsWebrtcSignalingClient.a(FileCache.c.o)
     (maybe you meant: _createFileIfNotExist)
  "_createRequestInfo", referenced from:
      _describeChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _createChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _getChannelEndpointLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _getIceConfigLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _deleteChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _connectSignalingChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_createStateMachine", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_fileExists", referenced from:
      _createFileIfNotExist in libkvsWebrtcSignalingClient.a(FileCache.c.o)
  "_freeRequestInfo", referenced from:
      _freeLwsCallInfo in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_freeStateMachine", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_getInt16", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_getRequestHost", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_getServiceCallResultFromHttpStatus", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_getStateMachineCurrentState", referenced from:
      _signalingClientGetCurrentState in libkvsWebrtcSignalingClient.a(Client.c.o)
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _refreshIceConfigurationCallback in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_getUserAgentString", referenced from:
      _createValidateChannelInfo in libkvsWebrtcSignalingClient.a(ChannelInfo.c.o)
  "_globalAtomicExchange", referenced from:
      _fromReadySignalingState in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
      _fromConnectSignalingState in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
      _fromConnectedSignalingState in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
      _fromDisconnectedSignalingState in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalAtomicIncrement", referenced from:
      _signalingClientSendMessageSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientConnectSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientDisconnectSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientDeleteSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientGetIceConfigInfoCount in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientGetIceConfigInfo in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientGetCurrentState in libkvsWebrtcSignalingClient.a(Client.c.o)
      ...
  "_globalAtomicLoad", referenced from:
      _awaitForThreadTermination in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetIceConfigInfoCout in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDisconnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDeleteSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _refreshIceConfigurationCallback in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _getIceConfig in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      ...
  "_globalAtomicStore", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _initializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _uninitializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDisconnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDeleteSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _validateIceConfiguration in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      ...
  "_globalCancelThread", referenced from:
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalConditionVariableBroadcast", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _reconnectHandler in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _terminateConnectionWithStatus in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsListenerHandler in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalConditionVariableCreate", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _initializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_globalConditionVariableFree", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _uninitializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_globalConditionVariableWait", referenced from:
      _awaitForThreadTermination in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _connectSignalingChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _writeLwsData in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalCreateMutex", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _initializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_globalCreateThread", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _connectSignalingChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalCustomLogPrintFn", referenced from:
      _createSignalingClientSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _freeSignalingClient in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientSendMessageSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientConnectSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientDisconnectSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientDeleteSync in libkvsWebrtcSignalingClient.a(Client.c.o)
      _signalingClientGetIceConfigInfoCount in libkvsWebrtcSignalingClient.a(Client.c.o)
      ...
  "_globalDetachThread", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _connectSignalingChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalFreeMutex", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _uninitializeThreadTracker in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_globalGetTime", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetCurrentTime in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDeleteSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _describeChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _createChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _getChannelEndpoint in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      ...
  "_globalLockMutex", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _awaitForThreadTermination in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingStoreOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _describeChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _createChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      ...
  "_globalMemAlloc", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalMemCalloc", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _createLwsCallInfo in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _createValidateChannelInfo in libkvsWebrtcSignalingClient.a(ChannelInfo.c.o)
      _signalingCacheLoadFromFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
      _signalingCacheSaveToFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
  "_globalMemFree", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _freeLwsCallInfo in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _receiveLwsMessageWrapper in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _freeChannelInfo in libkvsWebrtcSignalingClient.a(ChannelInfo.c.o)
      _signalingCacheLoadFromFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
      ...
  "_globalThreadSleep", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalThreadSleepUntil", referenced from:
      _describeChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _createChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _getChannelEndpoint in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _getIceConfig in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _deleteChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _connectSignalingChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_globalTryLockMutex", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_globalUnlockMutex", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _awaitForThreadTermination in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingStoreOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _describeChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _createChannel in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      ...
  "_loggerGetLogLevel", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_loggerSetLogLevel", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_lws_add_http_header_by_name", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_callback_on_writable", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_callback_on_writable_all_protocol", referenced from:
      _wakeLwsServiceEventLoop in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_cancel_service", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_client_connect_via_info", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_client_http_body_pending", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_context_destroy", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_lws_create_context", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_lws_frame_is_binary", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_get_context", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_get_opaque_user_data", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_hdr_custom_copy", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_http_client_http_response", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_http_client_read", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_is_final_fragment", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_is_first_fragment", referenced from:
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_service", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_set_log_level", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lws_write", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _lwsWssCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_lwsl_hexdump_level", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_packageTags", referenced from:
      _createValidateChannelInfo in libkvsWebrtcSignalingClient.a(ChannelInfo.c.o)
  "_readFile", referenced from:
      _signalingCacheLoadFromFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
      _signalingCacheSaveToFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
  "_removeRequestHeader", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_removeRequestHeaders", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_requestRequiresSecureConnection", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_resetStateMachineRetryCount", referenced from:
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_setStateMachineCurrentState", referenced from:
      _signalingConnectSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingDeleteSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_signAwsRequestInfo", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_signAwsRequestInfoQueryParam", referenced from:
      _lwsCompleteSync in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_singleListDeleteHead", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_singleListGetHeadNode", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_singleListGetNodeCount", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_singleListGetNodeData", referenced from:
      _lwsHttpCallbackRoutine in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_stackQueueCreate", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueEnqueue", referenced from:
      _signalingStoreOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueFree", referenced from:
      _freeSignaling in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueGetIterator", referenced from:
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueIteratorGetItem", referenced from:
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueIteratorNext", referenced from:
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _signalingGetOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stackQueueRemoveItem", referenced from:
      _signalingRemoveOngoingMessage in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_stepStateMachine", referenced from:
      _stepSignalingStateMachine in libkvsWebrtcSignalingClient.a(StateMachine.c.o)
  "_strtoui32", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _receiveLwsMessage in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
  "_strtoui64", referenced from:
      _describeChannelLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _getIceConfigLws in libkvsWebrtcSignalingClient.a(LwsApiCalls.c.o)
      _deserializeSignalingCacheEntries in libkvsWebrtcSignalingClient.a(FileCache.c.o)
  "_timerQueueAddTimer", referenced from:
      _validateIceConfiguration in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _refreshIceConfigurationCallback in libkvsWebrtcSignalingClient.a(Signaling.c.o)
      _getIceConfig in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_timerQueueCreate", referenced from:
      _createSignalingSync in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_timerQueueFree", referenced from:
      _terminateOngoingOperations in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_timerQueueGetTimersWithCustomData", referenced from:
      _validateIceConfiguration in libkvsWebrtcSignalingClient.a(Signaling.c.o)
  "_validateTags", referenced from:
      _createValidateChannelInfo in libkvsWebrtcSignalingClient.a(ChannelInfo.c.o)
  "_writeFile", referenced from:
      _signalingCacheSaveToFile in libkvsWebrtcSignalingClient.a(FileCache.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I built this library using the `-DBUILD_STATIC_LIBS` argument. I then added the two `.a` files to my Xcode project. I updated my build settings Header Search Paths to include the path to this repo: 

<img width="1059" alt="Screen Shot 2020-08-26 at 3 20 38 PM" src="https://user-images.githubusercontent.com/192464/91347045-b4648100-e7af-11ea-827b-c18ce397ab95.png">

In my bridging header I have:

```
#include <com/amazonaws/kinesis/video/webrtcclient/Include.h>
#include <com/amazonaws/kinesis/video/client/Include.h>
```

In my `AppDelegate.swift` I am attempting to call `createSignalingClientSync` which then calls the functions Xcode is unable to find.

What do I need to add to ensure that Xcode can find these functions?

**Comment by MushMal** [comment] 2020-08-26 20:45
Sorry, I would like to clarify. Are you having issues with building on mac OS or you have issues building in xCode?

Can you validate that the build instructions in the readme produce libraries with no problems?

If this is purely xCode integration issue then would you mind updating the description to reflect that?

**Comment by kyledecot** [comment] 2020-08-26 21:10
> Sorry, I would like to clarify. Are you having issues with building on mac OS or you have issues building in xCode?

I'm attempting to integrate this into a MacOS application that I'm building.

> Can you validate that the build instructions in the readme produce libraries with no problems?

Yes–I am able to build/produce the libraries with no problem.

> If this is purely xCode integration issue then would you mind updating the description to reflect that?

Done ✅

**Comment by MushMal** [comment] 2020-08-26 21:38
Thanks @kyledecot for the clarification. Anyone has experience with this?

**Comment by disa6302** [comment] 2020-09-05 13:37
@kyledecot , 

Not sure what the issue could be. Considering the signaling client library generation is fine and the linking issue is seen while integrating with your Swift app, I would suggest to check the architecture of the app binary and see if it is x86_64 as well. It is possible the library and app binary architectures are different. If the architectures are not the same, based on the platform, you can cross compile the SDK to generate the platform specific binaries and see if it solves your problem. 

I am closing this issue since there is nothing much we can do here since the issue is centric to XCode settings. 
Feel free to open a new issue if you have any questions. Thanks!

**Closed by disa6302** 2020-09-05 13:37 UTC
Labels: question
