### ISSUE TITLE
Failed to stream Video Data stream from Nvidia jetson Nano using WebRTC

### ISSUE THREAD

**Issue by shailesharya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1117] opened 2021-04-07 11:56 UTC
Hey,
I'm trying to build the Amazon Kinesis Video Streams C WebRTC SDK on Nvidia Jetson Nano. I have followed the mentioned steps.
The default kvsWebrtcClientMaster runs and prints "Signaling client connection to socket established" but fails to send the video frame to the test webpage with an error code: 0x5a000005. I'm seeking help with this issue. 
** Logging ** 
I'm attaching the log file.
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6271329/log.txt)

**Comment by disa6302** [comment] 2021-04-07 20:05
@shailesharya , 

0x5a000005 is not an error, it is a status code indicating the SDK detected TCP candidates. From the logs, it looks like the candidate pair is chosen and the connection is established. 
Can you give a few more details such as your set up, what version of the SDK you are using, if you made any changes to the sample? 

One more thing you can check is `webrtc-internals` on the browser you are using. Check if there are packets flowing. Also, the logs seem incomplete, please attach the complete logs.

**Comment by shailesharya** [comment] 2021-04-08 10:17
Setup Details:
Platform: Nvidia Jetson Nano Developer Kit (4 GB)
Official OS for Jetson Nano[ Jetson Nano Developer Kit SD Card Image](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write)
Camera: USB Webcam for Jetson Nano
Internet Connectivity: via ethernet cable

SDK Version: v1.4.0 (I'll Try v1.5.0)

web-internals Screen shot:
![2021-04-08 (2)](https://user-images.githubusercontent.com/41483772/114009967-445bc480-9881-11eb-89b5-81c69fcc92c2.png)

WebRTC Test Page:
![2021-04-08 (3)](https://user-images.githubusercontent.com/41483772/114010307-9866a900-9881-11eb-87c6-0e2b518ef898.png)
I'm able to hear sound on this page while running the viewer.

Please find the log file.
[log2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6277818/log2.txt)

**Comment by shailesharya** [comment] 2021-04-08 11:40
I have tried with SDK version: v1.5.0
Still, I'm facing errors. I'm attaching the log file.

AWS_KVS_LOG_LEVEL = 5
[logV1.5 AWS_log_level = 5.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6278231/logV1.5.AWS_log_level.5.txt)

AWS_KVS_LOG_LEVEL = 2
[logv1.5 AWS_log_level = 2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6278276/logv1.5.AWS_log_level.2.txt)

WebRTC Internals 
![2021-04-08 (5)](https://user-images.githubusercontent.com/41483772/114020417-3744d280-988d-11eb-98bb-9c404db82a09.png)

Please help me with this.

**Comment by disa6302** [comment] 2021-05-04 17:28
@shailesharya , 

From the screenshot, it looks like you are getting master feed and you are also getting packets. Still not sure what the issue is. 
Are you not seeing video and hearing audio in the test page?

**Comment by shailesharya** [comment] 2021-05-07 12:37
> @shailesharya ,
> 
> From the screenshot, it looks like you are getting master feed and you are also getting packets. Still not sure what the issue is.
> Are you not seeing video and hearing audio in the test page?


@disa6302 
I'm able to hear the audio but the video is not coming from master. It shows only black screen!

**Comment by disa6302** [comment] 2021-05-07 18:04
I see the video frame in the screenshot (white ball in  a black background). Does it get stuck?

**Comment by shailesharya** [comment] 2021-05-07 18:11
No, the white ball keeps on moving with audio being played in background.

**Comment by disa6302** [comment] 2021-05-07 18:14
That is the expectation. Which means it works. I am still not sure what the expectation is? That is the default video with the sample.

**Comment by shailesharya** [comment] 2021-05-09 13:00
> That is the expectation. Which means it works. I am still not sure what the expectation is? That is the default video with the sample.

Isn't it suppose to send the live video stream from the MASTER node using the camera attached to it?

**Comment by disa6302** [comment] 2021-05-09 13:31
You need to run the Gstreamer sample to send camera feed. Closing this issue because there really is no issue here

**Closed by disa6302** 2021-05-09 13:31 UTC
Labels: question
