### ISSUE TITLE
[FEATURE] Video resolution change support

### ISSUE THREAD

**Issue by thinkski** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1370] opened 2022-01-12 20:08 UTC
Viewers may wish to communicate a new desired video resolution to the sender. For instance, video may be minimized or full-screen, which may make a smaller or larger resolution more efficient or desirable, respectively. In such cases, the viewer may [applyConstraints](https://webrtc.org/getting-started/media-capture-and-constraints#constraints) on the video track, which are signaled to the sender via [COP](https://datatracker.ietf.org/doc/html/draft-westerlund-avtext-codec-operation-point-00) (RTCP message) or SDP.

Please add support for these RTCP messages and SDP renegotiation. Ideally, there would be an `onConstraintsChange()` or similar callback that could be used in an application to then actuate the encoder.

**Comment by disa6302** [comment] 2022-01-12 20:21
@thinkski , 

Thank you for the request. We will look into this and get back when there is an update.

**Comment by disa6302** [comment] 2022-01-12 22:05
On another note, this is a duplicate of this ticket: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1252. So closing this out, since we have already included the request for internal tracking.

**Closed by disa6302** 2022-01-12 22:05 UTC
Labels: enhancement
