### ISSUE TITLE
turnConnectionAddPeer(): Add peer failed. Max peer count reached

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#469] opened 2020-05-19 21:30 UTC
I'm currently testing connection and disconnection with with same client id with turn. It seems like the turn peer count never decrements. As a result turnConnectionAddPeer will fail.

**Comment by chehefen** [comment] 2020-05-19 22:53
how are you testing connection and disconnection?

**Comment by suggestedfixes** [comment] 2020-05-19 23:25
I'm using a modified viewer example. Could it be that it is missing freeSampleStreamingSession, which in turn will free the peer connection?

**Comment by suggestedfixes** [comment] 2020-05-19 23:29
Actually, freeSampleConfiguration does freeSampleStreamingSession.

**Comment by chehefen** [comment] 2020-05-20 00:10
if freeSampleStreamingSession is called the underlying turn connection should also be freed. it shouldnt accumulate peers.

**Comment by suggestedfixes** [comment] 2020-05-20 23:07
Can be replicated using kvs test page with same client ID and master sample
[maxpeer.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4659674/maxpeer.txt)

**Comment by suggestedfixes** [comment] 2020-05-20 23:07
Just repeatedly open and close viewer with the same client ID

**Comment by suggestedfixes** [comment] 2020-05-20 23:17
This is with offer check disabled, replicated in 3 open and closes with the same client id.
[maxpeer2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4659711/maxpeer2.txt)

**Comment by suggestedfixes** [comment] 2020-05-21 00:34
To add to my comments, maxpeer.txt and maxpeer2.txt can be reproduced with master example with kvs webrtc test page.

**Comment by chehefen** [comment] 2020-05-21 17:32
You cant just simply disable the offer check. By doing that you are not cleaning up the candidates and candidate pairs from previous session and they will just build up over time. You have to clean things up properly by doing ice restart or freeing the peerConnection.

**Comment by suggestedfixes** [comment] 2020-05-21 19:03
@chehefen 
This is reproducible with offer check enabled maxpeer.txt. I think this occurred when session cleanup has terminate flag set to true but not yet cleaned up the session. As a result, new connections are using the old session objects and inherited old peers.

Also what are the steps doing ice restart and freeing the peerConnection on the master side?

**Comment by chehefen** [comment] 2020-05-22 19:04
@suggestedfixes the offer check blocks new offers but doesnt block new remote ice candidate messages. Without cleaning up the old ice candidates, it would eventually grow out of space. The root cause is old streaming session dont get cleaned up promptly. I think this commit will help you: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/2ad4bd721318de941ca0505ee65e5e0c0f348a32

**Comment by chehefen** [comment] 2020-05-22 19:19
@suggestedfixes you can checkout this unit test on how to do ice restart: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/PeerConnectionFunctionalityTest.cpp#L436

**Comment by sharadrj** [comment] 2020-05-27 22:21
Closing as duplicate since the issue is being discussed in #475

**Closed** 2020-05-27 22:22 UTC
Labels: question
