### ISSUE TITLE
[BUG]Device crashed due to destroyed resources ahead

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1266] opened 2021-09-09 13:09 UTC
Thread exited timeout，device crashed due to destroyed resources ahead

Function call process：freePeerConnection ->freeIceAgent ->freeConnectionListener
Key log：
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7136694/log.txt)

[webrtc_crash.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7136633/webrtc_crash.log)

**Comment by disa6302** [comment] 2021-09-10 20:02
@August88618 , 

There is not enough information here. Can we get a stack trace or more info on when it is observed?

**Comment by August88618** [comment] 2021-09-13 01:47
@disa6302 
Here is dump stack trace:
#0  0xb6b458c0 in pthread_mutex_lock ()
   from /opt/arm-linux-gnueabihf-gcc4.9.4-uclibc1.0.31/arm-buildroot-linux-uclibcgnueabihf/sysroot/lib//libc.so.0
#1  0x002024ba in defaultLockMutex ()
#2  0xb6e4a1ac in connectionListenerReceiveDataRoutine () from /home/33588/upload/AWS/HBProject/Libs/app/libkvsWebrtcClient.so
#3  0xb6b47c5a in start_thread ()
   from /opt/arm-linux-gnueabihf-gcc4.9.4-uclibc1.0.31/arm-buildroot-linux-uclibcgnueabihf/sysroot/lib//libc.so.0
#4  0xb6b0adea in clone ()
   from /opt/arm-linux-gnueabihf-gcc4.9.4-uclibc1.0.31/arm-buildroot-linux-uclibcgnueabihf/sysroot/lib//libc.so.0
Backtrace stopped: previous frame identical to this frame

**Comment by disa6302** [comment] 2021-09-23 19:56
Closing since the changes have been merged. @August88618 , please feel free to reopen or open a new issue if the issue is not resolved.

**Closed by disa6302** 2021-09-23 19:56 UTC
Labels: pending-research
