### ISSUE TITLE
Crash in socketConnectionClosed()

### ISSUE THREAD

**Issue by docee** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#927] opened 2020-11-06 02:31 UTC
**Describe the bug**

When the Signaling Client disconnects from the server, calling closePeerConnection will crash.

**SDK version number**
Develop branch (3f78b57e44ca877d50db473afc27342ea75e87e5)

**To Reproduce**
1. Connect to the signaling server and establish a PeerConnection.
2. Wait for the signaling server to automatically disconnect.
3. Call closePeerConnection().

**Screenshots**
The following is GDB debugging information:

![392251604538846_ pic_hd](https://user-images.githubusercontent.com/4263278/98319109-ffeea300-201a-11eb-92d6-4250f0644ac1.jpg)

**Comment by MushMal** [comment] 2020-11-06 05:34
There is very little information in the ticket.

1) Can you please build debug version of the binaries so your stack trace contains symbolic information. As is, it's impossible to tell what's going on
2) Do a clean build including the open source dependencies.
3) Include detailed information about your platform and OS including the versions
4) Explain clearly what your scenario is. What do you mean by "wait for signaling server to automatically disconnect" - it doesn't do that.

Can you include details on your scenario/application? Can you run the stock master sample?


Removing "bug" tag as it's not clear what the issue is

**Comment by docee** [comment] 2020-11-06 07:17
> There is very little information in the ticket.
> 
> 1. Can you please build debug version of the binaries so your stack trace contains symbolic information. As is, it's impossible to tell what's going on
> 2. Do a clean build including the open source dependencies.
> 3. Include detailed information about your platform and OS including the versions
> 4. Explain clearly what your scenario is. What do you mean by "wait for signaling server to automatically disconnect" - it doesn't do that.
> 
> Can you include details on your scenario/application? Can you run the stock master sample?
> 
> Removing "bug" tag as it's not clear what the issue is

Our program is currently running in the Linux 3.10.14 embedded system of MIPS architecture.

We use the channel pool design to control the cost, so before connecting to the signaling server, we will ask the server for Channel information and STS credentials. Therefore, when the signaling server is disconnected, we will not reconnect to the signaling server again. Even if the signaling has been disconnected, it will not affect the established Peer Connection.

We found that if the signaling connection is disconnected, call `closePeerConnection()` will crash.

It should be that `pIceAgent ->pConnectionListener` is not set to `NULL` after being released before `iceAgentShutdown(PIceAgent pIceAgent)` is called.

If you remove the reconnection signaling code in the sample, you should be able to reproduce this problem.

**Comment by MushMal** [comment] 2020-11-06 07:26
I am not following. Are you saying that you have a custom application and you are calling closePeerConnection() and following freePeerConnection() and it crashes? PeerConnection is orthogonal to signaling - they don't share any objects.

Can you isolate the issue and come up with exact repro steps? Perhaps a unit test or something that demonstrates the issue? We won't be able to debug your application and I can't understand what the issue is from your description. 

Please try to provide details to avoid multiple iterations and re-engagements.

**Comment by suggestedfixes** [comment] 2020-11-06 17:58
This might be related, or timing related. This particular commit causes a similar crash.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/a15d2a0f290d2f58b218d9bb88a71a7d639520fd

**Comment by MushMal** [comment] 2020-11-07 00:38
I am not aware of any crashes nor I can make any parallels as I don't understand what the scenario is. This issue is not actionable as is and will be closed unless we get precise information to analyze.

**Comment by MushMal** [comment] 2020-11-08 06:14
Please try to get more information as we would like to get to the bottom of this issue and if there is an actual issue then provide a fix ASAP.
We need detailed information on

* Assets in question and their commit versions
* Platform you are using
* Exact steps/scenario you are running
* Whether any modifications are made as we will be looking at stock samples to repro
* Verbose logs
* Debug crash dump/backtrace for all of the threads.

Anything to help to recreate the issue or try to understand what might be wrong.

**Comment by hassanctech** [comment] 2020-11-11 20:59
@docee We just released a new version 1.4.0 yesterday.  Can you please upgrade to that version and let us know if you're still seeing the same issue?

**Comment by docee** [comment] 2020-11-12 13:00
> @docee We just released a new version 1.4.0 yesterday.  Can you please upgrade to that version and let us know if you're still seeing the same issue?

After updated to version 1.4.0, it did not crash again.  I think it might be solved?😀

**Comment by hassanctech** [comment] 2020-11-12 16:03
Great! If you encounter the issue again please open a new issue.  Closing.

**Closed by hassanctech** 2020-11-12 16:03 UTC
Labels: awaiting response, question
